== Chapter I.

[.chapter-synopsis]
* Locality of Airton
* Parentage of William Ellis
* Meeting held by R. Haydock
* Convincement, Character, and Settlement of William Ellis
* Commencement of his ministry
* Marriage
* Character of Alice Ellis
* Notices of John Richardson and Mary Frost
* Letters from John Real, Thomas Qwin, and James Tatham
* Birth and death of Jonathan Ellis

Among the grassy hills in the upper part of Airdale, in the West-Riding of Yorkshire,
a group of villages, named Airton, Calton, and Scostrop,
lie in close contact with each other.
These villages are six miles east of the town of Settle,
they are included in the parish of Kirkby Malhamdale,
and are near to the remarkable limestone cliffs of Malham Cove and Gordale Scar.
In one of these villages a cotton manufactory is now carried on;
but in former days many of the inhabitants were hand-loom linen-weavers.
Of this class, in the 17th century, was Stephen Ellis, of Calton,
who had several children, and whose son William was born on the 5th of the 8th month,
1658.

William Ellis lived with his father until he attained his sixteenth year,
and he then removed to Skipton, having engaged himself to John Stott, of that place,
who was also a linen-weaver, and who, with his wife, had joined the Society of Friends.
Two years after William Ellis had removed to Skipton, Edger Haydock,
of Penketh near Warrington, in Lancashire, appointed a meeting at Lower Bradley,
two miles from Skipton.
This meeting was attended also by Eleanor Lowe, afterwards the wife of Roger Haydock,
and her cousin Elizabeth Hodson,
both of whom had likewise received gifts in the ministry,
in the exercise of which they were travelling.
William Ellis having heard of this meeting, signified a wish to attend it,
which was readily acceded to by his master and mistress.
Eleanor Haydock describes this meeting, in a Testimony concerning her husband,
published in 1700, as "`a good meeting,
where William Ellis and some others were convinced.`"

Abigail Stott, the wife of the master of William Ellis,
in a notice respecting the convincement of the latter,
describes him before attending the meeting at Bradley,
as being in bondage to the spirit of the world,
and much carried away by folly and vanity; but afterwards,
not only as convinced of the way of truth and righteousness, but as being,
in a good measure, brought into obedience to the same; and maintaining a humble,
peaceable, and self-denying life, circumspect both in his words and ways,
lest he should offend the Lord.
She also says, that he was a good example to her servants,
and a reprover of vice and the appearance of evil in her children,
whom he often restrained from vanity and that which corrupts youth;
that he often laboured with his hands when he might have slept,
in order that he might get to meetings; that after he had done his work,
he often retired into places more free from noise and hurry;
that he loved honest-minded Friends,
and all the neighbours who were in any measure well-minded, whether rich or poor,
but was especially a visitor of the needy; that through faith in Christ Jesus,
he denied himself of the glory and friendship of the world;
and that he often suffered and was reviled for confessing Christ before men.

The particulars of the sufferings of William Ellis for conscience`' sake,
beyond the common distraints made upon Friends for refusing to comply with the unjust,
but legalised demands, for the compulsory support of a national church establishment,
do not appear to have been recorded, except in one case.
In this case, Abigail Stott says, that "`as he was passing through Skiptou,
to attend a meeting for worship with his friends, he was taken by violent hands,
and imprisoned in the tolbooth.
How long he remained a prisoner does not appear.

When about twenty-one years of age, William Ellis removed to Airton,
where he resided during the remainder of his life.
There is reason to believe that in his settling at Airton,
he established himself in a very humble way as a linen-weaver;
but that by industry and good economy he gradually improved in his temporal circumstances,
until he became a master-weaver, employing a considerable number of men.
He was liberal, according to his circumstances, when his means were small,
and his liberality increased with the increase of his means.

Soon after his removal to Airton, he came forth in the ministry,
bearing a public testimony to the Truth of which he was made a partaker,
and in which he walked uprightly, so as to be a good example.
In process of time he became an able minister of the Gospel,
and a diligent labourer in the vineyard of the Lord.
He cherished a deep concern for the maintenance of Gospel order in the church of Christ,
and while but a young man,
began to express what was upon his mind in meetings for discipline;
but not being forward to speak in these meetings,
and having a reverent regard for those who were in Christ before him,
and being careful to speak in the fear of God,
and in a sense and savour of the divine life upon his mind,
and demeaning himself with great humility, his labours were well received.

In the early part of 1688, William Ellis was married to Alice Davie or Davy;
he was then about 30 years of age.
Of the early days of Alice Ellis no account appears to have been preserved;
but she proved a true helper to her husband,
and was zealously concerned for the promotion of the cause of Truth; and for this object,
cheerfully gave him up to travel in the Lord`'s service;
and she heartily united with him in acts of hospitality and benevolence:
she also became a minister of the Gospel,
and several times accompanied other Friends in religious
visits to different parts of the country,
but her labours were chiefly exercised in her own meeting and the
other meetings of Friends within the monthly-meeting of Settle.

William Ellis travelled in the work of the ministry into various parts of England;
but though he had the unity of his Friends in these apostolic journeys,
no record of them, at that early period of the Society,
appears on the minutes of the monthly-meeting of Settle, to which he belonged.
The following letter from John Real, a Friend of Falmouth, addressed to William Ellis,
evidently refers to a visit of the latter to Cornwall
as early as 1690.--John Real died at Penryn in 1697;
in the register of his burial he is described as "`an ancient Friend.`"--John Richardson,
who is mentioned in this letter, was from Yorkshire.
At the time of his being in Cornwall on the religious visit here alluded to,
he would be only about 25 years of age;
he laboured diligently in the Gospel in Great Britain, Ireland, and America,
and died at Hutton-in-the-Hole, in 1753, aged 87 years.
See his Journal, also the Tract, No. 42,
of the York Friends`' Tract Association.--Mary Frost was from North Shields;
she also must have been young at the time of this visit,
and must have attained to an advanced age, as she died in 1756.

[.embedded-content-document.letter]
--

[.letter-heading]
John Real to William Ellis.

[.signed-section-context-open]
Launceston, 1st of the 1st mo. 1691.

My dear and loving friend,
unto whom my love flows and abounds! in the blessed and unchangeable Truth of our God,
very dearly doth my love salute thee; and my desire is,
that as the blessed and holy appearance of the Truth
hath been made known unto us in our day and time,
so we may walk and live in it, to our mutual comfort and consolation.
Oh my dear and well-beloved friend!
I cannot forget the many heavenly opportunities wherein
we have been comforted and refreshed together;
and our God is loving and kind to us, in sending his children and servants to visit us,
in this remote part of the country.
And now, having this opportunity, and the company of dear John Richardson and Mary Frost,
whose labour of love and service are well accepted of in these parts,
I could do no less than give thee a few lines, whereby thou mayst know that I love thee,
and all the dear children of my Father, who are all begotten of the Seed Immortal,
and born of the Spirit of Truth; and that I should be glad to see a few lines from thee,
as opportunity happens.
Blessed be the Lord!
Friends in these parts are well, and the blessed Truth prospers;
though the enemy and adversary of mankind seeks, as ever he did, to hinder it;
yet the Lord`'s power is over all, and his seed is growing,
and the plant of renown is springing.
Glory and praise to the name of the Great God forevermore!
I have not time to enlarge to thee at present; but this take,
as the remembrance of my dear and unfeigned love, wherewith I bid thee Farewell.

[.signed-section-closing]
Give my dear love to thy wife, though unknown.

[.signed-section-signature]
John Real.

--

By the subjoined letter,
it appears that William and Alice Ellis had a son who was named Jonathan.
This seems to have been their only child.
Thomas Gwin, of Falmouth, the writer of this letter,
joined the Society of Friends when young,
and became a laborious and sound minister among them:
he was the author of several tracts, containing much excellent counsel;
one of the earliest of these was addressed "`To the
children of Friends and other young people.`"
He died in 1720, aged about 64 years.

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Gwin to William Ellis.

[.signed-section-context-open]
Falmouth, 2nd of 10th mo., 1692.

[.salutation]
Dear William Ellis,

Thy acceptable lines I received, and am glad that myself with many Friends more,
here away, have a place in thy remembrance, which will not, I hope, be blotted out,
though our abodes are at so great a distance; but that the Lord,
in whom our fellowship and communion have been, will still preserve the same,
fresh and lively, while he sees fit to continue us in these tabernacles of clay;
and that, as he has made us, as it were, monuments of his tender mercy,
so we may forever speak forth his praise.
According to the resolution of a good man of old, who in his prayer said,
From my youth Thou hast taught me, and now likewise when I am old and grey-headed,
O Lord! forsake me not, until I have showed thy strength to another generation,
and thy power to those who are yet to come; and as the Lord is thus near us,
we shall be very near and dear one unto another: so dear William,
I have communicated thine to pretty many Friends, who are glad with me,
of thy wife`'s well-being, and of the birth of thy son Jonathan: the Lord,
if it be his will, cause him, as he grows in years, to grow in grace,
and in his Divine favour.
As for my part, I have been exceedingly exercised, by the removing of my little daughter,
on whom I had placed too much affection; but it hath been the Lord`'s will since that,
to give me another, who I desire, may grow up in God`'s fear;
for I have a true unity with thee in thy concern on account of Friends`' children;
and a jealousy sometimes on my mind,
lest the ensuing generation receiving the profession of Truth in a traditional way,
and being unacquainted with the wonders of the Lord,
which he has wrought for his exercised people, in their travels through the wilderness,
may be ready to sit as those who are at ease in Zion,
and trust in the mountains of a formal profession.
The Lord, I beseech him,
turn away this careless and lukewarm spirit from among the offspring of his people;
and engage the young generation in zeal and fervency, in his service.
As to Friends here, though some are too careless,
yet there is a remnant whose delight is in the Lord, and to whom he delights to do good,
and to refresh with the visitations of his presence, whereby their strength is renewed,
season after season.
And the spirits of some are concerned,
and their mouths sometimes opened on God`'s account,
being made witnesses of the operation of his Divine Power,
by which they are stirred up to speak forth his praise.
I am, dear William, thy friend and brother in the fellowship and bond of Truth.

[.signed-section-signature]
Thomas Gwin.

--

The following expression of condolence shows that William and Alice
Ellis were soon called upon to give up their only child.
James Tatham, the writer, was a native of Wray, near Lancaster,
and was a brother of John Tathain, mentioned in page 9:
he had settled as a grocer in Whitechapel, London, where he died in 1703, aged 52 years.

[.embedded-content-document.letter]
--

[.letter-heading]
James Tatham to William Ellis

[.signed-section-context-open]
London, 15th of 5th mo. 1693.

[.salutation]
Dear Friend,

I received thine, whereby I understand that thou got well home, at which I was glad;
but I was sorry to hear of the loss of thy son; but consider his great happiness;
he has passed his sojourning here in a little time, and is entered, without doubt,
into his Father`'s bosom,
where there is peace and joy forevermore.--I shall not be tedious at this time,
hoping thou wilt be sensible by this, what is in my heart.
We must leave all to the Lord, and to his ordering hand of Providence.

[.signed-section-signature]
James Tatham.

--
