== Chapter III.

[.chapter-synopsis]
* Letters from William Edmundson
* to William Edmundson
* to John Wynn
* from William Edmundson
* to William Edmundson
* from William Ellis to his Servants
* to J. Tomlinson
* to some Friends in Ireland, with a notice of the building of the Meetinghouse at Airton
* Testimony respecting Roger Haydock

In the letters contained in this chapter,
a fervent zeal for the promotion of the Gospel is exhibited,
in connection with much excellent counsel;
and the opening of a concern to visit America is touched upon.
The care of William Ellis and some others over the
flock of Christ is also strikingly exhibited,
and in William Ellis`'s Testimony respecting Roger Haydock,
some interesting particulars of his own religious course are given.

William Edmundson, the writer of the following letter, was a native of Westmoreland,
but resided during the greater part of his life in Ireland:
he became convinced of the soundness of the Christian
principles held by the Society of Friends,
through the instrumentality of George Fox and James Nayler, in 1653.
His character as a faithful disciple and minister of Christ,
is set forth in a journal of his life, travels, sufferings,
etc. published after his decease, which took place in 1712.
He was about 68 years of age when he wrote the following letter,
and nearly 85 when he died.

[.embedded-content-document.letter]
--

[.letter-heading]
William Edmundson to William Ellis

[.signed-section-context-open]
Rossenallis, the 23rd of the 5th mo. 1695.

[.salutation]
Dear William Ellis,

I received thy letter two days ago, and am glad to hear of thy safe coming home,
and of thy well-being.
Finding things well in thy family is great encouragement
to be diligent and vigilant in the Lord`'s service,
in his vineyard and husbandry.
There is much work to do, and it is fair weather;
the Lord having commanded the winds and storms to cease, so that it is a calm time;
and the Lord`'s labourers that he hath called into his vineyard,
and gifted with his Holy Spirit, for the work of the ministry,
are to follow his work and business close, and finish their work in the daytime,
and to be rewarded with "`Well done,
good and faithful servant,`" and not to stand idle in the market place,
about the affairs of this world, and so neglect the Lord`'s work and service.
There is need of good workmen, both in doctrine and discipline;
for the old enemy is hard at work, sowing tares, briers and thorns,
to surfeit men`'s minds and understandings; and his old engine is this world,
and the things and kingdom of it, to twist and draw men from the Lord`'s business,
and cumber them in the affairs of this life, and load them as with thick clay,
so that they cannot follow the Lord and his work, truly and faithfully,
as they ought to do.
And here many sit down at ease, in the flesh and will, and in their own time and place;
and this is not right: and they lose a good and right understanding, as in a mist,
and lose their way, and are clouded and darkened.
So whilst the light shines, all are to mind the Lord`'s business;
and He is and will be with them to the end, who is our Overseer, Director,
and Counsellor, who is with his workmen, that are diligent in his garden,
vineyard and husbandry; that put their hand to the plough, and look not back,
but look to the Lord and the prosperity of his blessed work of reformation,
and love it and delight in it, more than in all visibles, that will come to an end.
And blessed be the Lord! he owns his work and workmen, that seek not their own,
but the honour of his great Name, and the comely order of his Gospel,
which keeps all in their ranks, from first to last, in the church and body of Christ,
to do their service, in their places, according to their ability, gift and calling.
And blessed be the Lord! a concern comes upon many,
for close order and discipline in the church;
and the Lord blesses their endeavours and care for his honour, and the good of all,
and gives them wisdom and understanding beyond expectation;
and his heavenly power makes way through all opposition, to their great encouragement.
Everlasting praises to his name forever!
Friends in this country are generally well, and Truth`'s discipline goes on closely;
and the Lord renews the strength of such as are concerned to maintain it;
and I believe they will not be weary in their well doing.
My true love is to thee and thy wife, and all honest, true-hearted Friends.
Remember my kind love to them that may inquire after me.
I bless the Lord, I am in health, and yet able,
beyond the common course of nature in these latter ages,
considering my years and hard exercises attending me from my youth.
And I do not see but if the Lord hath yet more service for me to do,
he can give ability to perform his will in old age, as well as in younger years.
So in the fellowship of the Gospel of Christ, thy true friend and brother,

[.signed-section-signature]
William Edmundson

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to William Edmundson

[.signed-section-context-open]
Airton, the 26th of the 6th mo. 1695.

[.salutation]
Dear Friend, W. Edmundson.

By this thou mayst know that I got thine on the 23rd inst.
and am glad to hear of thy welfare.
I have been much better in my mind since,
and I bless the Lord in my heart for his kindness that still opens upon his servants,
to give advice to his people,
whereby they may be stirred up to do their service in their day:
and I am the more glad because he is giving advice and counsel to such
as he hath really called out of the world and the entanglements of it,
to advise and counsel others, lest we should sit down and do our own business,
and seek our own gain, to fill our own treasuries with,
and let the Lord`'s garner be empty; and by thus doing, grow emptier in ourselves,
and so grow weaker in ministering to others.
And for want of the good part being deeply reached unto,
sometimes flatness hath too much prevailed.
My soul hath at times travailed under a great weight, because of these things,
though but a young man, and a mean man in mine own eyes; yet blessed be the Lord!
I see that he is stirring up the spirits of some of his people to the end,
that Friends may yet go forward, as to the enjoyment of the sweetness of the hidden life,
and in the exalting of the peaceable government of Christ Jesus; though there are some,
I believe, who think there is enough of that.
I had a letter last week from Theodore Eccleston, a Friend in London,
with desires to hear of my journey in your country, to which I have given answer,
and concluded with a few lines as under-written:--"`My
soul rejoiceth to see that the day hastens,
that Babel with her gain, by which the great men of the earth have been made rich,
is now coming into remembrance before God; for he will stop her gain;
and now is the Lord about to try who they are that will cry,
alas! alas! and who they are that will rejoice over her,
because the hour of her judgment is coming on.
As upon the great men of the earth, so on poor tradesmen, who work,
some in wool and some in silk, and some in fine linen; now it is coming on,
to try all who will offer up freely, and who they are that will say,
If I lose my gain I cannot be supplied; so then I cannot live:
and I believe not only on the above-named, but also on such as work in wood and stone,
and iron and brass, and silver and gold, with those that make gain on the souls of men.
My spirit rejoiceth in God Almighty, to see that his Arm is awakened,
and hath put on strength.
The Lord stir up the spirits of his people, as he did of old,
that distinction may be truly made between dross and fine gold.`"

Now as touching my inquiry of the West ladies travel,
because thou art desirous to know my meaning:
that very matter hath sometimes glimmered in my mind, now going on three years,
which was before my son died; but lest I should lay hold on an uncertain motion,
I have been of that mind, to keep my mind from tampering with it,
lest I should be muddled in so weighty a matter, and miss my right way,
and lose that good reward that my soul earnestly labours for.
Now in thus doing, sometimes I have found little concern in my mind about it,
and at other times something hath seemed to draw my mind towards
that country with a flowing of kindness to the inhabitants thereof,
in like manner as my mind hath been, when it hath been to visit Friends in other places;
and if I must confess to the truth, as it is in secret, I dare not say,
but it is as full of kindness and well-wishings as ever to that country.
Now I know that as I have not answered my place to the full, as I ought to have done,
the hand of the Lord hath been strong and terrible upon me,
though I have kept it from all living but my wife;
so that under the weight of his sharp chastising hand,
I have cried earnestly to him that if he would bring me up in my place,
to stand in his delightful presence, I would be willing to run his errand,
by sea or land; and that which he hath given me should, in like manner,
be at his disposing; and thus he hath wrought with his gracious hand,
to the snapping that cord in pieces, which drew my mind to the world.
I know not that I ever opened my mind so much to any in my life.
Now the journey is weighty, and requires certain evidence,
so that when the matter seems to draw me forward,
something in me desires that I might stay the time, till a fit companion offers,
that may be to my comfort: and if it be my lot,
I hope the Lord in time will find out one,
or else will give me both ability and boldness in the great and weighty concern.
Now if a fit companion be made ready,
I am so free from the world that it need not hinder me, neither doth my wife at all.
I have said little or nought to any of the elders in our country, but to John Wynn,
whom I take to be an honest, weighty Friend.
I desire thee to send me a few lines with what speed thou conveniently canst,
with thy judgment or sense in this matter, for the better informing of my understanding;
for it is my pleasure to do that which is acceptable to the Almighty.

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to John Wynn

[.signed-section-context-open]
Airton, the 10th of 7th mo. 1695.

[.salutation]
Dear Friend,

By this know that I would fain see thee, for thou hast been and art often in my mind;
for my love hath been much to thee since the first of my convincement,
because thou wast an instrument in God`'s hand, for my help in that day;
and the subject that opened upon thy mind comes often into my remembrance; it was,
That all were to prize their time, for it is as swift as a weaver`'s shuttle.
And although this was many years ago, yet it lives upon my mind as much as ever;
and not only the memory of it, but it is in my mind to answer to it:
for I plainly see that it is as swift as a weaver`'s shuttle,
and there must be devout faithfulness, where time is truly prized and answered.
Therefore considering the great loss on the account of neglecting it,
and the great and joyful reward that is to be received in truly prizing time,
makes my soul travail to answer my place in time; and I oft say,
if I had it to spend over again, I could spend it to better advantage:
however this I know, that the Lord is a God of great kindness and tender mercy,
and delights to see judgment work out into victory; and that the hearts of his people,
whom he hath blessed, should be freely willing to venture all for his Name, even soul,
body and substance.
Dear John, my heart is set to serve the Lord, and with all my might to exalt his Truth;
for he hath greatly wrought for my help every way;
both in opening upon my mind the sweetness of his Truth,
and in setting me at liberty in outward things,
and in keeping my mind over the spirit of the world,
so that in all the good that is come upon me every way,
I do not give the honour to that which some call Good luck, or Good fortune;
but only to that great Name that is over every name, and over all powers.

[.signed-section-signature]
William Ellis.

--

Neither Robert Wardell nor Robert Barrow, who are mentioned in the following letter,
lived to return to England from their transatlantic visit.
Robert Warden, who was from Sunderland, in Durham, had travelled much in Europe,
in the work of the ministry, before visiting America: he died in Jamaica in 1696,
aged 60. After his decease, Robert Barrow, who was from Westmoreland,
sailed for Pennsylvania: he was shipwrecked in the Gulf of Florida,
and suffered great hardships among the Indians, by which his health was greatly impaired.
He died in Philadelphia, soon after arriving there in 1697, at an advanced age.

[.embedded-content-document.letter]
--

[.letter-heading]
William Edmundson to William Ellis

[.signed-section-context-open]
Rossenallis, the 18th of the 8th mo. 1695.

[.salutation]
Dear William Ellis,

This day I received thine from Airton, dated the 26th of the 6th mo.
last.
And as to that of the West Indies:
it is good to mind the Lord`'s motions and his openings, in the light and love of Christ,
and to be given up in his light to follow where he shall lead in his work and service;
and in his light, his will and mind are cleared up in his own time,
to his servants`' understanding, that are devoted to do his will in his time and season,
and divorced from this world`'s care and cumber, which is as thick clay,
and loads the minds of those that are in its spirit,
so that they cannot run in the ways of God`'s commands.

And, dear William,
I know that there is great need of faithful and skilful labourers in the Lord`'s vineyard,
in those parts of the world,
and especially relating to church government and close order
in the Gospel of our Lord and Saviour Jesus Christ;
and the service of it is often with me, and how it may be,
I shall see in the Lord`'s will and time, who gives ability to perform what he requires.
I received a letter from Robert Wardell and Robert Barrow, from Philadelphia;
they are both well, and the Lord blesses their service.
I have also letters from Barbados.
I was lately at Dublin with several country Friends;
it being the time of the Parliament sitting;
and Friends`' attending there is often of great service for the ease of Friends,
especially about oaths, in several acts.
The Parliament is generally courteous and loving to us,
and ready to do us good and to serve us in any respect;
they seem to regard us in every act they pass, in which we may be any way concerned,
and nothing can move in the house against us, but we presently have notice of it.
The Lord is working mightily in the hearts of the Government, for his Truth and people:
his Name is to be reverenced and magnified forever!
The Lord, through his comeliness, hath beautified his people,
and made them amiable in the minds of men;
and the Lord is honouring such as seek his honour and the public good,
laying aside all particular and self-interest, and endeavouring,
according to ability and gift, to prefer the kingdom and government of Christ Jesus.
And a godly concern comes upon many honest-hearted Friends, for the close Gospel order;
and the Lord causes it to prosper, to their great encouragement and satisfaction,
though there want not those that would live at ease and liberty in their wills;
but Truth prevails, and the testimony and holy discipline of Christ,
in the authority of his Eternal Power, are over all, which brings all under,
and crowns the labour of his faithful servants.
Our Province Meeting is a week hence,
and our Half Year`'s Meeting at Dublin is soon after.
I hope, if the Lord will, to be there.
Thou mayst write at large to me.
So with my dear love to thee, thy wife, and all true-hearted Friends.

[.signed-section-signature]
William Edmundson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to William Edmundson

[.signed-section-context-open]
Airton, the 14th of the 11th mo. 1695.

[.salutation]
Dear William Edmundson,

By this know that I received thine from the Half Year`'s Meeting,
which was very acceptable to me and my wife;
but I would gladly have seen it before it came to hand,
and am well pleased with thy advice about that great and weighty concern;
and I do intend, by the Lord`'s assistance, to do accordingly.
Now as in relation to Friends in that country, it hath often been in my mind,
the great good that might be done in those parts, by four or six honest, weighty,
concerned Friends, not only in doctrine but in discipline,
which I see more and more is too much a wanting in many places;
and if it be brought to pass, that the Lord should stir up Friends in that service,
and he makes way for me,
I should be glad to enjoy such company as might complete such a work,
for it is truly begun.
I bless the Lord with my whole heart; for his goodness is often upon me,
which makes me incline after his counsel, that I may answer my service to the full:
and though I have a trade, I find much strength to live over it, and loose from it,
so that if the above-named concern, or any other, fall to my lot,
I have little to hinder me.
The Lord hath wonderfully helped me in things outward, so that want of that,
need not hinder me.
And I do resolve, by the Lord`'s help, the aboundings thereof shall not hinder me,
neither.

One thing I would request of thee, that is this,
that if the intended journey grow up to be completed in thee,
then let me have the knowledge thereof; and as often as thou canst till then,
give me a few lines, as time affords.
I shall forbear to tell thee the benefit thy letters are to me.
I was at the last Lancaster Quarterly Meeting; to my great comfort,
I beheld their comely order in their affairs; and this I see, they go fast forward,
and grow too strong for all that would oppose their discipline:
there were many glad hearts to see that wisdom and counsel that opened in several,
in order to set up the government of Christ Jesus.
We have had many public-friends with us of late, John Gratton, for one,
who hath visited our country fully, and hath done great service amongst us,
and is still under an exercise for Ireland.
A concern begins to stir in several here away, for good order;
and if we had but Elders that were concerned to lead the way,
things would go fast on in our country; but keep what I say to thyself.
It is some benefit to our Monthly Meeting,
that we are so near Lancaster Quarterly Meeting.
George Myers hath been more likely to die than to live, and still is out of order:
some give account that he is low and tender-hearted, of which I am glad.
I hear something that Roger and Robert Haydock have
some mind to come to York Quarterly Meeting,
of which I am glad.
If the Lord permit health and liberty, I intend to see Friends eastward in Yorkshire,
in a little time.
Let me know if thou intend for the Yearly Meeting,
with anything else thou seest may be for our good.
Here are many Friends who have an endeared love for thee;
and who bless God that it was thy lot to come into our country.

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
From William Ellis to his servants.

[.signed-section-context-open]
London, the 16th of the 5th mo. 1697.

[.salutation]
To Simeon Wilkinson, with the rest of my servants,

These lines may let you know that a concern is much upon my mind,
and hath been since I left you,
that you may truly prize the day of God`'s kindness that is put into your hand;
and as it hath pleased God to give you, or the most of you, the knowledge of his Truth,
that you be sure you prize it; and I know it hath been by the Truth,
that my heart hath been enlarged to grant you all the liberty
that I could any way see hath been for your good,
and the growth of your love to the Truth,
and that you might be truly brought to a state of private retirement in yourselves,
so that you might be the more able to serve the Lord in your day.
I think it should be often in your thoughts,
the care that hath been upon my mind for keeping week-day meetings;
and when my heart hath been full of the goodness of God therein,
that I have laboured often to withhold expression, that I might see how you, with others,
might be exercised in mind.

And let me further tell you, it is now your day as to the great kindness of God,
and as to liberty to go to meetings to renew your strength:
therefore consider it as it is,
and keep your minds out of thoughts that are foolish and vain:
and do not think the privileges given are so indifferent
that they are not to be highly prized;
for I do say, that if it be not thus with you, but you walk in ease of mind,
and liberty in thoughts,
and take care for your preferment and self-pleasing in the things of the world,
and what and how you shall do to accomplish your interest in other matters,
more than for the interest in Him who hath been Master, Shield, and Strong Tower;
then the day of exercise will come upon you, and distress will take hold of you;
and though you may accomplish your interest in other matters,
and in things which you desire, it will bring with it divine displeasure,
with grief and trouble of body and mind:
and though you should keep under the name of Truth,
yet the soul will be under death`'s power,
and the mind overcharged with the cares of this life;
and then will your master`'s counsel come to your remembrance.
Pray consider the reason why there are so many that
fall asleep when met together to worship God,
and you will find they have split upon this rock: pray consider it in time;
I am sure that if you be diligent in serving the Lord,
it will be your pleasure and crown in old age.
If some of those whom I had before you, had done thus,
I am certain things had been better with them than they are at this day.

[.signed-section-closing]
This is written in kind love, and I remain, yours,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to John Tomlinson.

[.signed-section-context-open]
London, the 24th of the 5th mo. 1697.

[.salutation]
Loving Friend,

It hath several times been in my mind to write unto thee since I came unto this town,
of things that bear with some weight upon my spirit,
concerning Friends of our own meeting; for although I am far from you,
yet a concern is upon me for your prosperity and establishment in the blessed Truth.
And as thou art one whom we thought most fit to be
joined with the other two Friends as overseers,
therefore I send thee, in true love, these following lines.

Now, whereas it hath been God`'s great kindness,
to raise up a people to serve him in sincerity and truth;
it is also manifest to all such as retain a true sense of him,
that it hath been his continued care towards them for their further establishment,
to open many good and wholesome rules and orders amongst them,
to the end that they might come more and more to be settled in the root of the matter;
therefore the thing that is much upon me is, that you,
into whose hands these people are committed, to have that oversight of them,
may truly see those things put in practice, which are opened in you,
and which are read at your Preparative Meetings;
so that things which are wrong may be righted,
and things that are weak may be strengthened.
My desire is, that there be no indifferent minds,
nor a putting off things one to another, nor a saying, It is not my business, or so;
for by so doing, many hurtful things have crept in,
which have brought in coldness of love to Truth, and to the real service of it,
so that death hath taken hold of many;
so I am truly fearful that salvation will be wanting to them at last,
which fills my heart with great sadness many times;
therefore discharge yourselves in the sight of God,
of those things that are committed to your charge.
That saying of the Lord, by the mouth of his true prophet, is sometimes in my mind,
"`That when the sheep went astray, the Lord set overseers over them,
and if they did not discharge their duty to them,
he would require the flock at their hands.`"

So I desire thee, with the concerned Friends,
to watch to keep all disorders from amongst you;
and labour to see Truth come up in its ancient purity and comeliness.
Thou in thyself knowest it hath been my concern for many years, and while I am with you,
I shall still labour to the utmost of my strength, and not in speaking only;
there are enough of those who speak, except they spoke from a deep sense of life,
and in a true fellowship with it in themselves.
The Lord`'s work grows great upon me, so that it is like to put me out of all business,
and my mind is made to bend to it; so that the time draws near,
that I must leave wife and friends, and bid you all farewell.
So with kind love to thee and thy brethren, and friends that inquire of me,
I shall remain, with dear love to my wife, thy true friend,

[.signed-section-signature]
William Ellis.

--

The following letter is without an address,
but it seems to have been written to Samuel Randal and Joseph Pike,
in the course of a short interval in which William Ellis was at home,
previous to sailing for America.
The meetinghouse noticed in it is a stone building,
capable of holding about a hundred and fifty persons; it was built by
William Ellis at his own expense; and he subsequently conveyed it to Friends.
Some of the work about this meetinghouse seems to have been completed at a later period.
There are on a stone above the door the initials W. A. E. 1700.
Previous to the erection of the meetinghouse at Airton,
William Ellis seems to have attended a meeting held in a neighbouring village,
named Rilston.
This meeting was originally called Scalehouse Meeting: it was established about 1653,
chiefly by Richard Scostrop, who, after persecuting Friends sorely,
became convinced of the soundness of their principles, joined the society,
and preached the faith which once he destroyed,
travelling for this object into various parts of Europe.
Rilston and Airton long constituted one Preparative Meeting.
In 1791 the meetings were held alternately at Rilston and Airton.
In 1792, the meetings at Rilston ceased, and Rilston meetinghouse was sold in 1813.
The meetinghouse at Airton is still occupied by Friends.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Samuel Randal and Joseph Pike

[.signed-section-context-open]
Airton, the 24th of the 6th mo. 1697.

[.salutation]
Dear Friends,

After my dear love to you, by this know that my wife had yours before I got from London;
and I have read it over, and am greatly comforted to hear of your welfare,
and to feel your love still to increase to the Truth,
and to know your labour for the prosperity of it.
The tenderness of your love to me for the Truth`'s sake,
hath wonderfully overcome my heart; and I know not how to answer it to the full;
but am fully satisfied the Lord will give you a reward here and hereafter,
if you keep firm to the end.

My heart is full of tenderness at this time, in the remembrance of you,
and your constant zeal and love to the Truth.
The Lord prosper his work amongst you!
And dear Friends, know further, that I am got home, to set my affairs to rights,
with the intent for the journey you know of, having offered my whole in secret,
and my life for a sacrifice; and all the thought I take is,
that it be but pure enough to offer to the gracious God that hath had mercy upon me,
and thus far hath saved and delivered me out of all my straits.
I have had it long in my mind, therefore have I laboured with my soul,
body and substance, that God hath given me,
to bring Truth up into dominion over all the country where I live,
and to bring things to rights in our particular and monthly meetings,
where I have met with opposition at times: yet I bless the Lord,
and rejoice in his strength, he hath made bare his arm to help,
and has raised many that have been, my helpers,
so that divers good things are set on foot amongst us;
on that account I am therefore wonderfully easy,
and shall commit the management to the honest men,
with the weight of my charge that God hath put upon me,
to see that things be kept in order, and that the Life may rule over the congregation.
For though Truth hath been preached, and many convinced, yet for want of a fervent mind,
and faithfulness, it might have been said,
as the prophet spoke concerning the people of old, Jacob is low, by whom shall he arise;
so that here hath been great need of faithful labourers,
that the sweetness and marrow of the Gospel may be brought up to people`'s understandings.
I gave you a hint before, how I had got up a meetinghouse;
but now shall give a small account of the good service
we have had since we got it in order.

Many public-friends come to us, and great numbers of people at times;
and the Lord`'s goodness opens wonderfully,
so that people declare their satisfaction one to another; so that I am in great hopes,
great part of our valley will be convinced; and if they will not be converted,
the fault will be their own.
Thus the Lord hath graciously answered the secret travail of my heart.
Dear William Edmundson will give you account, if time permit;
he hath been at my house two nights, and hath had a great service in our country.
This is with my dear love to you and your wives, and friends as you see meet,
as though I named them.

[.signed-section-closing]
So concludes, your real friend,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.testimony]
--

[.blurb]
=== William Ellis`'s Testimony concerning our dear Friend, Roger Haydock.

I have much in my heart concerning our dear Friend, Roger Haydock,
though I cannot express to the full what I know of him; but however,
I shall say the less, not questioning,
but that there are testimonies in the hearts of many Friends to his worth and faithfulness,
and service in the blessed and holy Truth;
wherein we have believed and felt the blessed effects of our faith,
to the great comfort and consolation of our souls.

It was about twenty-one years, the last Third Month,
since I was convinced of the blessed Truth.
And though I have since that day, had many instructors in Christ,
yet I have not many fathers;
for in Christ Jesus was I begotten by him through
the Gospel and the operation of the Holy Spirit,
which did effectually open a door of entrance in my heart,
as it opened a door of utterance unto him.
It was at a meeting, at Bradley, near Skipton in Yorkshire;
where he declared the day of God, which was broken forth in this age,
in great splendour to enlighten mankind.
He spoke many things which reached the states of many in that day;
alluding to the state of Israel of old, who passed through the sea,
and saw the wondrous works which the Lord wrought for their deliverance;
yet some forgot him, and made themselves idols of their jewels and earrings; saying,
These be thy gods, O Israel, who brought thee out of the land of Egypt,
and then sat down to eat and drink, and rose up to play.
With these and many more precious words, he did sound forth the glorious Gospel.
I was abundantly satisfied that day, with what I felt and heard;
so I took heed unto the Word in my heart, unto which I was directed by him;
and it grew and increased; and my faith increased, and I became,
according to my small measure, obedient thereunto;
and my soul was in love with the Truth, and the followers thereof,
especially with him who had been the instrument of publishing the same to me:
and I could say in truth, Blessed is he that cometh in the name of the Lord.
I saw his zeal, and was sensible of the sincerity of his heart,
and of his endeavours in his lifetime, to promote, to his utmost, the great name of God.

And when, through Providence, I came to be more intimately acquainted with him,
I was confirmed in my sense of him, and his love to God, and zeal for the Truth,
and have in many private opportunities with him,
been abundantly satisfied in the sweet society and fellowship we have enjoyed together.
And I am fully persuaded that his root was in the Truth,
and that he was sensible that the Root bore him; and he grew therein,
and laboured much to bring people to be established upon the sure Rock, Christ Jesus,
the Root of Life, upon which the true church is built:
and I know his labour in that respect was great, and the Lord saw his faithfulness,
and poured out upon him the spirit of wisdom and understanding, and of a sound mind,
to promote good discipline and comely order in his church,
that she might be like the true church of old, which John spoke of,
under the similitude of "`a woman who was clothed with the sun,
and had the moon under her feet;`" which glory did far excel
the glory that attended Solomon in his best state,
for the sake of which, the Queen of the South came from far,
and was overcome with the sight thereof.

Thus did he labour and travel in his day;
spending himself that the church might be adorned with the comely attire,
and ornaments of the Holy Spirit, and that the name of the Lord Jesus, her head,
might spread to the ends of the earth.

Blessed be the great God of heaven and earth, that raised up him, and many more,
who could hold the sword and be expert in the war,
like the three-score valiant men of Israel,
who kept the bed of Solomon (Song. 3:7-8), or like the men of Benjamin,
who could sling to an hair`'s breadth and not miss.
(Judges 20:15-16)

The Lord raise up more such faithful labourers in his vineyard;
and give them wisdom and zeal, to train up those who shall believe in the Truth,
in sound discipline, as well as in word and doctrine,
that he may restore unto the church, Judges as at the first,
and Counsellors as at the beginning, that men may call them, The City of Righteousness,
the Faithful City.
(Isa. 1:26)

[.signed-section-signature]
William Ellis.

[.signed-section-context-close]
London, the 20th of the 6th mo. 1697.

--

[.offset]
Roger Haydock died on the 8th of 3rd month, 1696, aged 53.
