== Chapter VI.

[.chapter-synopsis]
* Letters from Alice Ellis to her husband
* Adam Squire to William Ellis
* William Ellis to Simeon Wilkinson
* to Alice Ellis
* Theodore Eccleston to William Ellis
* William Ellis to Adam Squire

The notice in the following letter of "`Quarterly Meetings of Public
Friends at Settle,`" seems to have referred to the commencement
of the meetings now known as the Meetings of Ministers and Elders,
which are held once a quarter within most of the
Monthly Meetings in the Society of Friends.

[.embedded-content-document.letter]
--

[.letter-heading]
Alice Ellis to Her Husband

[.signed-section-context-open]
Airton, the 24th of the 5th mo. 1698.

[.salutation]
Dear and Loving Husband,

I have received thine dated the 23rd of the 2nd month, which was gladness to my mind;
it was the first I had received since thou took shipping.
I am well in health, and very cheerful in my mind,
and we have been very quiet in our family since thou left us.
Dear love, thou hast often been in my remembrance to my great comfort;
and such has been the Father`'s love, that I can truly say, I have had no want of thee,
excepting in our own meeting;
and I daily feel the sheddings abroad of this love in my heart;
I feel my strength is often renewed,
and many times earnestly pray in the secret of my heart to the Lord,
that he may enable thee to perform thy service fully.
I desire thee to take no care for me for outward things, for I can truly say,
there has nothing seemed hard to me since thou left me.
I believe all things will be well every way,
if we be but faithful in heart and mind in what the Lord makes known to us.
I hope thou wilt take well my writing after this manner in both letters;
and though I signified the fear that was in my mind,
lest thou shouldst be drawn homewards over soon,
thou knowest it is not for want of love to thee; for I can truly say,
thy company has been always pleasant to me; but finding it was my duty,
I durst not but signify my mind after this manner; for I know,
the Lord who brought us together by a secret hand, that we might be a comfort,
and as meet helps one for another, and serve him in the sincerity of our hearts,
and to the utmost of our strength, will, if we do so, and continue faithful to the end,
yet more and more bless us, and enrich us with the riches of his love;
so that thereby we shall be more freely given up in heart and mind to serve him faithfully.
And as we abide here, the Lord will still more and more be glorified by us,
and we shall desire nothing more than that which will be a means
of spreading the Truth and propagating his great Name upon earth:
then I know that our love will increase to the Lord yet more and more,
and unfeigned love and hearty desires will spring
in our hearts to the Lord one for another,
that we still may be preserved by that secret hand which brought us together at first;
so in the secret of my heart do I earnestly pray
unto the Lord for the continuation of the same.

We have had two Quarterly Meetings of Public Friends, at Settle, since thou left us,
which were very precious meetings, and the set time they are kept,
is the week before the Quarterly Meeting at York; and so to continue.
I was at the Quarterly Meeting at York, and I can truly say,
it was the most comfortable meeting that ever I was at there.
Having a little eased my mind, I shall conclude, and so remain,

[.signed-section-closing]
Your true and loving wife,

[.signed-section-signature]
Alice Ellis.

--

Adam Squire, the writer of the following letter, was a Friend of Airton,
whose name first occurs on the minutes of Settle Monthly Meeting, in 1696.
The Gill estate, near Airton, which is now in the possession of Friends of Yorkshire,
belonged to some of the same family of Squire,
who lived at Needham Market at the time it was transferred to Friends in 1829.

[.embedded-content-document.letter]
--

[.letter-heading]
Adam Squire to William Ellis

[.signed-section-context-open]
Airton, the 24th of the 5th mo. 1698.

[.salutation]
True and Well-wishing Friend, William Ellis;

Wheresoever these may find thee, the glory of the Lord God of Israel overshadow thee,
and the blessings of his Son Christ Jesus abound in and upon thee!
Heartily do I desire that he may distill his small rain more and more,
and shower down his love in and through thee, so that he may make thee a fruitful bough,
spreading over all the walls of opposition;
and the Lord grant thy prosperity in the Truth every way,
that when the wicked archers are suffered to shoot their darts sore on every side,
thy bow may abide in its full strength; and I do not at all question,
but the Lord will arm thee with that spiritual armour,
which I know is able to resist all the fiery darts of the devil.
For this cause I greatly bless God on thy behalf,
that the Lord hath chosen thee as one of his faithful labourers,
to place his holy Name upon.

O my dear friend!
I tenderly desire thee in bowels of endeared love,
which I feel in the love of God to roll towards thee,
to be sure thou leave nothing short,
of that which the Lord has discovered to thee and given thee a knowledge of.
I believe thy reward will be great;
for this is thy day that the Lord hath handed forth to thee.
The Lord goes before thee and is become thy captain,
and if thou follow him in sincerity of heart and mind, and fight his battle valiantly,
then the Lord will make thee more than a conqueror, a pillar in his house,
which shall no more go forth.
Thus I have given thee a small hint of my respects,
withal heartily desiring of the Lord that he may say, Amen,
to my secret desires for thee.

Now I know I need not say much of my gladness to hear from thee,
for I believe thou knowest it, yet I desire thee, as opportunity offers,
to let me hear from thee; and as touching what thou mentionedst in thine to me,
I do intend, if I live, to answer thy mind in all respects; and as for thy poor wife,
who I know loves the Truth, she shall want no assistance that I can make her.
And further, my friend,
I must acknowledge the remembrance of thee comforts my heart and soul;
and though we be far separated outwardly,
yet in this pure love of God are we nearer than ever;
but at times I want thee exceeding sore,
to help to press forward those that would fain stay behind;
and to drive onwards the backsliders which will neither
go themselves nor are willing to let others go.
This thing is a great trouble to me, to see such things, amongst those called professors;
but I believe the day is coining that every one must be turned to their own,
and must reap the fruits thereof;
and happy will all those be who have laid up heavenly treasure,
whose fruits will be safe forevermore.
I heartily desire thee,
that thou wilt pray unto the Lord of the harvest
that he may raise up more faithful labourers,
who will stand substantial in the day of trial, and in the time of great exercise.

And my friend, whom I dearly love in the everlasting Truth,
I beg it of thee to pray unto the Lord in the secret of thy heart,
that I may be preserved out of the snares of death, which lead to the chambers of hell.
I see the danger they are in, whom Satan hath blinded.
O that thou would call to mind, and remember when thou wast beset, as it were,
with enemies, within and without! and as thou patiently waitedst upon the Lord,
how he in his due time, wrought thy deliverance every way;
so that now thou art become free to the commonwealth of Israel;
and then thou mayst remember me before the great Lord,
that I may be preserved out of the reach of the enemy in every respect.

My friend, I cannot word my desires in this respect,
but believe thou hast a feeling sense of my condition, and hast experienced the same,
so that I know no mortal that I can make my complaint to in comparison of thee;
and I believe that to thy private supplications, the Lord will say, Amen.
I cannot but earnestly desire thee to remember those who have thy exercises to go through;
and to pray the Lord that he may bring them through Jordan,
which I earnestly desire the Lord may grant so to be; and in expectation of the same,
I rest thy loving friend and brother in the unchangeable Truth,

[.signed-section-signature]
Adam Squire.

--

Simeon Wilkinson, to whom the following letter is addressed,
appears to have been an indentured servant to William Ellis.
The care of a Christian master is well set forth in the counsel contained in this letter.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Simeon Wilkinson

[.signed-section-context-open]
Maryland, the 25th of 5th mo. 1698.

[.salutation]
Simeon Wilkinson,

Loving friend, after true love to thee, know that the time of thy freedom being near,
I have been under a concern of my mind for thy welfare; and seeing, it may fall so,
that thou set up for thyself; therefore I advise thee, that thou settle thy mind quietly,
to feel the Truth to direct thee in thy undertakings;
and let not love of increase of outward things or profit,
take up thy affections too much; but be sure to keep openness to go to week-day meetings;
and in private, desire to feel God`'s goodness to fill thy heart,
that thy strength of mind may be renewed, rightly to rule what God may bless thee with,
and likewise to overcome what is incident to thee in nature,
and that thou love and honour thy parents, which I know will please God;
and that thou wilt help thy sisters in what is needful in any manner.
And wait to have thy eye opened,
to discern truly between those that serve God and those that serve him not;
and labour to improve thy gifts, spiritual and natural, to the most advantage,
and God`'s honour: and if these things be found in thee,
the Lord will make way for thy prosperity every way.
Thou hast seen my care of thee,
and that the Truth might grow in thee and amongst you all;
that by it you might be made men for God when I am gone.
Thus with true love to thee and you all,

[.signed-section-closing]
I rest thy true friend,

[.signed-section-signature]
William Ellis.

--

While William Ellis pointed out the benefit of attention
to the teaching of the Holy Spirit,
and the advantage of waiting on the Lord for this teaching,
he saw the necessity of watching against the snares of Satan,
when transformed as into an angel of light, beguiling those who being somewhat awakened,
but not truly humbled and brought to a spiritual discernment of their duty,
gave way in an excited state of mind to imaginations,
and in this professed to have visions, and to be moved by the Divine Spirit.
The enemy of all good has often sought by such means to bring into discredit a belief
in that teaching of the Spirit which is abundantly promised in the Scriptures,
to the disciples of Christ;
and the early Friends whilst directing to the true teaching of the Spirit,
guarded this point by declaring,
that whatsoever was professed to be the teaching of the Spirit,
and was contrary to Holy Scripture, must be reckoned a delusion of the devil.
Caution is extended in the following letter, in regard to persons under such delusions.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
East Shore, Maryland, 26th of 5th mo. 1698.

[.salutation]
Dear and Loving Wife,

After true love to thee, these may let thee know,
that through the tender mercy of God (who hath wonderfully
extended mercy unto us many years,
not because of our desert, but of his own good will),
I am as well in body and easy in my mind as I have been a long time;
and my heart pants to be filled with the Lord`'s goodness, that by it,
I may do that which is fallen for my lot in this wilderness country;
and my desire hath prevalence with him, which is secret gladness to my heart.
In about ten days or two week`'s time, I intend to be in Pennsylvania,
and to be thereabouts till towards the last of the Seventh Month,
and then to go towards New England, for it is dangerous travelling in the winter there;
and if I live, to come back to Pennsylvania.
I have seen Friends mostly two or three times over thus far;
and I intend to spend my time to the most profit I can; and if I go not for Barbados,
shall make my way for home; but cannot say much to that till I see my way clearer.

My dear, I often think of thee,
and it is no small comfort to me that I have thee to think of,
and the more because I have ever found thee true to me in my greatest trials;
and though I be far from thee, yet my love increases to thee,
and if it please God to bring us together again,
I believe it will be to the increase of our comfort and strength,
and I hope for the further advancement of the work of Truth,
which thou knowest hath been my hearty desire this many years.
And my desire is, that thou live nearer the Truth than ever,
and let the life of it fill thy heart,
that thereby thou mayst be enabled to discharge thyself
of what is committed to thy charge,
and labour to promote that which makes for peace;
but if any mutinies should arise to disturb and disquiet Friends,
labour to keep to the sense of God, and to what clearly opens to thee;
in that clear thyself, but let it not take too deep hold of thee,
nor fret thyself at evil doers,
for they will wax worse and worse till they be fully made manifest.
And let patience possess thy mind, and wait to grow weighty in thy retirements,
that thereby thou mayst grow in all virtues,
and in the knowledge of those things that appertain to the
exalting of the worthy name of the Lord Jesus Christ.

I know that true-hearted Friends will often inquire of me:
remember my dear love to them as one man.
My spirit is often with you in your week-day meetings;
and to think of God`'s goodness in times past is gladness to my heart.
Remember my love in general to all Friends as thou seest fit,
and be careful to keep out all who pretend to motions and visions,
such as are but of their own brain; and advise to keep to the sound Truth in all things,
and put Friends in mind to visit Scarhouse Meeting.
So with true love to thee,

[.signed-section-closing]
I remain thy real and loving husband,

[.signed-section-signature]
William Ellis.

--

George Keith who, as well as some others,
is noticed in the following letter and in some subsequent ones,
was once a minister among Friends; but he fell from his standing,
and afterwards joined the Episcopalians, among whom he became a priest,
but practised persecution and falsehood so as to render his profession
of religion contemptible.--See [.book-title]#Life of John Richardson#, Ed. 1843. p. 103--129.

Nicholas Wain was a Friend who emigrated from England at an early period.
A Friend of the same name, possibly a descendant of the former,
visited England from America as a minister in 1783, and again in 1795.

The following notice of Griffith Owen, who is several times mentioned in this volume,
is from Proud`'s [.book-title]#History of Pennsylvania#, Vol.
ii. p. 99. "`In the latter part of the year 1717, died Dr. Griffith Owen, of Philadelphia.
He came to Pennsylvania among the early settlers;
and was said to be of great and eminent service among them in divers capacities.
As a preacher among the Quakers he was highly esteemed, being an active, exemplary,
and very useful member of that religious Society.
In the civil department his merit and abilities raised him to several public stations,
wherein he acted with judgment and integrity, being long one of the Governor`'s council, etc.
But his practice as a physician, in which he was very knowing and eminent,
rendered him of still greater value and importance in the place where he lived.
With these qualities he is said to have preserved
the sincerity and meekness of a true Christian,
and died much beloved by a large acquaintance of people of different ranks and societies.`'

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
Philadelphia, the 8th of the 6th mo. 1698.

[.salutation]
Dear and Loving wife,

By this know that I got to this city two days since, where I was long looked for,
and as kindly received by Friends.
Yesterday I was at two meetings in this city, and the Lord`'s power came upon me,
so that I was made strong to sound forth the Truth,
and set it over what might appear to oppose it.
Many of George Keith`'s party were there, but I hear not a word of opposition yet.
Since I wrote my last to thee out of Maryland, I have been much out of health,
with much swelling and pain in my head, and a strong fever,
so that I somewhat thought it would have brought me down, but have travelled still.

Tomorrow I hope to go out to a Quarterly Meeting about twenty miles off;
and hope to return and stay sometime with Griffith Owen,
and take something to help my body.
Nicholas Waln and his wife met me here yesterday,
and as far as I see he has kept his integrity.
I got thy letter, of which I was not a little glad,
and I am glad thou art so easy in thyself:
my care is great in secret for thy safety every way; and though I be far from thee,
yet I know my love increaseth to thee, and hope our love will be so to the end.
Now since I left thee I have gone through many straits and much exercise of body,
so that sometimes I could hardly stand in a meeting without a staff,
and what I have yet to go through I know not;
but sometimes I am so that I question my return to thee again,
and when that is in my mind,
my care is more and more increased for thy safety and preservation; but what shall I say,
the Lord is able, and I believe willing to keep us, if we keep to him.
And further, take care to thyself that no false spirit betray thee,
nor lay hands on any man too suddenly, neither believe men for fair sayings only.
I have seen sometimes that all is not gold that appears so to be,
and as thou keepest here, thou wilt find what spirit people are of,
both at home and abroad:
take diligent care to improve what I have said to thee in this thing.

Here are many tender-hearted Friends who are preserved lowly in mind, and loving,
and who keep much out of superfluity in apparel.
Walter Fawcitt is with me here and is well; Richard Wilkinson knows him, I suppose.
If I live I intend to see the north parts, and hope to see those islands;
and at my return back,
I hope I shall be of more ability of body and see more as to my return to England.
Aaron is not come here yet, being in a fever and an ague every other day.
I sent two Friends to see him, and stayed till they came back: he sent me a letter,
wherein he hath expressed my sincerity to him.
If he come not up here after I go on,
I somewhat question whether I shall have any more of his company in travel,
but must labour to be content.
I would have thee draw my family into as little a compass as thou canst,
that if we live we may serve the Truth more than ever, if we be able.

My dear love to Friends in general, as thou seest meet.
I have thought some Friend might have been so kind as to
have given me an account of the affairs of our meeting,
and how things are in the monthly-meeting; it might well be thought,
that as I have left all to see Truth prosper in these lands,
it would therefore give me great gladness to hear of its prosperity at home.
With true love to thee,

[.signed-section-closing]
I remain thy truly loving husband,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Theodore Eccleston to William Ellis

[.signed-section-context-open]
Wandsworth, near London, 12th of 6th mo. 1698.

[.salutation]
Dear and Loving Friend;

I have received several of thy letters from the seacoast, and from Maryland or Virginia,
one of which came to hand when I was on a journey in Holland and elsewhere,
with dear Paul Moon.
I travelled through many countries and kingdoms and states,
even in some of the dark corners of the earth,
where Satan hath his seat and sits highly exalted,
and where the beast`'s deadly wound is healed,
and the whore rides as a queen that should never see sorrow;
but the day is dawned in which her merchants shall howl and lament as they see her downfall.
The Lord hasten his work more and more for his own glory and the good of the souls of men!
We had very good service among the Friends,
some of whom had not been visited for a great while.
Meetings in some places are large, and generally tender;
the worst was amongst a sort of Baptists, that queried of us,
if we came to meet with them as Christians! or if we came
to make them Christians! and much to do we had;
but at last we got a meeting with them, and felt some tenderness,
though not so much as in some other places,
for we had five meetings in Baptists`' meeting places,
in towns where Friends had no meetings; and in one near Hamburgh,
there was great tenderness, with tears and love, so that an open door is now there,
I hope, for the next faithful labourers the Lord may send amongst them.
There was much need of visiting in some places, and I hope through the Lord,
our labour was not in vain; for his presence was in a glorious manner with us,
and his power tendered our hearts and theirs,
and many of the other people`'s. Oh! that his love might not be in vain to any,
but that all, through the descending of the heavenly showers,
might know the earth to be mollified, the good seed to take root and grow,
to the praise of the Lord`'s own Name.

Well, it is a good day, and the Lord`'s work is going on!
A great parliament man owns Truth openly,
and a testimony is stirring among some honest Friends.
John Tomkins is opened a little in the ministry, and William Townsend,
a red-haired man of Southwark.
The Lord bring more into the labour of his vineyard,
that his great harvest work may go on.
The great Master of our assemblies be with thee, and rivet the nail in a sure place,
that it be loosened no more, but that it answer the end, to the good of men,
to the glory of God, and to the comfort of thy exercised mind.
So desiring thy preservation every way, with that of thy dear fellow traveller,
with mine and my wife`'s dear love to you both,

[.signed-section-closing]
I rest thy truly loving friend and brother,

[.signed-section-signature]
Theodore Eccleston.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Adam Squire.

[.signed-section-context-open]
Philadelphia, the 8th of 6th mo. 1698.

[.salutation]
Kind Friend,

Thou mayst know that it is no small gladness to have a few lines from thee,
and much more, because in them I find thy love to increase to me and to the Truth,
and that unsoundness in the people becomes thy burden.
The Lord raise thy love more to him, and thy zeal to his Truth,
and to give thee strength to bear whatever may fall upon thee for his Name`'s sake;
and that thou mayst labour to do whatever is ordered for thee to do, with a willing mind;
God Almighty loves such.
I am glad thou hast found the good effect of my advice;
I do think thou wilt find the good effect of it more and more.
Thou knowest I have told thee things that were for thy good, as if thou hadst been my son.
Had all that I have wished the welfare of, seen it as thou hast done,
and taken it in the same way,
several had been nearer the kingdom of God than I believe they are at this day.
And still my counsel is to thee, to hold on in every good work,
and let everybody have the benefit of thy love to the Truth; and above all,
watch to thyself, that nobody may have aught justly to charge thee with;
and as to marriage, wait in God`'s counsel,
that thou mayst have thy right portion on that account.
If thou pass that post without harm, it will make thy days comfortable.
So with true love to thee,

[.signed-section-closing]
I rest thy real friend and eternal well-wisher,

[.signed-section-signature]
William Ellis.

--
