== Chapter VII.

Notes of a Meeting of Ministering Friends, at Burlington,
West Jersey--Letter to Alice Ellis--Epistle to Settle Monthly
Meeting--Letters from Theodore Eccleston to Alice Ellis--to
Friends appointed as Overseers--Alice Ellis to her husband.

The following Notes respecting a Meeting held at Burlington, in West Jersey,
and preserved among the memoranda of William Ellis, are of great interest,
and may be profitably read by many in the present day.
From what is stated in a subsequent letter,
this meeting appears to have preceded the general Yearly
Meeting for Pennsylvania and the adjacent parts of the country.

Samuel Jennings, at whose house this meeting was held,
was for some time Governor of the province of West Jersey:
he emigrated from Coleshill in Buckinghamshire, in 1680;
and is said to have been "`a suppressor of vice, and an encourager of virtue;
sharp toward evil doers, but tender and loving to them that did well;
giving good counsel and wholesome advice to friends and neighbours;
he was an able minister of the Gospel, and laboured much therein,
to the comfort and edification of many people.`"--See Proud`'s History of Pennsylvania,
Vol. I. page 157.

Thomas Janney, respecting whom a Testimony was read at tin`'s meeting,
emigrated from Cheshire, in 1683, and settled near the Lower Falls of the Delaware:
he is said to have been a very serviceable person in his adopted country.
After residing in America twelve years he revisited
his native country on a religious account;
and after travelling through some parts of it, was taken ill.
He died in Cheshire, amongst his relations, in 1696, aged 63 years,
having been a minister forty-two years.--See Piety Promoted,
Part II. and Proud`'s History of Pennsylvania, Vol. I. page 217.

Elizabeth Webb, noticed as being on a religious visit from England,
in company with Mary Rogers, from the same country, was from Gloucestershire;
but she afterwards removed to America,
and subsequently paid a religious visit to the land of her nativity.
An account of her religious experience, given in a letter to Anthony William Boehm,
was re-printed in 1848, in a volume of Autobiographical Notices, by Thomas Chalk.

Mary Rogers died whilst visiting the West India Islands,
on her passage from Nevis or Antigua to Jamaica.--See.
Letter, in this volume, from Samuel Carpenter, dated 1699.

Caleb Pusey, who produced at this meeting the essay of a controversial work,
was an emigrant from London, who had settled in Pennsylvania with his family in 1682;
he is spoken of in Proud`'s History of Pennsylvania, Vol. I. page 837,
as having preserved part of the materials from which that work was composed;
and as having been a man of good example, both in public and private life,
and esteemed as a worthy Elder among his friends the Quakers.
He was long one of the Provincial and Governor`'s Council;
and was the author of several controversial works,
one of which was in defence of William Penn.

Griffith Jones was, subsequently to the period of this meeting,
a member of the Assembly of Pennsylvania.

Notes at a Meeting of Ministering Friends, Held in Burlington,
at the House of Samuel Jennings, the 17th, 18th, 19th, 20th, 21st, 22nd,
and 23rd days of the 7th month, 1698.

The meeting was large and full,
and divers travelling Friends that were strangers were present, as William Ellis,
Aaron Atkinson, Mary Rogers, Elizabeth Webb, from England, and Elizabeth Gambel,
from Barbados, with divers others from neighbouring provinces;
and the Lord`'s eternal power was with us, in which divers living,
sound testimonies were borne; and after Friends were a little eased,
and our hearts united by the bond of Truth,
we proceeded to inspect the necessary affairs of the meeting.

A Testimony concerning our dear friend, Thomas Janney, given forth by Griffith Owen,
was read and approved.
The meeting adjourned until the morrow morning.

18th day.--Friends being met together,
and the Lord`'s power and presence eminently attending the meeting,
divers testimonies and cautions were delivered in the power and life of Truth,
which then overshadowed the meeting.

First,--Though some that had a public testimony, might think within themselves,
that the weight of the service of the Yearly Meeting might not be upon them,
believing it would rather become the concern of those
who had come from far to visit Friends here,
yet that they should beware of an unconcernedness in that respect,
but be weightily and carefully concerned to travail with them, spiritually,
who might be in the exercise,
that thereby they might be helped and strengthened
through their spiritual travail with them.

As also, that whereas, it was the way of the world to forget God,
yet the Lord had gathered us, his people, to himself, that we could not forget him;
for though we came poor and empty together,
yet the Lord in his wisdom and goodness and love, met us with a full hand,
to comfort and strengthen us, that we might not faint in our minds,
but be renewed in our strength; and as Friends kept in that,
the Lord would be praised and his Truth advanced.
As also that Friends might keep to the power of Truth, and not to be over forward,
but to mind it; and when things were well, not to offer anything that might do hurt,
or hinder the Lord in his spiritual work amongst his people;
and though this caution might seem then to be well received, as it had been formerly,
yet it was seldom but some things in these great meetings were offered that did hurt,
wound and grieve the honest-hearted: and several cautions were given,
that it should not be so at this meeting, or for the future.

As also, that Friends in the ministry should not run before their Guide,
but be weightily concerned, and not strive to utter words out of the power of Truth;
but as the power fell in them,
though there might be an openness and a desire to speak in that power,
yet rather to leave off, that the Lord might have his way;
for many things which might open at such times, if the power withdrew,
might be better spoken to by another, who might afterward be put forth to speak to it,
if the Lord saw good to order it.

Adjourned until the morrow morning.

19th day.--Friends being again met this morning,
some testimonies and cautions were given; viz.

As to the difference between the wisdom of God and of man,
and that though the wisdom of man was in the power of man,
yet the wisdom of God was to be waited for,
therefore Friends were cautioned to wait for it in silence,
and know a renewing of their strength therein,
and not to stir without it carried them along;
but rather to rest when it withdrew or did not put them forth.

As also, that as the Lord had formerly appointed Priests and Levites to serve him,
so the Lord had now appointed and chosen vessels
to bear public testimonies to his Name and Truth;
with caution,
that none should go before or stay behind the power of that which had called them,
lest their offerings should be those of strange fire.

And not only so, but to be good patterns and examples in their lives and conversation,
and to see that it should be so with their wives and children and servants,
that in all things the Lord through them might be praised.

William Ellis and Aaron Atkinson, for good order and example`'s sake were willing,
and of their own accord, offered their certificates,
that Friends in England had given them, of their unity with them,
and of Friends satisfaction in their coming to visit us here,
which were read and well accepted and approved.

A letter from Thomas Turner, and his certificate, read from Friends in England,
were well received; and it was agreed that a certificate be drawn on his account,
to go from this meeting.

The answer written by Caleb Pusey and John Wood, to Daniel Leeds`'s book,
called "`News of a Trumpet,`" agreed to be read next Fifth-day morning.

Adjourned until the morrow, at eight in the morning.

20th day.--Adjourned again until four in the afternoon.

Ann Dilworth proposed her intentions of going for England, to visit Friends there,
and she was advised of the weight of so great a concern; but if it rested still with her,
the meeting left her to her liberty.

Walter Fawcitt laid before this meeting his intention of going to England to visit Friends,
and he was left to his liberty.

An Epistle from the Yearly Meeting at London, was read,
and referred to be considered by the Yearly Meeting here.

A paper of condemnation was brought into this meeting, signed by Griffith Jones,
about his joining with George Keith in his separation;
but being informed it had not yet orderly passed the Monthly Meeting at Philadelphia,
to which he belonged,
he was therefore referred to give the said meeting satisfaction in the first place.

Adjourned until eight in the morning.

21st day.--Adjourned until evening.

Adjourned until eight in the morning.

22nd day.--Mary Rogers, in much brokenness, laid before Friends,
how that it had not been her own choice, to choose exercises, trials and difficulties,
but it had been the Lord`'s pleasure to draw her beyond her expectation,
as now he had laid it upon her to visit Barbados;
and though she had tried several ways to have evaded it, if the Lord had seen good,
yet every way, except that, seemed as darkness to her;
but she was willing to lay it before the meeting,
that she might have the concurrence of Friends in so weighty an undertaking;
which caused much tenderness in the meeting,
and divers testimonies were borne of the satisfaction
of Friends concerning her and her exercises;
and with several prayers for her preservation, in much love and brokenness,
the meeting gave her up to the will of the Lord.

Agreed that a certificate be drawn on her behalf,
and that the Monthly Meeting at Philadelphia be desired to take care that it be done.

It was proposed to this meeting,
that Richard Hoskins had it on his mind to visit the meetings in Maryland and there-away,
and in Virginia, and he was left to his liberty.

Thomas Turner`'s certificate signed.

23rd day.--Caleb Pusey`'s answer to Daniel Leeds`'s
"`News of a Trumpet sounding in the Wilderness,
etc.`" was read and agreed that it be published, with amendments,
and the additions noted to be made.

The meeting ended.

William Ellis to His Wife

Burlington, in West Jersey, 27th of 7th mo.
1698.

Dear and Loving Wife;

After my true love to thee, know that I am indifferent well,
and Aaron Atkinson is come hither,
and now is at the Yearly Meeting for Pennsylvania and thereabouts,
where many Friends from many parts are come up, and the meeting has begun well,
and I hope it will end with thanksgiving and praises to God Almighty.
After this meeting we intend to go towards New England, and into the Isles thereabouts,
and hope to come back into these parts; and if we find ourselves easy,
be sure we shall be glad to return to England again;
but I must not draw conclusions till I see my way clear.
Mean time my mind is much exercised for thy welfare,
and that nothing fall too hard on thee.
I sometimes fear ill folks will take an opportunity to foam out their malice at thee,
now that I am gone;
but I consider they will make themselves manifest to be in a great degree void of Christianity.
Above all, seek for patience to bear what may fall to thy lot,
and wisdom to behave thyself properly, both in word and deed;
and in due time the Lord will help thee through.

I received thy letter with what thou sent by Robert Haydook`'s ship, and was glad of it.
I have heard that Henry Coward is deceased, and George Myers also;
but it will not yet enter my mind that George is deceased.
Thou fallest short of giving me account of the affairs of our meeting,
and of the monthly-meeting, and whether you have got a meeting of public-friends or not.
Methinks somebody might have sent me a few lines;
but if the cares of this world and the love to it, drive me out of Friend`'s remembrance,
it is not so with me; for all my exercises, whether at sea or land,
have not driven them out of my mind, nor prevented my hearty prayers for their welfare.
Pray labour to bring the young people to a sense of the Truth,
and of the comeliness of it.

My dear love to all true-hearted Friends,
and especially to Richard Wilkinson and his wife and children; to Thomas Stockdale,
Thomas Atkinson, old Phineas Parkinson and Adam Squire;
I took his letter with more than ordinary gladness.
My love to brother Daniel and his wife, sister Margaret and brothers,
and all my well-minded neighbours;
and if anybody that is disaffected to the government of the Truth inquire of me,
let such know, that what I was in zeal and love to the Truth, I am the same still,
and hope to abide the same; for the love of God abides in my heart,
and my love increaseth to true men more and more.
My bowels often yearn for loose people that profess the Truth,
and such as have done wrong things, and have withstood Friends`' counsel,
because I see that if such die unreconciled to God and his people,
the hand of the Lord will be heavy upon them.
The Lord show mercy to all such, if their day be not over.
I have had good service in the Yearly Meeting.
Blessing and honour be to the holy and merciful name of the Lord forever!

This from thy real husband,

William Ellis.

An Epistle from William Ellis sent to Settle Monthly Meeting.

Boston in New England, 20th of 8th mo.
1698.

Dear Friends,

Though I be far separated from you in body, yet neither length of time,
nor distance of place, hath hitherto cast you out of my remembrance;
and under the sense of true love to you, my secret desires are for your welfare,
and that you all may be preserved in pure love and perfect unity one with another;
and that every one may fervently labour to promote the Truth,
and the good and wholesome order of it; and that wisdom may spring in your assembly,
to show mercy to the weak that are really penitent,
that they may be helped out of their weaknesses;
and that such as are taken in the snares of Satan may be helped;
and as for such as have been found in evil doing, and still remain in it,
and by no means will be restrained, though often advised in great love and tenderness,
let such know that the judgment of Truth is upon their evil doing,
and will be over them while they abide therein; and in the name of the Lord Jesus,
suppress pride and improper liberty in your young people.
Likewise that old people keep out of that grasping spirit
of the world which has blinded the eyes of too many;
and some have been choked by it.
Also in the name of the Lord Jesus Christ,
charge the rich men not to be high-minded nor to trust to uncertain riches,
but in the living God.

Also there are two sorts of people more, for whom my soul, in the sense thereof,
doth often mourn; the one is such as have wives but never a child,
yet are rich in this world; and the other such as never had wife nor child,
and have toiled to get riches in abundance;
and when neither of these two states are willing
to serve the Truth with all their souls and substance.
Now I desire in the love of God, that if any such there be,
that faithful Friends speak to them,
and advise them to discharge themselves of the stewardship they are entrusted with,
so that God may have his honour,
and they the comfort by serving the Truth in their Life time.
So whether such will hear or no, Friends will be found clear in the day of the Lord,
and such must bear their own trouble.
And with all your might promote hospitality; and when your tables are filled with plenty,
then remember the poor that are in want.
Judge the cause of the fatherless and plead for the widow,
and feel your bowels warm with tenderness towards the afflicted,
and I am certain the God of heaven will bless you in basket and in store,
and peace and love will increase amongst you;
and the young people will behold your good order, and bless the Lord on your behalf.
Thus with true love to you all, and to honest Friends in your particular meetings,

I remain your real friend,

William Ellis.

P+++.+++ S.--Know this, that I have visited Friends in Carolina, Virginia, Maryland,
Pennsylvania, East and West Jersey, Long Island, and Rhode Island, mostly,
and now am here at this time with an intent to see Friends, and go back to Pennsylvania.
Robert Heaton is well, Nicholas Wain is well, and hath many fine children.
Martin Wildman and children are well.
James Dilworth`'s wife, I suppose, is gone by this to Barbados, and if she live,
she intends to come for England.
My love to my wife.

William Ellis

Theodore Eccleston to Alice Ellis.

London, the 25th of the 8th mo.
1698.

Dear Friend;

I was often desired to write to thee by thy husband before he went hence, and since,
by letters that have come from him, but I have been much in journeys this year,
i have once been beyond sea, in Holland and divers other countries,
where in some places we travelled three and sometimes
four score miles between one meeting and another;
and we were at one town where no public-friend had been for nearly three years.
I think never since Roger Haydock was over.
In those meetings Friends generally speak by an interpreter.
I was absent from home about ten weeks,
and came back about the time thy letter came from thy husband, which we sent thee,
and received thy answer without a direction; but I sent it forward to Pennsylvania,
where I hope it would meet thy husband;
for I expect he might be thereabouts at the time when the
ship that carried thy letter might come there,
for I have received yesterday, another letter from him from thence,
dated in the 6th month, whereby I perceive he was gotten thither,
through the provinces of Virginia and Maryland.
He said nothing to the contrary, so I hope he was well.
Aaron was left behind, not well,
and I think had been much in sickness since he came there.
Thy husband works very hard in meetings, but I hope the Lord will please to preserve him,
and return him safe to us again when he has done his work in those places.

In the mean time it is some comfort to hear of him,
and to consider it is a time of liberty, and no wars this year in those countries;
but that which is more, is, to consider that it is the Lord`'s business that he is in,
to glorify his God and our God,
and to proclaim the day of great salvation which hath visited us,
that others also may enjoy the same love wherewith God hath loved us,
and may come to know and serve and worship God,
and be brought out of the ways of destruction,
wherein multitudes are going on ignorantly, supposing all is well with them.
It is good to be an`' instrument in the hand of the Lord, to save the souls of men,
and that is the work dear William is absent about;
therefore I hope it will not appear long or tedious,
especially considering that that God, whom he serves, is the God of all our mercies,
and I hope doth and will abundantly make up his absence
to thee with the comforts of his Holy Spirit,
to which Holy Spirit manifest within, I truly recommend thee,
desiring the blessings of God inwardly and outwardly may be increased to thee.
So dear friend, with mine and my wife`'s true love to thee,

I rest thy assured loving friend,

Theodore Eccleston.

P+++.+++ S. Thomas Story and Roger Gill are going to America.

A Letter from William Ellis to the Friends appointed as Overseers of the Church at Airton.

Boston, in New England, 9th of 9th mo.
1698.

Kind Friends;

After my kind and dear love to you,
wishing with my whole heart your welfare and your steadfast walking in the Truth,
and that the life of it may fill your hearts, know,
that though I be far separated in body, yet are you not forgotten by me,
but are often in my mind; and often is my mind exercised to this end,
that Truth may prosper amongst you;
and as it hath been thought good to commit to your trust those
things that are for the good of the Church and the honour of God,
my desire hath been and still is,
that you may be truly careful to see that every good work be maintained;
and that where such hath been found short in any, they may be advised in the love of God,
to repent and become anew; and if such be truly gained,
show all tenderness to them that is needful; but if any refuse amendment of life,
show your dislike in the Lord`'s name.

Advise Friends`' children to keep to the Truth,
and that they go not to other people for wives and husbands; but if any offer to do so,
deal with them in tenderness,
and wait that the true sense of their misery which
they are about to bring upon their own heads,
may fill your hearts, and in that deal with them;
and if such will not be gained but go on, when the Lord`'s hand comes to touch them,
and to bring trouble upon them,
your faithful warning may come into their minds and thereby they
may be made to confess to your care of them and love to them.
I have seen, since I left my country, the sad effects of such things,
and how through them our people are scattered, and make confusion,
and become unlike an assembly of saints.
I wish your love may increase to the poor, and fatherless, and widows;
and that in the sense of God`'s love,
you advise such as are rich and have neither wives nor children,
that they be much given to hospitality and to good works:
the day is coming in which such must know that it is better
to serve the Lord with their substance in their day,
then to leave it to their brethren or brethren`'s children,
or to pretend to leave it to serve when they are gone.

Let Friends meet often together, and with a free heart and a willing mind;
and see that Satan be withstood, who leads men to sleep and to idleness;
for it is he that doth this,
let him and them that take his part in it say what they will.
The Lord hath made my arm strong to war against him in that work;
and I hope it will be strengthened through the mighty God of Jacob,
to war against him to the end of my days;
and be sure that you fail not to set true judgment upon the head of that spirit,
I know it envies Truth`'s prosperity and the saving of people`'s souls.
And labour for that which makes for peace; so may your hope increase,
that God will bring you to his kingdom.
Labour also that humility may abound to that degree,
that you may be enabled to wash one another`'s feet;
and that not only the Ten Commandments to Israel be walked in,
but the new commandment given by Christ, that is, That you love one another.
And be sure that advice be given, not to watch over one another with an evil eye;
but where this is seen let sorrow abound;
and mark those that make divisions and sow discord.
The devil hath done more mischief by these things, in this part of the world,
than ever he could do by whipping, branding, imprisoning or hanging on the gallows tree.

And bear with me, if it be an offence to say to you, Finally my brethren,
be all of one mind; and so the God of all peace,
who forgets not the labour of his servants,
nor all the hardships and sorrows endured by night and by day, for this end only,
and no other, that the kingdom of his son Jesus Christ may be exalted: even He,
in due time, will give you to reap the fruit of your labours,
if you continue to the end and faint not.

If this come to your hand, and it be seen good, read it in your First-day meeting,
with my dear love, in the unity of the blessed Spirit of Christ,
who hath washed us from our sins in his own blood,
and will give us an inheritance amongst all them that are sanctified,
if we continue steadfast in faith and good works unto the end.
In this love I dearly salute you all, with all faithful Friends.
By this you may know that I have been over most of these countries,
and now hope to return to Pennsylvania, which is near four hundred miles off,
with many great rivers, sounds, and bays of water between.
These I have passed over before, with much difficulty at times.
If I live to come there, I hope the Lord will open my way; and if it be to return,
be sure I shall be glad.
Pray remember my poor wife, who parted with me freely;
she seems to me to be like the silly dove without its mate, who mourns for its companion;
speak comfortably to her,
and let no one do her wrong in any case that is in your power to set right.
My dear love to her and to Friends of your Monthly Meeting, or elsewhere,
who love the Lord Jesus Christ.
Aaron Atkinson`'s love is to you all.

Your real, constant and true friend,

William Ellis.

It is worthy of notice,
that on the same day on which William Ellis allowed his affection
for his wife to dictate the expressions of fear respecting her,
in the foregoing letter, she addressed the following to him,
showing how groundless were his fears.

Alice Ellis to Her Husband

Airton, the 9th of the 9th mo.
1698.

Dear and Loving Husband;

After the salutation of endeared love to thee, by this thou mayst know,
that I have sent thee two letters already;
and I hope thou wilt have received them before this comes to hand;
it would be great satisfaction to my mind to know that thou hadst once heard from me.
Likewise, my love, I have received six letters from thee since thou took shipping,
and they were all great gladness to my mind, and especially thy last,
dated the 26th of the 5th mo.
last, wherein thou signifiedst that thou wast easy both in body and mind;
and I earnestly pray unto the Lord for the continuation of the same,
and that he may still bear thy head over all,
and above all the troublesome seas of opposition,
which I am sensible at times thou meetest withal; but blessed be the Lord!
I am fully satisfied that he will make thee as a fenced city, and a brazen wall,
against all thy opposers, not to be prevailed against.
For this cause I heartily bless God on thy behalf,
that it hath pleased him to spare me to see this day; and I earnestly desire of the Lord,
that I may prize it.

So my dear love, seeing that it hath pleased God to bless us every way,
and to fill us with the new wine of his kingdom, many times to the admiration of my soul,
I can truly say we are engaged above many others to serve him faithfully.
And I earnestly desire thee in that which is beyond words,
to be very careful of thyself every way,
and still mind the inward drawings of the Father`'s love, that thou mayst,
in his acceptable time, fully complete his work which he was pleased to call thee to,
and clear thyself fully in his sight.
Now in the consideration of thy care and love which thou hast had towards me every way,
for my good, and for the loving and good advice I have received at thy hand,
both when near, and far off, in other islands, far remote from me,
the remembrance hereof many times tenders and melts my heart and spirit before the Lord,
so that I cannot word the nearness thou art to me continually.
I daily feel the shedding abroad of the love of God to fill my soul,
and to overcome my spirit, so that he makes up all wants, on all hands,
and on every account: my soul gives him the glory and the praise;
for such are his doings to them that serve him with a willing mind.
And many precious seasons we enjoy in the presence of God,
with the many faithful messengers whom he hath drawn in his love, to visit us;
and many of them, I believe, if not all, remember thee in their prayers to the Lord,
for thy preservation and safety every way;
and many there are whom God hath raised in his infinite love,
to sound forth the day of salvation; and their trumpets have given a certain sound;
and it is a gladdening to my heart to see Truth prosper;
and I believe it will increase from one end of the earth to the other.
The Lord increase it, is the desire of my soul.

So my dear love, let not the care thou hast for me lay over hard upon thee;
for I want for nothing which is good; the Lord makes up all and every want;
only remember me in that bond which cannot be broken.
And in this inexpressible love do I remain,

Thy true and loving wife,

Alice Ellis.
