== Chapter IX.

[.chapter-synopsis]
* Letters from William Ellis to John Chanler and Samuel Bound
* Notice of Phineas Pemberton
* Letters from Phineas Pemberton and William Gabbitus to William Ellis,
* from John Tomkins to Alice Ellis
* Notice of Gilbert Thompson
* Letters from Gilbert Thompson to Alice Ellis
* from William Southebe and Rowland Ellis to William Ellis
* Notice of William Fishbourn
* Letters from William Fishbourn and Griffith Owen to William Ellis
* Notice of Anthony Morris
* Letter from Anthony Morris to William Ellis
* Notice of Samuel Carpenter
* Letters from Samuel Carpenter and Richard Johns to William Ellis
* John Cowgill to the Offspring of Believing Parents.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to John Chanler.

[.signed-section-context-open]
Philadelphia, the 11th of 1st mo. 1698.

[.salutation]
My Kind Friend and Landlord;

After my true respects to thee and thy wife, by this know,
that I thought it no less than my duty to give thee a few lines,
to acknowledge thy civility and kindness to us, both as strangers,
and as people fearing God,
though thou thyself knowest we sought nothing of thee but love; and this, we had freely;
and let me freely tell thee, that I believe the love of God is much towards thee;
and if thou mind the Word that is ingrafted in thy heart,
thou wilt find that it will open thy understanding in things pertaining to thy salvation.
I believe it hath been already at work upon thy mind;
and let men say of it what they will, I do know that it is the leaven of the kingdom,
and the substance of the parable of the grain of mustard seed;
also of that of the woman that lost her piece of money,
and in searching and sweeping her own house, found it.
Likewise it is the pearl of great price,
for which the merchant was to sell or part with all, before he could obtain it.
And Christ says, He that is with you shall be in you; and it is also said,
What is to be known of God is manifest in men.
The Prophets also say, That in the last days,
the Lord would make a new Covenant with the house of Israel and Judah,
even would write his law in their hearts, and put his fear in their minds;
and that all should know the Lord.
And I pray God thou mayst take heed to his Word,
and it will guide thee in the way that is acceptable to God;
and this is that which I desire may come upon thee, and upon all mankind,
though some speak hardly of us, without cause or knowledge of us; but as for such,
I pray God to forgive them; they know not what they do.
My respects are to the little man in the white hat, his name I know not,
he sat with me at thy house; he came from Plymouth, in Old England.
My companion is come, and he told me of thy kindness to him.
I took it as done to myself.
So in true love to thee,

[.signed-section-closing]
I remain thy true friend,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Samuel Bound

[.signed-section-context-open]
Philadelphia, the 11th of the 1st mo. 1698.

[.salutation]
Dear Friend, Samuel Bound;

After true love to thee, by this know,
that I was somewhat uneasy that I parted so suddenly with thee and George Langlay;
however it is gladness to my mind to see thy zeal for Truth,
and thine and thy wife`'s dedication to the service of it; it is also my great comfort,
to see so many that are stirred up with love to the Truth;
and I desire that all Friends may labour to walk in it;
and that Friends may come out of all that which tends to improper liberty,
or to gratify a vain mind, whether in house or habit, loose talking or walking;
and as well in monthly-meetings for business, as in other meetings,
that Friends may sit under an awful sense of the presence of God in their minds;
and whatever comes before you to consider, keep in peace and love;
and labour to be all of one mind, and take care to prevent all such words or discourses,
as may in any way stir up heats or aggravate one another.
Let Christ be head and master and governor; and then will you feel, in yourselves,
the increase of that unity which always attended faithful brethren.
It was said to be like the oil that was poured on the head of Aaron,
and as the dew of Hermon`'s hill, or the rain upon the mountains of Zion.

Advise Friends to be true in retirement,
and that they may feel no contentment till Truth fill their hearts;
and that Friends may bring their children to meetings with them;
and that none be too much set upon business,
but rather spend some time to see one another in your particular meetings;
and put Friends in mind to keep up their week-day meetings through your island;
also that the younger people may not dis-esteem the
elder that have been true in their time.
I am somewhat of a mind that the Lord will enlarge Friends in your island,
if they be true to him;
and I further advise all to take care not to touch with that ranting spirit,
nor to show any pity to it; but in God`'s wisdom and power to stand over it;
I never saw any to prosper that ever lent it any assistance.
Fail not to write once a year to thy wife`'s mother in England.
Let honest George Law see my letter; my love is much to him;
he behaved himself to me like a man, a friend, and a faithful brother;
and the Lord`'s goodness filled his heart often.
The Lord thoroughly work him into that frame of mind
in which he may faithfully serve him in all things.
So with true love to thee, thy wife and friends,

[.signed-section-closing]
I remain thy true friend,

[.signed-section-signature]
William Ellis.

--

Phineas Pemberton,^
footnote:[Phineas Pemberton was the father of Israel Pemberton, and grandfather of James,
John, and Israel Pemberton who were all eminent and valuable men in their day,
useful in their respective stations,
and for a long period took an active and prominent part in the concerns of the Society,
as well as in some of the affairs more at large of
their native city (Philadelphia) and province.]
the writer of the following letter, emigrated from Lancashire,
where he had been a useful member of the Society of Friends.
In 1697 he was a member of Council and Speaker of the Assembly of Pennsylvania:
he died in 1702,
having been very serviceable in things temporal and spiritual
in his adopted country.--See [.book-title]#Life of Samuel Fothergill#,
page 160.

[.embedded-content-document.letter]
--

[.letter-heading]
Phineas Pemberton to William Ellis

[.signed-section-context-open]
The 18th of the 1st mo. 1695.

[.salutation]
Dear Friend, William Ellis;

Thy faithfulness to the Lord, the plainness of thy testimony,
the uprightness of thy conversation, and thy labour of love,
have been of great benefit to many, and therefore many do greatly love thee;
and I amongst the rest, who have reaped the benefit of thy labour,
am now drawn to give thee these few lines as a Farewell!
doubting whether I may see thee any more;
but I shall have that spiritual enjoyment of thee,
of which the saints in fellowship are made partakers,
and of which the things in this world cannot prevent us,
and wherein we are often comforted in those dear remembrances we have of one another,
until the time of that full fruition of enjoyment which is laid
up and prepared for us in the kingdom of rest and everlasting peace:
and truly the remembrance of thee at this time is very pleasant to me,
and the sense of the sweet and comfortable seasons we have had together,
dwells upon my spirit, and works me into a humble frame of mind,
to give the Lord the glory, who so tenderly takes care of his, everywhere.
This is not, ought not, and I believe will not be forgotten by the faithful,
but will more and more engage our hearts to love
and faithfully to follow and worship him,
who over all is worthy.
Thus being in haste, but in dear and tender love, I bid thee Farewell!

[.signed-section-closing]
Who am thine in sincerity and truth,

[.signed-section-signature]
Phineas Pemberton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Gabbitus to William Ellis

[.signed-section-context-open]
Philadelphia, the 25th of 1st mo. 1698.

[.salutation]
Dear William,

I thought I parted very hardly with thee, when I last saw thee;
indeed I did not think it would have come so very near me; but seeing that it must be so,
that we must now part with thee, the Lord`'s will be done!
I do not know what makes it harder to part with thee than with some others,
but I could gladly have wished for an opportunity to have seen thee.
I think I was too tender of some engagement then appointed,
which I now see I might have omitted, to have enjoyed more of thy company.
Blessed be the Lord that hath made thee so near and
dear to us! for we must needs confess it is his doing.
I humbly pray, we may answer his love in these things.
Anthony Morris and I had concluded to have seen thee once more,
either in Chester or Newcastle County;
but when we heard of thy concern for more haste than we expected,
it put a stop to our designs.
The Lord, if it be his blessed will,
preserve thy tender body safe from dangers both by sea and
land! that thy arrival in our native land may again be the
rejoicing and comfort of many brethren and sisters there,
but more especially of thy dearly beloved wife and family.
Friends with us are reasonably well; my wife desires to be remembered to thee.

Dear heart, our spirits go along with thee,
and love follows and melts and runs towards thee;
but it is for his sake who sets the fountain open: for his love`'s sake we love thee,
for thy sake we pray to him that his favour may be with thee forever;
it is He who gives of his Divine gifts, wisdom, courage, sincerity, and sound judgment,
crowned with meekness and charity, as ornaments to the sons of men.
The Lord prolong thy days, if it be his will,
that by the heavenly service and savour which he hath been pleased to put upon thee,
many may be turned unto him.
Now dear heart! not knowing whether ever we shall see thy face again,
which does not seem likely at present,
it was in my mind to give thee these few lines by Ann Dilworth;
and my spirit breathes that the Lord may be with thee and with all our spirits.
The Friends that are prisoners at Burlington, for the country privileges,
were very well in health; last night but one, my wife and I were with them;
they were also very cheerful;
but I cannot yet see when their troubles of that kind can come to an end;
to me it looks duskish at present.
Dear heart, remember us when we see thee not.
In the love of God, I bid thee truly, Farewell!

[.signed-section-closing]
Thy truly loving friend and well-wisher,

[.signed-section-signature]
William Gabbitus.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Tomkins to Alice Ellis.

[.signed-section-context-open]
London, the 10th of 12th mo. 1698.

[.salutation]
Dear Friend,

At the request of thy dear husband, I send this,
to let thee know that he was well at Boston, in New England, about the 9th of the 9th mo.
last, in good service for God and his blessed Truth.
The labours of thy dear husband with his companion Aaron Atkinson,
and the other two Friends, Thomas Turner and Thomas Chalkley, have been very acceptable;
and I have both received and seen many good accounts thereof,
from many Friends in those parts.
I suppose thou mayst have heard, that Thomas Turner hath been returned nearly a month.
Thy husband intended to go back from Boston to Pennsylvania; and afterwards,
if he find his spirit clear, he hopes to hasten homewards,
to be here by the next Yearly Meeting.
Here are enclosed two letters, one of a public tendency,
they both came to me as they are, unsealed.
I know not how to forward them to the Friends designed, but by sending them to thee;
and I do this the rather, as being of thy husband`'s own writing,
thou mayst understand by them the nature of his service.

Dear friend, thou seest that hitherto the Lord hath been with thy husband,
and made his service prosperous; and I doubt not, but He will be with him to the end.
This is encouragement to thee, as thou gavest him up freely to the Lord`'s service,
so to keep in that resignation until he hath fulfilled his Master`'s will;
it will make his absence still easy to thyself and to him also.
I feel that his love is for the general good of the church of Christ,
not only in those parts where he travels, but also for his brethren here,
and for the Church in those parts where thou dwellest,
that they may grow in grace and in the knowledge of our Lord and Saviour Jesus Christ.
Dear friend, thus according to his request, and my inclination also,
have I sent these few lines;
and with the salutation of mine and my wife`'s dear love to thee,

[.signed-section-closing]
I rest thy friend in the Truth,

[.signed-section-signature]
John Tomkins.

--

Gilbert Thompson, the writer of the following letter, resided at Penketh in Lancashire,
where he kept a boarding-school.
Professing the religious principles of the Society of Friends,
he was prosecuted by the intolerant party then in power, for keeping a school,
and for this alleged offence was imprisoned in Lancaster Castle!
He became a minister about the period at which this letter was written to Alice Ellis,
and was much esteemed both in this capacity and in that of a preceptor of youth:
he died in 1719, aged 61 years.--See notice of him in [.book-title]#Piety Promoted#, Part VIII.
and [.book-title]#Memoirs of Samuel Fothergill#, page 11.

[.embedded-content-document.letter]
--

[.letter-heading]
Gilbert Thompson to Alice Ellis

[.signed-section-context-open]
Sankey, the 28th of the 11th mo. 1698

[.salutation]
Dear Friend, Alice Ellis;

I often remember thee though I seldom write to thee, and were I near thee,
I could be glad of thy company, and to partake with thee in the fruits of thy faith,
and hear of the noble acts which the Lord hath enabled
thee to perform since thou lovedst him,
for his mercy`'s sake.
I have beheld with admiration, the industry, ability, willingness and resignedness,
which the Lord, upon divers occasions hath endued thee with,
and made thereby a meet companion and yokefellow to dear William Ellis,
whose heart and all his faculties are freely and truly devoted
to those particular services his Master hath engaged him in,
and in which, I doubt not, but as he hath been, he still is,
truly serviceable in his lot and place,
having an eye to the honour of Him that called him when he was little,
and to that recompense of reward laid up for the righteous.
I question not but thou meetest with exercises and divers difficulties, in his absence;
and yet, I as well believe, thou knowest how they all become sanctified, and canst,
in the faith, press forward and see beyond them all,
and feel a sweetness in standing in thy lot and testimony what way soever it stand.
Thy strength and experience I know go beyond mine, else would I say,
Maintain thy own lot, and stand in thy own rank and place of service,
and let others do so too; and then every one`'s task will be best done.
Let the peaceable wisdom that is from above, and settles our spirits, be dwelt in,
and therein, whatever is done more or less, will be to the glory of God,
and every one`'s particular comfort.
I am straitened now for time, otherwise I feel an openness that could enlarge;
but I can say, I read thee and some other dear Friends beyond words.
There is a more settled knowledge of such as are in the true faith,
and live in the Truth, than can or need be set forth by lines.
With a tender salutation of love I bid thee Farewell, and remain

[.signed-section-closing]
Thy well-wisher in my measure.

[.signed-section-signature]
Gilbert Thompson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Southebe to William Ellis

[.signed-section-context-open]
Philadelphia, the 26th of 1st mo. 1699.

[.salutation]
Dear Friend, William Ellis.

Not having the opportunity to be more in thy company when thou was here amongst us,
I could not well omit to signify my true love to thee,
and unity with that measure of the blessed,
holy power which I have had a sense of as attending thy ministry, and thy plain doctrine;
and of thy promoting true spiritual and inward worship to God.
Thou hast been instrumental to help forward our retired meeting here,
which I hope will be of good service.
This many of us, I believe, have long desired;
being truly sensible that the perfection of Divine worship and prayer to God,
as to our own particulars,
is performed mostly in true silence and inward retiredness before our great Creator;
and this indeed is much the end of outward testimony,
and is that into which my soul desires to be gathered more and more.
So with true and unfeigned love to thee,
desiring the Lord may prosper thee in his service,

[.signed-section-closing]
I remain thy friend,

[.signed-section-signature]
William Southebe.

--

Rowland Ellis, the writer of the following letter,
was a man of note among the Welsh settlers in Pennsylvania: he visited America in 1686,
for the purpose of selecting a place on which to locate his family.
In the voyage thither, which was very long,
many persons who sailed with him died for want of food.
He returned to England in the following year, leaving one of his sons in America;
and did not finally remove his family till 1697.
At this time he was about forty-five years of age; and it is said,
he lived long to do good,
his service both in the church of Christ and in the State being considerable.
He was a preacher among the Quakers, and an acceptable man in every station.
He died at his son-in-law, John Evans`'s, in North Wales, Pennsylvania,
in his eightieth year.--See Proud`'s [.book-title]#History of Pennsylvania#, Vol.
I+++.+++ Page 220.

[.embedded-content-document.letter]
--

[.letter-heading]
Rowland Ellis to William Ellis

[.signed-section-context-open]
The 28th of the 1st mo. 1699.

[.salutation]
My Esteemed Friend, William Ellis;

If these lines come to thy hands,
thou mayst understand what often hath been in my mind to tell thee,
That if ever it come before thee to visit Friends in Wales,
I desire this kindness of thee, partly for thy name`'s sake,
but rather upon Truth`'s account.
When at Dolgelly Meeting, in Merionethshire, in North Wales, to inquire for my daughter,
if she be then alive, and for her husband who is a priest.
If thou findest thyself free and anything inclined thereunto, knock at his door,
and see whether she is quite dead, or slumbering among the dead.
I do believe a living invitation may call home a strayed sheep,
though gone far into the wilderness, and there, it may be, fast entangled in briars,
and bound up in strong chains.
If there is any breath left in her, she may answer, though in a land of darkness,
and under the shadow of death.
The good Shepherd takes great pains to unloose the lost sheep from their bonds and entanglements,
and David-like, killing the lion and delivering the lamb out of his mouth,
to bring the same to their right mind, to know the Shepherd`'s tents.
Well, my friend!
I believe some have done things of this nature; and who can tell, if it come before thee,
but thou mayst through the power of God, be instrumental to open their eyes;
they both are very kind to Friends.
Our friend, Hugh Roberts, hath twice visited them, they being sick;
her husband took it very kindly.
So with my dear love unto thee,

[.signed-section-closing]
I remain thy friend,

[.signed-section-signature]
Rowland Ellis.

--

William Fishbourn, the writer of the following letter,
was a member of the Assembly of Pennsylvania, for Philadelphia county,
in 1716 and subsequent years.

[.embedded-content-document.letter]
--

[.letter-heading]
William Fishbourn to William Ellis

[.signed-section-context-open]
Philadelphia, the 2nd of 2nd mo. 1699.

[.salutation]
Dear and Well-esteemed Friend, William Ellis;

For so in my small measure of the Truth as it is in Jesus, I am bold to call thee;
not with flattery, nor with deceivable speeches, but with a true esteem,
as it is wrought by the power of God.
And as I hope I do humbly and reverently esteem the many mercies, blessings,
and favours which I receive from the hand of the Lord,
I also hope I ever shall measurably esteem his servants;
and I greatly desire I may be bowed down under a sense of the mercies of our God,
more and more every day.
My friend! with these lines I dearly salute thee with my unfeigned love,
wishing thy health, prosperity, and preservation every way;
and I earnestly desire thee to remember,
as thou hast access to the throne of God`'s grace, thy poor friend,
who travels in weakness, fear and hope, dread and humility, before the Lord;
and sometimes is ready to say, I fear, at one time or another,
I shall fall by the hand of the enemy that daily besets me.
Oh! desire for me, that I may not be tried beyond my strength;
for the wicked one sees the weak part, and he is often at work there;
but blessed be the God and father of all our mercies, his power,
in the very glorious appearance of it, is very strong,
as I am kept mollified and melted down before him.
Oh! my soul and spirit ever desire to dwell low before him;
I would to God I had a tent to dwell in, in the valley of humility,
and that I might always abide in it; then I should be safe.
Pray visit me with a few lines from thy hand, as thy spirit hath freedom;
and I desire thee to pray to the Lord, that I may ever be sensible of my condition,
and that nothing may be hid in me that is contrary to, or that oppresses the good seed.
Look upon these lines as from one that wants utterance to express my desires.
To the Lord I leave thee, and to the guidance of his good Spirit,

[.signed-section-closing]
And bid thee, Farewell!

[.signed-section-signature]
William Fishbourn.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Griffith Owen to William Ellis.

[.signed-section-context-open]
Philadelphia, the 3rd of 2nd mo. 1699.

[.salutation]
My Dear Friend,

I cannot forget thee, nor thy service or labour of love amongst us,
the remembrance of which draws my sincere love as a stream unto thee,
which I believe distance of place or length of time cannot wear out nor stop.
Mayst thou feel my brotherly love to thee beyond what my fear can express.
I earnestly desire the Lord to accompany thee with
his power and presence in all thy undertakings,
and to make thee more and more instrumental in his hands.
Dear friend! remember us and the little flock in this wilderness,
when thou art far from us, in thy nearest approaches to the Lord;
and I desire thee to mind my love to all Friends
in England that may inquire respecting me.

[.signed-section-closing]
I remain thy friend and brother,

[.signed-section-signature]
Griffith Owen.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Abraham Johns to William Ellis

[.signed-section-context-open]
Maryland, Clift, the 11th mo. 1699.

[.salutation]
Dear William Ellis,

Whom I dearly love in the Truth, my true love salutes thee,
desiring these may find thee well, as through mercy they leave us.
Dear friend,
the many blessed opportunities we have had together are livingly in my remembrance,
and blessed be God whose mercy and favours are great to this wilderness country,
he has not left us without sending his servants amongst
us to sound forth his blessed Truth,
and to stir up his seed, which he hath sown in the hearts of a remnant here,
which has many times been oppressed and kept down
through the wiles of the enemy of our souls;
but which hath been raised and stirred up through the testimonies of his
dear servants whom he hath been pleased to send amongst us;
praises and honour and thanksgiving be to his great and holy Name forever,
saith my soul!
Dear friend, forget me not in thy most secret supplication to Almighty God,
that my faith may be strengthened, and that I may be valiant for the Truth,
which he has been pleased to reveal unto me; for alas! dear William,
what are we without we receive strength and ability
from him?--nothing but poor dust and ashes,
not able of ourselves to speak a good word or think a good thought.
My hearty prayer to God for thee is, that he may be with thee,
and bless thy testimony and seal it down on the hearts of many sons and daughters.

Our dear friends, Roger Gill and Thomas Story, as also dear Aaron Atkinson,
were at our Yearly Meeting, where they had brave service for the Lord.
The same wrangling priest that Aaron met with,
came also to that meeting and openly opposed; but he was so handled by Thomas Story,
that I presume he repented coming there; it was of good service,
for Thomas laid him open to the people, abundance of his hearers being there,
who went away well satisfied.
My dear friend, I have this word of comfort to tell thee, Truth prospers,
and people begin to see what the priests are.
We are all quiet and still, and in true unity one with another.
Aaron is gone back again to the north, not being yet clear of those parts;
he expects it will be the 8th or 9th month before he leaves America.
Dear William, I desire to hear from thee as opportunity may present.
I shall not add, but mine and my wife`'s true love to thee and all Friends,
is the conclusion of,

[.signed-section-closing]
Thy loving and sincere friend,

[.signed-section-signature]
Abraham Johns.

--

Anthony Morris, the writer of the following letter, settled at Burlington,
in West Jersey, about 1680: he afterwards removed to Philadelphia:
he was a serviceable man as a preacher among the Quakers,
and in various other respects both of a public and private nature:
he died in 1721.--See Proud`'s [.book-title]#History of Pennsylvania#, Vol.
II. page 146.

[.embedded-content-document.letter]
--

[.letter-heading]
Anthony Morris to William Ellis

[.signed-section-context-open]
Philadelphia, the 12th of 4th mo. 1699.

[.salutation]
Dear William Ellis;

I have often been troubled in my mind when the thoughts
of thy going from us have come into my remembrance,
because that I had not the opportunity of taking my leave of thee in a solemn manner,
considering how nearly my spirit was united to thee, so that I can truly say,
I loved and do love thee in the Lord;
and through the operation of his Spirit thou wert made serviceable to me;
so dear William, excuse my neglect, for I came but a few minutes after thou wast gone.
Now I desire thee to pray for me, that I may be kept and preserved faithful to the Lord,
for according to my weak abilities I have often done
the same for thee since thy departure from us.
I send this by my very good friend, Joseph Kirkbride,
whom I hope the Lord will attend with his presence,
and keep him near to Himself and within his own protection;
and if it be his good pleasure return him safe to his family,
as I hope thou art gotten to thine.
With the salutation of mine and my wife`'s dear love to thee and thy dear wife, I rest,
and subscribe myself, in the Truth that changes not,

[.signed-section-closing]
Thy real friend,

[.signed-section-signature]
Anthony Morris.

--

Samuel Carpenter, the writer of the following letter,
was one of the early settlers in Pennsylvania:
he became one of the most considerable traders in that Province,
in which he also filled the office of Treasurer: his great abilities,
combined with a benevolent and active disposition,
rendered him a useful and valuable member of civil and religious society;
and he appears to have been highly esteemed among the Quakers,
to whom he belonged.--See Proud`'s [.book-title]#History of Pennsylvania#, Vol.
II. page 60.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Carpenter to William Ellis

[.signed-section-context-open]
Philadelphia, the 17th of the 4th mo. 1699.

[.salutation]
Dear William Ellis,

Although I have little to write,
I was not willing to let this opportunity slip without giving thee a few
lines to signify mine and my wife`'s dear love to thee and thine,
acknowledging thine to us, and thy tenderness towards us and ours;
hoping that the Lord will reward thee with peace in thy bosom,
for thy labour of love in this remote land,
with others of the Lord`'s faithful servants and messengers,
who have left all that was near and dear to them, in obedience to his requirings,
and in love to the souls of people,
that Truth and righteousness may increase and spread over the earth,
and the Lord`'s great name may be honoured.
Now it having pleased God to send his messengers to us, from time to time,
his living power and presence hath attended their ministry and services,
so that many can say, surely the Lord has been gracious to us, a lost people,
and accounted little of by our brethren, being scattered in this remote wilderness;
but blessed be the Lord our God,
who hath so graciously visited us by his good Spirit within us,
and by his faithful servants, who have been made instrumental in his hand,
and by his power, to reach our hearts, so that many have been comforted, confirmed,
and settled in the Truth.
What remains on our part, but that we walk humbly before the Lord all our days,
that his love and the labour of his servants may not be bestowed on us in vain?

Our dear friends Roger Gill and Thomas Story are
lately come by way of Virginia and Maryland,
and are hastening towards New England, in hope to return to our Yearly Meeting.
Dear Aaron is returned to Chester county; whether he go past us or not when he returns,
I yet know not.
This is intended to be sent by our dear friend Joseph Kirkbride,
who is gone down towards the ship; they are to be at Salem tomorrow,
and take their departure from Elsinborough.
My very dear love to Walter Fawcitt, and Friends that have laboured amongst us.
I should be glad of a few lines from thee, as opportunity and freedom offer.
We were glad of thine from Maryland.
Friends are generally in health, and I know the love of many is to thee;
so concludes thy real friend,

[.signed-section-signature]
Samuel Carpenter.

--

Richard Gove, who is mentioned in the following letter, resided in Philadelphia:
in the latter part of his life he accompanied Thomas
Chalkley on a religious visit to England,
having also been his companion in similar services in the West Indies,
Ireland and Scotland: he died at Uxbridge, near London, in 1710;
and is described by Thomas Chalkley as an inoffensive, loving Friend,
whose testimony was sound, serviceable and convincing.--See [.book-title]#Thomas Chalkley`'s Journal#,
Ed. 1818, page 102.

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Grove to William Ellis

[.signed-section-context-open]
Maryland, the 25th of the 4th mo. 1699.

[.salutation]
Dear William Ellis,

Whom I truly love in the Truth;
the many comfortable opportunities and heavenly visitations that we have enjoyed together,
both by sea and land, is often upon my mind;
and my soul is at this time made glad in the living remembrance of it.
We had a very glorious Yearly Meeting; the Lord`'s heavenly power was over all,
and Friends were greatly comforted and strengthened.
I communicated to the meeting what thou left in charge with me,
concerning a certificate to be sent to your Quarterly Meeting,
which was as readily granted as desired; the which I here enclose thee.
Dear Aaron Atkinson came from New England,
Griffith Owen and Richard Gove from Pennsylvania,
and Roger Gill and Thomas Story from Virginia, to attend our Yearly Meeting,
where they had indeed good service for the Truth.
The priest came and contended openly in the meeting; but Truth was over him,
and his folly and wickedness were manifested to his shame,
among some of the chief of his own people.
I am in some haste, being straitened for time; the ship is just under sail,
so that at present I must conclude,
and tell thee that`' some lines from thee will be very acceptable to

[.signed-section-closing]
Thy friend and brother in the Truth,

[.signed-section-signature]
Richard Johns.

--

William Ellis returned from America to England in the early part of 1699.
The following letter,
expressive of the yearnings of an emigrant over the children of those
to whom he had been united in religious fellowship in his native land,
was entrusted to William Ellis for circulation.

[.embedded-content-document.epistle]
--

[.letter-heading]
A few Lines to the Offspring of Believing Parents in Old England.

[.salutation]
Dear and well-beloved friends in the land of our nativity;

My hearty desire and prayer to God is for you all, and mostly for a young generation,
the children of believing parents,
that it may please the Lord to raise up a remnant
to stand up in the place of our fathers in Christ,
who have stood in the gap and borne the burden in the heat of the day,
and left us good examples; who, many of them,
are gone and going off the stage of this world,
to the everlasting rest prepared for the righteous.
And dear friends, you are often in our remembrance,
when our hearts are engaged to praise the Lord for the prosperity of his Truth;
and we desire your prayers for us,
that it may please God to preserve and guide us in that unchangeable way,
till we meet at the haven of rest, where all the righteous rejoice together forever.
The Lord`'s work prospers in this wilderness land,
and many young people are concerned for the glory of God and the prosperity of his Truth,
that his great Name may not be evil spoken of amongst the heathen;
and I should be glad if it would please the Lord to raise
up many more worthies to visit his seed in these countries.

[.signed-section-signature]
John Cowgill.

[.signed-section-context-close]
From my house in Middleton, in the County of Bucks, in Pennsylvania,
the 9th of the 1st month, 1699.

--
