== Chapter XIII.

[.chapter-synopsis]
* Visit of Samuel Bownas to William Ellis
* Notices of Samuel Bownas, James Wilson, Gilbert Heathcot, and Jennet Stow
* Letter from Gilbert Heathcot
* Notices of John Butcher, Robert Huberstie, and James Waithman
* Remarkable Fungus
* Letters from John Tomkins, with an extract of a letter from John Richardson
* Notices of John Taylor and Jeremiah Grimshaw
* Letter from Theodore Eccleston
* Notice of John Bowran, and letter from him
* Notices of Isaac Alexander, Thomas Pearce, George Rook, John Ecroyd, and Lawrence King
* Letter from Isaac Alexander
* Letter to Nathan Newby, containing advice respecting the Scriptures
* Notice of Thomas Rodman
* Letter to Thomas Rodman

But few incidents relating to the life of William Ellis,
after his return from America have been recorded,
so that little but what is contained in his correspondence can be presented to the reader.
The following notice of a visit to him is from the pen of Samuel Bownas,
who in [.book-title]#An Account of his Life, Travels,
and Christian Experiences in the Work of the Ministry,# mentions being at Airton,
in 1701, "`where,`" he says, "`that great and good man William Ellis,
being then living and full of power,
having great and solid experience concerning the work of the ministry,
was very edifying to me by the wholesome counsel he gave.
James Wilson was then with me, who was not at that time a public minister,
yet of great service in visiting families,
being closely engaged in spirit for maintaining good order and discipline.
And we being very young in these things, this worthy Friend gave such advice to us both,
with respect to a faithful coming up in our services, that we could with good reason say,
that his words were "`like apples of gold in pictures of silver;`" for a long time after,
the sense and virtue of them dwelt on my mind to my great advantage.
We stayed with him one night, and had a small meeting,
in which the preference and value I had for him,
together with an awe that was upon my spirit concerning
his great services and experience as a minister,
took such place in my mind, that I was silent before him.
Next day we took our leave, and he brought us on our way a little,
heartily praying at parting, that I might be preserved in my place,
and return with safety.`"

At the time the foregoing was written, William Ellis was about forty-three years of age,
and Samuel Bownas twenty-five.
The latter was on his way to London to take shipping for America,
in order to pay a religious visit in that country.
He was a native of Westmoreland, and was brought up among Friends,
but did not become awakened to the importance of a religious
life till he was about twenty years of age.
He came forth in the ministry, under the constraining influence of divine grace,
at the expiration of one month from the day of his awakening.
He soon became a diligent labourer in the Gospel, and took many journeys on that account,
returning to his business as a blacksmith, or working as an agricultural labourer,
in the intervals.
The field of his religious labours embraced Great Britain, Ireland and North America.
In the latter part of his life, Samuel Bownas resided in Dorsetshire,
in which county he died in 1753, aged 77 years.--See [.book-title]#Life of Samuel Bownas#.

James Wilson, who accompanied Samuel Bownas on his visit to William Ellis,
was a native of Kirby Lonsdale, in Westmoreland:
he was educated in the way of the Episcopal Church,
but joined the Society of Friends whilst a young man.
He became a minister in his thirtieth year, and was a serviceable man in various ways,
and especially as a peacemaker.
He died at Kendal, where he had long resided, in 1769,
aged 92 years.--See [.book-title]#Piety Promoted#, Part VIII.

Gilbert Heathcot, the writer of the following letter, was a physician,
who resided at Citthorp, near Chesterfield: he married a sister of Sir John Rhodes,
of Balber Hall, respecting whom there is a notice in a subsequent part of this volume.
Gilbert Heathcot appears to have been a useful member of the Society of Friends:
he was appointed by the Yearly Meeting in 1704, along with William Penn,
to lay before the Queen the suffering case of Thomas Rudd, then a prisoner at Canterbury.

Jennet Stow, who is noticed in this letter,
became a minister within the compass of Settle Meeting, at an early age.
She travelled in the exercise of her gift in various parts of Great Britain and Ireland,
and died at Dronfield, in Derbyshire, in 1702, aged about 30 years.
She was attended in her last illness by Gilbert Heathcot, to whom,
along with William Ellis, she bequeathed her property,
as appears by the following letter.
Gilbert Heathcot, entertained a high esteem for his patient,
and wrote a Testimony respecting her,
which is attached to a notice of her in the Seventh Part of [.book-title]#Piety Promoted#.

[.embedded-content-document.letter]
--

[.letter-heading]
Gilbert Heathcot to William Ellis

[.salutation]
Dear Friend, William Ellis;

Our dear friend, Jennet Stow, having left the management of her affairs to us two,
I have here sent thee her last will, which was made when I was from her,
for I never wanted any of her worldly goods; nor do I believe that our all-wise Master,
that orders all things well,
ever intended me to be paid (in that kind however) for what I did for my dear friend;
so that whatever power I may have through or by this will,
I wholly give it into thy hands, hoping the Lord will direct thee more wisely than I can.
I have paid the charges of her funeral,
and I think I have paid every body largely that showed her any help or kindness any way.
I am not willing to give any account of the charges,
because I intend to pay it all myself;
I only beg of thee to be very kind to Mary Simpson,
and I think her relations should have some small token of her kindness,
as thou thinkest fit.
I believe it was the Lord`'s mind, she should end her days with me;
for which I am thankful to the Lord; she was helpful to me in her life and death,
and her memory is sweet.
Dear William, I shall be glad to hear that I am brought into thy remembrance often.
I am satisfied, a man of troubles I am like to be, and not of ordinary troubles;
however I am at present possessed with a humble confidence in my God,
who never failed me yet, and I believe never will, if I can be honest and do my part,
or rather, be willing to let the Lord do with me and for me what he pleases.
My love is dearly to thee and thy wife; your welfare I wish as my own;
and if ever we meet, may it be in that which makes all good meetings;
and if it never be in this world, yet I hope we shall meet at the great and best meeting.
My love is to all that are in the true love.

[.signed-section-closing]
Thy loving friend,

[.signed-section-signature]
Gilbert Heathcot.

--

John Butcher, who is noticed in the following letter, was born in 1666:
his parents were estimable Friends: he became a minister when about fifteen years of age;
he visited many parts of Great Britain in the exercise of his gift,
and was eminent as a peacemaker; he died in 1721, aged 55.--See [.book-title]#Piety Promoted#,
Eighth Part.

William Bingley, who is also noticed in this letter,
became a minister among Friends while residing in Yorkshire,
and from this county visited Ireland in 1675: he was also there again in 1682.
He settled in London as a stuff-merchant when in the meridian of life,
and in 1684 accompanied Samuel Waldenfield on an
apostolic journey in Holland and the Netherlands.
He was one of the Friends who preached at the funeral of George Fox, in 1690;
and he appears to have paid religious visits to different
parts of Great Britain at various periods.
He died in London, in 1714, aged 64 years.

Robert Huberstie, of Yealand Conyers, in Lancashire,
one of the prisoners mentioned in this letter, was committed to Lancaster Castle,
for attending a meeting for worship, at a period when the Government of this country,
urged by an intolerant clergy,
conspired against the laws of God and the inalienable liberties of men,
with the design of compelling all to worship, not according to the Gospel,
but according to statute law:
he joined the Society of Friends when about eighteen years of age.
The Lord bestowed upon him a gift in the ministry,
in the exercise of which he visited the churches of Christ in many parts of England:
he died in 1706, aged about 71 years.--See [.book-title]#Piety Promoted#, Part Fourth.

James Waithman, also mentioned in this letter as a prisoner,
had been in prison for conscience`' sake twice before the time noted here.
The first time for refusing to swear, and the second for refusing to pay tithes.

The "`strange thing`" noticed in New England, in John Richardson`'s letter quoted here,
was probably a fungus;
both in form and stench it seems to have resembled
a plant of the same tribe found in Great Britain,
and called _phallus impudicus_ or Common Stinkhorn.
The remarks upon it are curious,
and show how much the mind may be excited for good or evil by an object not understood.

[.embedded-content-document.letter]
--

[.letter-heading]
John Tomkins to William Ellis

[.signed-section-context-open]
London, the 11th of the 10th mo. 1702.

[.salutation]
Dear Friend, William Ellis.

I had thine last night; it was very acceptable.
I have had many remembrances of thee since I saw thee, and have been about to write,
but have been prevented by divers occasions;
more of them have been to serve others than myself.
I am glad thou hadst unity with my return home; I knew not what weather was to come,
so that was not the occasion; but on my bed that night I did consult the oracle,
and waited for an answer, as David said of old time:
"`Shall I go up to Keilahand I saw my place was to return home and not to go.
It is always safe to follow one`'s Guide, and not to be too inquisitive of the reasons;
but in faith and obedience to submit and follow the leadings of the Holy Spirit,
which will never lead amiss.
I am often comforted in the love, unity,
and sweet refreshment that I met with amongst you at York,
at that Morning Meeting of ministering Friends; the uniting sweet fellowship I felt,
engages my heart to the Lord, and also in love to his people.
I reached Balber Hall on the Seventh-day at night, after I left thee,
was at meeting at Woodhouse on First-day following, on Third-day at Nottingham,
and on Fourth-day at Leicester Meeting in course,
and thought to have reached Northampton Quarterly Meeting, but was prevented,
so got home on Seventh-day by noon.

I have had my health better this winter hitherto, than last winter;
if the Lord continue it to me he shall have the service of it, for I am his,
and I have dedicated my whole strength and days to his honour
and the service of him and of his beloved people.
I am glad Jeremiah Grimshaw is so well; my dear love to him,
I shall be glad to see him at London.
John Meld and John Butcher are well; we are often together;
there is a knot of us bound up together in the bundle of the living;
blessed be the Lord! and we are of one heart, and go one way,
and speak the same thing in the Truth.
William Bingley is gone to Norfolk.
I am glad you are so quiet, though I am not against contending,
and that steadfastly for the Truth, and the most holy faith, against the opposers of it;
yet sometimes, in some cases, there may be a time to forbear, and wait with patience,
the judgment of Truth.
If it have leaden heels, it will have iron hands, and the hypocrite cannot escape,
nor the sinner stand in the congregation of the righteous.
I have been lately at Hertford; Truth goes on, and the Lamb is conquering in many hearts,
and will have the victory.
We are in hopes to get Robert Huberstie and James Waithman, two prisoners in Lancaster,
out of jail.

I have a letter from John Richardson, dated Lynn, in New England, the 22nd of the 7th mo.
last; among other things,
he gives account of a strange thing which appears in New England;
his account is as followeth:--"`There is lately a
strange sort of thing grown up in this country,
in many places; it springs up in one night about a quarter of a yard above the ground,
as white as snow, with a thing about the upper parts somewhat like shoulders;
there is a thing like a cap, which with the aforesaid covering seems to hang loose;
the shoulders have somewhat like a laced veil upon them.
I with many others have seen it; but that which is as much admirable is, the stink of it,
which is so nauseous that I think nothing ever exceeded it for a bad smell.
It is by several, compared with the smell of man`'s flesh after he is dead,
sometime buried, and then taken up again; the sight of it doth terrify some,
and some are putting away their top-knots and finery, especially in Salisbury,
in the east part of that country; but others count it as witchcraft,
and so harden their hearts thus far.`"
John Richardson is in health, though he has travelled hard.
My wife`'s and my dear love to thee; give mine to thy dear wife.
I remember your great love and shall be glad to see you both here.
We are very thankful of the safe arrival of our dear friend, William Penn;
it is the Lord`'s mercy who is gracious to him and us also.
Farewell,

[.signed-section-closing]
I am thy friend and brother in the Truth,

[.signed-section-signature]
John Tomkins.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Tomkins to William Ellis

[.signed-section-context-open]
London, the 17th of 4th mo. 1703.

[.salutation]
Dear Friend, William Ellis;

I have thine to me of the 15th of 3rd month, 1703;
it came to my hand before the Yearly Meeting; and I find thy bishop-like care for us,
and desire that the Lord may help his people,
and judge that which would appear to trouble or afflict
that life which he hath given to rule;
but we should have esteemed it a manifest token of thy care, if thou hadst come thyself,
and contributed to the lifting up of Moses`' hand in the time of battle,
as thou wert pleased to phrase it;
but we have the charity to believe that thou wast concerned
in travail of spirit for the prosperity of Zion,
at the time when others here were actually concerned, in a peaceable spirit,
to contend for the simplicity of our testimony to the precepts of Christ.
And the Lord did comfort his people,
and things were well gone through in several respects;
for the particulars I refer thee to those who were present.
God did bless our meeting with plenty of the water of life, which sweetened all,
and kept things cool and quiet.
Our hearts were comforted in the love of God and fellowship of the brethren;
and counsel was given, and doctrine dropped as the dew upon the tender herbs.
I hope what was done will have a tendency to the
furtherance of charity and peace in the Church.
Come and see us and help us, for we have now much work and few hands to do it;
but however, remember to pray for us,
that our labours in every respect may be blessed for the benefit of the Church,
that an addition may be given us,
and many children may be yet born to the Church of Christ; for the promise is,
that more shall be her children than the children of the married wife,--the Jewish Church,
which consisted of the line of Abraham.
But now God will not only be known in Judah and his Name be great in Israel,
but he hath promised that all the ends of the earth shall see his salvation.

Dear friend, pray for the hastening of the day, that all flesh may see his glory,
that he may "`glorify the house of his glory.`"
Give my dear love to thy wife; I wish her perfect recovery;
my wife remembers her and thee.
Your folks have been pleased to choose me for one of your County Correspondents;
it was their love; I want not employment, but wherein I can,
I shall not be backward to serve them.
Let me hear from thee, and when we may expect to see thee;
I have not material of other matters to advise thee of, but in great sincerity am

[.signed-section-closing]
Thy real friend and brother,

[.signed-section-signature]
John Tomkins.

--

John Taylor, who is noticed in the following letter,
was convinced of the soundness of the Christian principles of Friends by George Fox,
in 1656; he soon felt constrained in spirit to preach the Truth which he had received,
and in 1657, when only about twenty years of age,
he went on that service into the West of England.
Subsequently he travelled much in the work of the ministry in America and the West Indies,
as well as in Great Britain, Ireland and Holland.
He resided several years in Barbados, but subsequently returned to England,
and settled at York as a sugar refiner.
Here, as well as in several places, in the course of his apostolic journeys,
he suffered imprisonment for the testimony of Jesus.
He died at York in 1708, aged about 70 years.

William Wyld, who is also mentioned in this letter, was born at Oldham, in Lancashire,
in 1648.
He joined the Society of Friends, became a minister among them,
and partook of the sufferings to which they were exposed in maintaining
a testimony against the anti-christian impost of Tithes.
He was imprisoned upwards of a year and a half on this account at Lancaster,
where he afterwards settled.
He sometimes travelled in the work of the ministry in the neighbouring counties;
and when he had accomplished these services, returned to his calling,
which is mentioned in a Testimony respecting him as having been humble and laborious.
He died in great peace in 1729, aged 81 years.

[.embedded-content-document.letter]
--

[.letter-heading]
Theodore Eccleston to William and Alice Ellis

[.signed-section-context-open]
London, the 16th of 7th mo. 1703

[.salutation]
Dear William And Alice Ellis;

In true love I heartily salute you both, desiring that you and we,
and all that uprightly love the Lord, may be preserved by him, growing in the Truth,
and in the knowledge of his glorious power reigning amongst us; that while we are here,
in the sense of life, we may magnify his holy Name; and when we are summoned from hence,
that we may be received of Him who was our blessed example, and is our head and lawgiver,
to whom belong dominion and praise, world without end.
Amen.
The Lord be praised for all our mercies,
and for preserving us from everything that would render us unfit for his service,
that in his blessed work we may go on to glorify his Name,
and show forth his power and goodness to the children of men;
that many with us may taste how good the Lord is,
and how good it is to serve Him to whom dominion and praise is due;
and to him be it rendered by us all, henceforth and forever.
My dear love to John Taylor and wife, William Wyld and friends, Thomas Aldam,
Jeremiah Grimshaw, Aaron Atkinson, and all that ask after

[.signed-section-closing]
Your loving friend,

[.signed-section-signature]
Theodore Eccleston.

--

The following Testimony of Jeremiah Grimshaw, of Rawden,
who is mentioned in the above letter, and in several other parts of this volume,
is from the pen of his brother, John Grimshaw, who also was a minister:

[.embedded-content-document.testimony]
--

Jeremiah Grimshaw was born of religious parents,
who brought him up in the fear of the Lord;
and when he arrived at the age of 18 or 19 years,
he zealously followed after those preachers who were accounted the most eminent,
but he did not experience that satisfaction he was in pursuit of,
until he became convinced of the saving efficacy of divine Light and Grace,
through the effectual ministry of George Gregson and Robert Lodge;
and then he gave up in obedience to that powerful Word, which inwardly awakened him,
and which wrought powerfully to the bringing him
into the ministry,--which was living and convincing.
About this time there was a merciful visitation extended towards his neighbours;
and through him, as an instrument, divers were brought to the knowledge of the Truth.
In the early part of his life, he visited sundry parts of England,
and also went through Ireland in the service of Truth,
to his own satisfaction and the strength of the brethren.
In the latter years of his life, he had to pass through divers afflictions; yet,
through the Lord`'s mercy, he was enabled to perform several religious visits,
to the comfort of his friends.
He departed this life on the 12th of the 8th month, 1721, aged about sixty-nine years;
and we doubt not has attained to that rest,
which is prepared for those who hold out in faithfulness to the end.

--

John Bowron, the writer of the following short letter, resided at Cotherstone,
on the northern border of Yorkshire: he joined Friends about 1653,
when about 26 years of age, being convinced of the soundness of their principles,
by the preaching of George Fox and James Nayler.
Soon after this he received a gift in the ministry, and travelled into Scotland,
preaching the Gospel in the streets and markets.
He visited this part of the British dominions several times,
and in 1656 went to Barbados, where he had many meetings:
he then sailed for South America, and travelled in Guiana and other parts,
preaching by an interpreter to the natives,
who regarded him as "`a good man come from far to preach the white man`'s God.`"
From thence he returned by Barbados to England, and continued his gospel labours.
He also visited Ireland many times;
and after all his journeyings and several imprisonments
for his testimony to the Truth as it is in Jesus,
he died in 1704, in the house in which he was born, being 77 years of age,
and full of peace.--See [.book-title]#Piety Promoted#, Part III.

[.embedded-content-document.letter]
--

[.letter-heading]
John Bowron to William Ellis

[.signed-section-context-open]
Cotherstone, 1703.

[.salutation]
Dear Friend, William Ellis;

My love unto thee in the Truth of Almighty God, and to thy wife and Friends thereabout.
I have received the things thou sentest me;
the Lord God of heaven and earth reward thee for thy token of love;
they will do me great service, for which I cannot make thee satisfaction;
but I hope the Lord will not forget to reward thee.
I have a great desire to see thee and thy wife before I die; but how it may fall out,
that I leave to the Lord.
I have been very weakly, but I hope I may yet travel a little in the service of the Truth.
Friends here would be glad to. see thee.
William Kay and Jonathan Kay, as also Peter Atkinson,
send their kind love to thee and thy wife.
This with my dear love to thee and thy wife and Friends in the unchangeable Truth, is from

[.signed-section-closing]
Thy loving brother in the Truth,

[.signed-section-signature]
John Bowron.

--

Isaac Alexander, the writer of the following letter, was born in 1680:
he joined the Society of Friends when about fourteen years of age,
and became a minister in his seventeenth year:
he took apostolic journeys into various parts of Great Britain and Ireland,
labouring diligently in the exercise of his gift; and died at the house of James Wilson,
at Aba, near Kendal, in 1705, aged 25 years.
In this letter he mentions the following persons:

Thomas Pearce, who was the son and successor of Richard Pearce,
an apothecary of Limerick, and the first person that received Friends in that place.
The magistrates publicly forbade the people to buy anything of Friends,
particularly of Richard Pearce; and the prohibition rested upon him for several months;
but he regained his business and followed it with reputation.
The meetings of Friends were held at his house for many
years.--See Rutty`'s [.book-title]#History of Friends in Ireland#.
Quarto edition, page 97.

George Rook, a native of Cumberland, and a carpenter by trade:
he joined Friends when about twenty,
and became a minister when about twenty-five years of age.
He accompanied Thomas Trafford, noticed in page 10 of this volume,
in a religious visit to Friends in the north of England,
and was afterwards imprisoned in Durham jail,
for refusing to break the command of Christ, "`Swear not at all.`"
He laboured in the Gospel in various parts of Great Britain and Ireland,
and settled in Dublin in 1737: he died in 1742,
aged 90.--See [.book-title]#Biographical Notices of Friends in Ireland#.

John Acroyd or Ecroyd, who resided at Briercliffe, near Burnley, in Lancashire:
he is described as an able minister of the Gospel, a steady and zealous labourer therein,
a good example to the flock of Christ,
and a patient sufferer for the testimony of a good conscience.
He died in 1721.--See a testimony from Marsden Monthly Meeting, concerning John Ecroyd,
the son of this Friend, in [.book-title]#A Collection of Testimonies#, published in 1760.

Lawrence King, who is likewise mentioned in other parts of this volume:
he belonged to Salterforth Meeting,
and travelled much in the work of the ministry in Great Britain and Ireland,
between 3697 and 1720.
From 1721 to 1724 he was engaged as the companion of John Fothergill in
a religious visit to North America and some of the West India Islands.
It seems probable that he died soon after returning from this visit,
as no notice of him as a minister occurs after this time;
but as there are the deaths of other Friends of this
name on the record of Settle Monthly Meeting,
without any particulars by which this individual can be identified among them,
it is not easy to determine the period of his decease.

[.embedded-content-document.letter]
--

[.letter-heading]
Isaac Alexander to William Ellis.

[.signed-section-context-open]
Sedburgh, the 15th of 10th mo. 1703.

[.salutation]
Dear Friend, William Ellis;

Whom my soul doth dearly love, and tenderly salute,
in the sweet fellowship of the Gospel of peace, with thy dear and true-hearted wife;
for I can truly say, I have had you both often in remembrance,
with real comfort and gladness of heart,
in a thankful consideration of how often I have been comforted in your good company;
for my very soul was knit and united to you the very first time I was at your house;
and the same nearness I have felt increasingly to remain in my heart towards you,
ever since, both when we have been together, and many times,
when outwardly separated one from another.
And that in the living,
feeling enjoyment of this hearty spiritual nearness and heavenly Gospel fellowship,
we may be preserved increasingly while we have a day on this side the grave to spend,
is what my soul desires and secretly longs for.
And now, my dearly beloved friend, the chief reason of my now writing to thee is,
to give to thee and thy good wife, whose exercises are oft before me,
the remembrance of endeared love, having an opportunity,
and being rather covetous of a free-hearted correspondence with thee in
things relating to the Truth and the affairs of the Church of Christ,
in the exercise of which, I know thy soul is engaged night and day;
and which exercise and labour of love, the Lord thy God that hath been thy strength,
thy bow, and thy song, hath never forgot,
nor hath he been backward to reward thee richly into thy bosom.

Dear William, I speak without flattery,
I know thou hast been a great strength and help to
many of Zion`'s exercised and travailing children;
yea, thy horn hath oft been filled with the best oil, and thy box with healing balm;
as well as the sword of the eternal Spirit and Word of Life given thee,
which is sharper than any two-edged sword in thy hand,
to hew in pieces that Agag that hath been a hindrance
to the Israel of God in their journey,
and an occasion of causing the anointed of God to err in the performance of their duty.

Dear William, I hope that thou, in the reading of these few simple lines,
wilt feel what I aim at.
Now by these, I give thee to understand,
that since I parted with our dearly beloved friend and esteemed Elder, William Edmundson,
at York, I have received several very comfortable letters from him,
in all or most of which he desires to be remembered to thee;
also from Thomas Pearce and George Rook, I have received several; and they do the same.
I had on Seventhday last, one from William, and one from George Rook,
and George Rook wonders what thou art doing,
and that thou should have so long forgot them that so often think of thee with delight;
he says, they long to hear that thou and I are coming together,
to give them another visit.
I have been to visit Friends in Cumberland; they are generally pretty well,
and they long to see thee there; many of them had their very dear love to thee,
and many Friends in our meeting desire to be heartily
remembered to thee and to thy wife.

I am now going to visit Friends in Bishopric, and the east of your county,
and therefore am heartily earnest that thou mayst
have me in remembrance when it is well with thee.
I also have account from Ireland, that things there are generally pretty well,
and that discipline is closely maintained and carried on in great quietness,
and that Truth`'s testimony is over all gainsayers; also William Edmundson is hearty;
but old age creeps on him apace, but his understanding is as strong as ever:
he has got a fall, by which he hath broken a rib, but he mends:
he writes largely of the affairs of Friends.
Dear Thomas Trafford is buried; he died under a surgical operation.
John Acroyd and Lawrence King got to the Half-year`'s Meeting;
they had a heavenly opportunity at this meeting: Friends in Ireland are generally well.
I have received a letter from Samuel Bownas, from Philadelphia; he had a good voyage,
was nine weeks at sea, and had his health very well.
Being in haste,
I shall conclude with my heart full of true brotherly
and abiding love to thyself and wife,
and Friends that ask of me.

[.signed-section-closing]
Thy true friend and exercised brother in the Truth,

[.signed-section-signature]
Isaac Alexander.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Nathan Newby.

[.signed-section-context-open]
Airton, 1703.

[.salutation]
Kind Friend, Nathan Newby;

Having opportunity, I thought fit to let thee know, that I got well to England,
through the great mercy of God;
and although I went through abundance of exercises after I left you,
yet the Lord`'s hand carried me through them all, and great was my comfort at my return.
And now, dear friend, know this, thou art often in my remembrance,
although we be far separated;
and the labour of love that was raised in my heart for your welfare is not forgot by me.
Though I know that there is a sincere remnant amongst you, yet I do know that the Seed,
that is the heir of the kingdom of God, was too low in many;
and that caused a deeper travail upon my mind.
In some degree my desire was answered, and now it is my advice to thee, that thou,
with all that love the Truth,
may labour to bring the Truth up over all looseness and improper liberty;
and that all be advised to let the time past be sufficient in these things,
and that misspent time be redeemed, through true repentance, and amendment of life,
and renewing of love to God and one to another;
and that all Friends be advised to meet together,
and to wait on the Lord to fill their hearts.
If any be opened by the power of Truth, to speak a word one to another,
be sure that Friends be advised to be tender,
that such may grow to the degree of strong men;
and I desire that all Friends may keep their Monthly
Meetings in the name of the Lord Jesus;
and that Friends in his power may judge down all looseness in conversation;
and that none may go out, to take wives nor husbands,
nor to bring mixed marriages to be accomplished amongst you;
for such things brought the displeasure of the Almighty God upon people in old time;
and the church was corrupted by these things, as the Scripture declares in many places.

And let Friends wait in God`'s wisdom to keep the old ranting spirit out of your assemblies;
and let all who may be concerned in Truth`'s affairs truly
seek the honour of God and the promotion of his Truth,
and not the honour of their own name.
And I wish that all Friends may train up their children in the fear of God;
and that while they are young, they may be trained up in the reading of the Scriptures,
that these may be ingrafted in their memory, so that when they grow to riper age,
and their understandings are opened by the Word of Truth,
they may know the profit of the Scriptures,
and may in heart and soul bless the Lord that put into the
hearts of their parents to do these tilings for them.
Seeing it was the Lord`'s counsel to Israel to do these things,
it cannot but be profitable to his people in our age

And let all Friends that have negroes to their servants, be truly careful of them,
and do to them as you would have them to do to you if you were as they are.
There was a secret fear upon me in several places in my travel,
lest Friends`' children `'should suffer hurt in not
being kept to employment as they ought to be,
because negroes are provided to labour for them.
Having thus eased my mind, I leave these things to thee,
and commit thee to Him that is able to keep thee to the end,
and rest with dear love to thee and thy wife,

[.signed-section-closing]
Thy real friend,

[.signed-section-signature]
William Ellis.

--

Thomas Rodman, to whom the following letter is addressed, is spoken of,
by Thomas Chalkley, as a man of the first rank on Rhode Island.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Thomas Rodman.

[.signed-section-context-open]
London, 1704.

[.salutation]
My Dearly and Well-beloved Friend, Thomas Rodman;

Having this opportunity, I was willing to give thee a few lines,
that thereby thou mayst know, that although I be far off thee,
yet thou with many others are often in my memory;
and in this remembrance my heart is comforted with lively enjoyment;
and my hearty prayers have been and are for your
safety and growth in the most precious Truth;
and that many may be affected by the beauty of it;
and that all Friends may grow in zeal for it and love to it;
and that a labour may be exercised to promote its
testimony above all that would oppose it.
For by the power of the Truth have many sons been brought from far,
and many poor as from the dunghill,
to dwell in fertile situations both outwardly and inwardly,
the sense of which often brings my mind low, and a secret holy fear fills me at times,
lest I should in my ways be forgetful.
Also it is a secret trouble to my mind to see any that have
come to sit under the shadow of the wing of Truth,
grow high and elevated in their minds, and forgetful of what and where they were once,
and what abundance of iniquity hath been passed by,
and to think good of themselves for what is done for them,
as though this was some of their own works, and that therefore they must be honoured.
But time hath declared, that upon this rock many have been broken;
and I desire it may be a caution to all to remain under the conduct of the Truth,
and to walk as becomes a people that hath been brought
from a barren land into a pleasant soil.
And now, dear friend, seeing that God hath shewn mercy unto thee,
and given thee a good understanding,
I desire that thou mayst labour to stir up the pure mind amongst Friends,
and that all be advised to keep and increase unity and concord,
which was precious of old, and is amiable in our time; and in this,
young men will entreat Elders, and Elders will be prevailed with; and in the same,
Elders will encourage the younger in every good word and work.
And I wish that that which would spread reports of weaknesses abroad, to disadvantage,
may be kept out from Friends,
so that righteousness may spring up and Truth may grow like a rose,
and the glory and perfume thereof may fill your meetings.
This is the desire of

[.signed-section-closing]
Your real friend,

[.signed-section-signature]
William Ellis.

--
