== Chapter XV.

[.chapter-synopsis]
* Letter from Francis Plumstead
* Notice of Thomas Wilde
* Letter from John Tomkins and others
* Notices of John Blaikling and James Baines
* Letter from William Edmundson
* Notice of Samuel Bownas
* Letter from Anthony Morris
* Letter to Abraham Green
* Letters from William Armistead and John Fothergill

[.embedded-content-document.letter]
--

[.letter-heading]
Francis Plumstead to William Ellis.

[.signed-section-context-open]
London, 23rd of 1st mo. 1706.

[.salutation]
Dear Friend, William Ellis;

I received thine, and was glad to hear of thy welfare,
but it would have been an addition to my joy if thou
hadst said one word in reply to my sincere invitation;
but if thou be more engaged in thy own affairs or pre-engagements,
it shall not break my sincere love to thee,
whilst I and thou keep in that Root which was and is the
life of my love to all the faithful flock of God.
I have a great loss in the death of my neighbour, James Tatham; he was a man I valued,
living, but more now that he is dead;
and indeed I fear to value men too much whilst living,
for fear of being betrayed by their weakness and instability.
I having seen in measure (and thou perhaps more largely)
the readiness with which men are apt to yield to temptations.
George Keith would be great like his father Lucifer;
but he sought it not for God`'s sake, nor his glory`'s sake, but for his own self-honour;
and the Lord laid that honour in the dust.
To go forward upon this subject would fill a sheet of paper.
A word to the wise is sufficient.
I could write much, but am not willing to commit what is in my heart to ink and paper,
so shall reserve it till we have an opportunity to see one another,
which I hope will be at the farthest, at Pentecost.
I hope you will take, or have taken, care in your Quarterly Meeting, to appoint approved,
tried, sound Friends, to attend the Yearly Meeting;
also when you want any London Correspondents,
not to choose till you have the judgment of sound, true men in London;
for I shall never forget what our revered friend William Edmundson said,
upon his sight into, and sense of, the service of the Meeting for Sufferings:
he hardly thought himself fully qualified to be a member of it;
but when I consider what members some have chosen for their Correspondents, in this city,
alas! alas! it hath grieved me deeper than I can mention;
but I hope it will be more carefully considered,
as I doubt not thou art very sensible hereof;
so it is not as a thought of blame upon thee.
Thus with mine, and my wife`'s dear love to thee, thy dear wife and good friends,

[.signed-section-closing]
I remain thy very loving friend,

[.signed-section-signature]
Francis Plumstead.

--

Thomas Wilde, one of the Friends mentioned in the following letter,
belonged to Settle Monthly Meeting: he was born in 1649,
and was convinced of the Truth as held in its simplicity and fulness by Friends,
when about twenty-four years of age.
Being then a tailor,
and much engaged in ministering to the gratification of the vain mind by making garments,
according to "`the needless and superfluous fashions`" of that day,
he abandoned the chief part of his trade for conscience`' sake,
and betook himself to other business for a livelihood; and herein,
though never possessed of affluence,
he was blessed with a competency sufficient for his support.
Not long after his convincement his mouth was opened in a public testimony as a minister,
in a few words; and in process of time he became an able minister of the Gospel;
he was also very serviceable in the discipline of the church.
His religious labours extended to various parts of England and Wales;
and he dwelt in deep humility under a reverent sense
of the goodness and mercy of his God and Saviour.
He peacefully "`departed this life in great patience and stillness`" in 1728,
being then in his eightieth year,
and was interred in the Friends`' burial ground at Low Bentham.

[.embedded-content-document.letter]
--

[.letter-heading]
A Letter sent to William Ellis.

[.signed-section-context-open]
1706?

[.salutation]
Dear Friend,

Thy letter we received, and have answered the same by the post; but notwithstanding,
we cannot forbear to acquaint thee,
that the notice thou tookest of us in thy letter to Thomas Wilde, we take kindly;
and are engaged to thee for the regard thou hast to us at so remote a distance.
We have had some company of the Friends, viz. Thomas Wilde and John Fielden,
and could have desired to have had more;
and should have taken it kindly if thou hadst recommended
them to either John Tomkin`'s or Francis Plumstead`'s house;
but however we are glad of their company,
and are now together at a friend`'s of thine and ours, viz. Thomas Cox`'s,
whose kindness thou knowest.
Truth prospers in this city, and Friends generally are well;
and the Lord is good unto us;
and our heads are borne over all our exercises that we meet with.
God`'s name is great in Israel, and his dwelling-place is in Zion:
the shout of a King is in the assemblies of the righteous.

Dear William, we often think of thee, and much desire thy company,
that we may impart of our spiritual gifts one to another.
Come and see us, and bring thy wife with thee; we have heard of her faithfulness,
love to the Truth, and diligence to serve the brethren; bring her,
that she may receive from us of the kindness that she has shown to the brethren.
There are many brethren here,
and we have made mention several times of thy name with good wishes for thee,
and desires that God may increase all spiritual gifts unto thee,
for the comfort of thy own soul and the edification of his Churches.
Salute us to thy dear wife.
For the rest of affairs among us, we do refer thee to the bearers,
and conclude in all sincerity,

[.signed-section-closing]
Thy true and dear friends,

[.signed-section-signature]
John Tomkins, Francis Plumstead, Thomas Pittstow, William Robinson, Thomas Cox,
Edward Hulley.

--

John Blaikling, of whom honourable mention is made in the following letter,
lived at a house called Draw-well, near Sedbergh in Yorkshire:
he was convinced of the truth of the doctrines of Friends, by the ministry of George Fox,
in 1652.
About two years afterward he received a dispensation
of the Gospel to publish to the world;
and he became a diligent labourer in the vineyard of the Lord,
making apostolic visits to many parts of Great Britain.
He was not only called to preach the Gospel of Christ, but to suffer for his sake,
being several times sent a prisoner to York for holding
or attending meetings for the worship of God,
or for bearing a testimony against the anti-christian
practice of claiming tithes under the Gospel dispensation.
He died at his own house in 1705, aged 80 years,
having been a minister about 51 years.--See [.book-title]#Piety Promoted#, Part III.

James Baines, who is also mentioned with christian esteem in this letter,
was born at Strangerthwait, in Westmoreland,
of parents belonging to the Society of Friends: he began to seek the Lord when young,
and grew in grace as he advanced in years.
It is recorded of him, that "`some time before he died,
God opened his mouth in a public testimony for the Lord Jesus Christ and his pure religion,
in which he was very fervent;`" and in his last illness, "`at several times,
he expressed his great peace with God here,
and full assurance of eternal blessedness in the world to come,
through the atonement made by the Lord Jesus Christ,
and the work of sanctification of his Spirit.`"
He died in 1705, aged 51.--See [.book-title]#Piety Promoted#, Part III.

[.embedded-content-document.letter]
--

[.letter-heading]
William Edmundson to William Ellis.

[.signed-section-context-open]
Tenelle, 5th of 1st mo. 1706.

[.salutation]
Dear friend and fellow servant in the Lord`'s vineyard!

I was at our Province Meeting at Carlow, two days ago, where I received thine;
it came in good time, and was well accepted,
in the same love of God in which I believe it was written.
I am always glad to hear from thee;
but I am touched with sorrow at my very heart for the loss of dear Isaac Alexander.
Though he was a young man, yet he was of a ripe and sound judgment,
and a good understanding in the mystery of Christ`'s kingdom;
and the Lord`'s mighty power accompanied his testimony:
he was my comfortable companion in the fellowship of the Gospel of Christ Jesus,
when I was last in England.
We travelled together in sweet unity, from London to York,
and in many places had powerful meetings together;
and after the Quarterly Meeting was over,
we parted in that love and life that death and the grave cannot overcome.
Since that time I have had several comfortable letters from him,
by which I understand that he retained his integrity
to the Lord and his blessed Truth and testimony,
which I am always glad to hear of.
He wrote me a letter when he had been in the south and west of England;
and gave me some account of his travel and of the prosperity of Truth,
and likewise how he had been sick and was pretty much recovered;
and knowing my old age could not be of long continuance,
he desired me to leave in writing some precepts of advice that might be for his benefit;
but now he has gone to his rest.
According to his years and abilities he might have
lived long and have been of great service,
and I am yet left behind; and the outward man is waxing feeble through old age,
and thereby my service for the Lord`'s Truth is much abated;
but I do not find that my day`'s work is left behind me undone; so, as bound in duty,
I must leave all to the Lord, who knows what is best.

I take notice of the death of old John Blaikling and James Baines;
the first a father and pillar of the church of Christ,
kept close and staunch from the beginning, and was of great service many ways;
and James was a zealous, true man,
and would have Truth`'s testimony preserved in all its branches,
as we first received it from the Lord, and from Elders that have gone to their rest.
The Lord grant that their seats be not left empty in the house and service of God.
And as to those that are counted Friends, and run headlong into debt,
beyond their ability, and break;
the testimony of Truth has gone over them again and again;
and likewise over them that go to law one with another; but as to these last,
the Affirmation hath opened a door for such to sacrifice the Truth to open scandal,
and to rend and tear one another to pieces,
which they could not have done so readily before.
It is the Lord`'s day for making discovery and manifesting both matters and men,
and what and whom he approves; as on the other hand, what and whom he disapproves.
Though pretences be ever so plausible, and designs be laid ever so deep,
the only wise God, in his own method,
is taking off the covering and discovering the ground and root of every one;
that all the churches may know that he searches the hearts and tries the reins;
and those that stand with his testimony, he doth and will stand by them,
over all gainsayers and revolters.
Blessed be the great and holy name of the Lord!

Friends in this nation, up and down, are very quiet; no sufferings,
but a little by some particular priests, and that is very easy,
and the Truth and Friends are in good esteem and credit;
and there is great openness in most places for Friends to have meetings.
We want good labourers,
for we have but a few in comparison to the great openness in most places.
I shall conclude in hearty and true love to thee, thy wife, and Jeremiah Grimshaw,
in a word, to all true-hearted, faithful Friends in your parts,
and about Sedbergh and Kendal or elsewhere, that know me and may ask after me;
they may know that I am not much failed in ability but through old`' age,
which naturally brings weakness of body along with it.
So in the love and peace of our Lord and Saviour Jesus Christ,
I rest thy hearty true friend and brother in the blessed Truth,

[.signed-section-signature]
William Edmundson

--

From the preceding letter, it appears that some who professed with Friends,
and who seem to have united with them in their testimony against Oaths,
went to law with their brethren, when permitted to give evidence upon Affirmation.
This is a remarkable circumstance,
and is one of the many evidences which are to be met with,
that the day of the early Friends was not without trials,
from persons who had joined the Society, but who, in various respects,
were not subject to the government of Christ.

Samuel Bownas, of whom honourable mention is made in the following letter,
was a native of Westmoreland, and born about 1676.
When about twenty years old,
he was awakened spiritually through the instrumentality of the ministry of Anne Wilson,
at Brigflats Meeting, near Sedbergh.
One month after this event he came forth in the ministry,
and soon became an able minister of the Gospel of Christ.
Much of his life was spent in apostolic journeys in Great Britain, Ireland, and America.
In the latter country he suffered imprisonment under
the persecution raised by George Keith.
In the latter part of his life, Samuel Bownas settled in Dorsetshire,
where he died in 1753, aged about 77 years.--See [.book-title]#Life of Samuel Bownas#.

[.embedded-content-document.letter]
--

[.letter-heading]
Anthony Morris to William Ellis.

[.signed-section-context-open]
Pennsylvania, 5th of 1st mo. 1706.

[.salutation]
Dear Friend, William Ellis;

In that love which abides and is unchangeable do I salute thee,
not forgetting thy labour of love, and thy care over me,
for the Truth`'s sake and my soul`'s welfare.
I must confess now,
as I have often done to that which I received through thee as an instrument,
although the work was the Lord`'s, and he it is who gives the increase.
Notwithstanding I knew the Lord in some degree,
and loved the Truth and the prosperity thereof,
for many years before thy coming amongst us,
yet many things stood in my way that wanted to be removed;
and thou wast made serviceable to me therein; and now,
that thou mayst reap something of thy labours,
which may add a little to thy satisfaction,
I may inform thee that the bread thou cast upon the waters many days since, is, in part,
found again.
The Lord, if it be his will, continue to bless thy labour,
and keep thee faithful in his service to the end of thy days;
the same I earnestly desire for myself,
with all the Lord`'s servants and labourers that
he hath employed to run to and fro on his errands,
to call others and invite them to come to the marriage of our Heavenly King`'s Son,
who tells us, that in his Father`'s house are many mansions,
and we faithfully believe the report.
I shall not need to enlarge much on this subject, to thee especially,
because thou knowest more than I can tell thee; but I know by experience,
that fathers love to hear their children talk a little in their minority and innocency;
and if the children do not speak altogether as well as they should,
the fathers will delight to teach them.
And since I have remembered thee,
and given thee an opportunity for some fatherly instructions,
I hope thou wilt not forget me, for I am in want.

And now I think it is time to break off from this subject, and acquaint thee,
that these come by our friend Samuel Bownas, who is a brave fellow, a good workman,
and hath done great and good service here, and we are loth to part with him;
but if you have any more such, let thy prayers with mine be put up to our Master,
that he may send them forth amongst us; for here is abundance of work to be done,
and a great want of workmen.
And now for a conclusion; in the sense of that Ancient Power,
which uniting in love makes us one, all the world over, when truly gathered into it,
do I again with sincere affection salute thee,
and subscribe myself thy friend and younger brother
in the fellowship of the Gospel of peace,
according to my measure,

[.signed-section-signature]
Anthony Morris.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Abraham Green.

[.signed-section-context-open]
Airton, the 29th of 3rd mo. 1706.

[.salutation]
Kind Friend,

Since I left you, thou, with many others, hast been much in my mind, and the more,
because the Lord`'s kindness was manifested amongst us;
and I heartily wish your growth and prosperity in the most precious Truth,
and that it may spread over all your country,
and that those that of late years have come to know it, may walk in it:
it was the just man`'s path of old; it was David`'s guide; it was the guide of Abraham,
Isaac, and Jacob; and by the strength that came from the fountain of it,
was Israel led through the wilderness and through the Red Sea;
and by the strength hereof, Caleb and Joshua inherited the good land;
what shall I say of the fame of the Fountain of it, but even as was said of old,
Thou hast been our dwelling-place in all generations.
And blessed be the Lord that hath made his arm bare in our time,
to bring many back that were gone into a bye path,
and to bring us to the discovery of a most excellent situation,
the glory of which cannot be told with the tongue of men;
and it is intended by Him that we should grow steadfast in the faith,
which gives victory over that which is to be done away,
and brings us into that state of preparation in which, at the last,
we may come to enjoy that which we have had in some measure a foresight of.
In order to this, I wish that I and all may hold fast that which has begun to work in us,
that so we may know a steadfast perseverance in that way that is
cast up for all that love the Lord Jesus Christ.

And kind friend, I desire thee to give my dear love to all Friends about thee,
and tell them my love is to them beyond words,
and that Friends are very often in my remembrance;
and I pray God to preserve you all and make his name
known more and more amongst the dark professors,
that it may be said as of old, that she that sat in solitary places,
and inhabited the wilderness, may sing for joy of heart,
Oh! blessing and honour to the name of the Lord forever and ever.
This is from thy real well-wishing friend,
who desires that Truth may spread over all the earth,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Armistead to William Ellis.

[.signed-section-context-open]
Chester, North America, 24th of 5th mo. 1706.

[.salutation]
Dear Friend, William Ellis;

Having this opportunity, by a vessel bound for Newcastle-upon-Tyne,
I am willing to let thee hear from me, and to give thee some account of our welfare,
which I doubt not thou wilt be glad to hear of.
John Fothergill and I are both pretty well in health,
except overdone by hard travelling and heavy exercises,
abundance of which have fallen to our lot,
and they sometimes bring the body weak and low;
yet through the great mercy and goodness of our God,
strength has been given us to hold on our way hitherto.

Since the last Yearly Meeting at Philadelphia, we have been in the eastward country,
and in New England, and on Long Island, where we spent much more time than we expected,
by reason that we could not be clear without being at their Monthly, Quarterly,
and Yearly Meetings of business.
This hath cost us many miles travel.
At these meetings there was a service for us,
not only in bearing public testimony for the Truth,
but also in endeavouring to settle some good order and discipline in the Church;
for although many are convinced of the Truth in these parts, and make profession of it,
yet there has been a want of good discipline;
and this has been an inlet to abundance of looseness and improper liberty.
But there is a pretty people arising who are willing to take hold of the work;
and in whose hands I have a strong hope the Lord will carry it on,
to his own honour and their comfort; and I think I may say,
Truth gets ground and rises over the heads of such as have
stood to prevent the stroke from coming upon iniquity,
and their hands grow weaker, their knees feebler, and their number fewer,
so that I think I may say, a consumption has taken hold of the Lord`'s enemies.
There is a pretty people upon Rhode Island, who are many of them young;
they are both zealous and knowing;
I hope the Lord will make some of them a blessing to the country.

The present are troublesome times in the eastern parts of New England;
the Indians are often breaking in upon them,
and sometimes killing and carrying away captive some of our poor Friends,
who seem to be in continual jeopardy of their lives,
but most have hitherto been marvellously preserved.
We came from New England to Long Island Yearly Meeting,
and went back to Rhode Island Yearly Meeting, both of which were very large,
and owned by the power of Truth in a good degree, to the comfort of many hearts.
There is at present upon Long Island a considerable
breaking in of the Truth upon many young people,
and great tenderness among them.
I have not heard one word from thee, nor had one line,
though I have written several times to thee;
thou mayst be sure I should have been glad of a letter; but if I be not worthy,
I must be content without one.
Remember my dear love to Friends, and to my relations,
and take the same to thyself and wife and family, from thy exercised friend,
though well content with my portion,

[.signed-section-signature]
William Armistead.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Fothergill to William Ellis.

[.signed-section-context-open]
Philadelphia, 9th of 6th mo. 1706.

[.salutation]
My Near And Esteemed Friend,

Whom I dearly love,
and often remember in a near and sweet manner in these wilderness countries,
where William Armistead and I have good reason to be satisfied that the Truth has led us;
and my spirit of late time has been particularly inclined to write a few lines unto thee;
but this day, came a few lines by Samuel Carpenter to our hand from thee,
of which we are truly glad, which hath increased the openness of my heart towards thee,
which is occasioned and maintained by the bowing, melting life of the blessed Truth,
whereby the great and merciful Hand prevailed upon us,
when far out of favour with the Lord; and by the continued extending of it,
he has led step by step to where he is pleased in some measure to make use of us;
and he is also a careful provider of strength and
counsel to his little ones in needful times.
In awfulness of soul my heart bows before him at this season,
in the sense of that engaging virtue whereby the Lord`'s people, that are really so,
are made really and truly near, although their bodies be far apart.

I would not write largely, my companion having written a pretty large account already,
but my heart being solidly affected in living love, gives thee these few lines,
hoping thou wilt feel a little of the frame and travail of our spirits,
and continue thine for us.
We have a pretty deep share in searching work,
which sometimes takes fast hold both of body and mind;
yet we have some reason to hope it will not be altogether lost labour;
for though things in some places are very poor, and life very low and scarce,
yet there is now more room for labour, in order for the removal of obstructions,
than there has been heretofore.
Here is lately some account come from the east of New England,
of more damage being done by the Indians,
yet Friends keep their places finely in a general way;
and hitherto the Almighty has preserved them.
The Lord God keep them and all in due subjection to him, and in confidence in him,
and reverent, under the renewings of his mercies, is my strong cry.
Here is a suffering people, yet too many more zealous for earth than heaven;
though the earth doth not favour many as it has done.

Samuel Carpenter and his wife, and David Lloyd and his wife, give their love to thee,
and many more.
We came this day out of the Jerseys, from visiting Friends there,
and find hard searching to get way for the Truth, yet have some hope,
because there are growing spirits for the Truth`'s sake,
and we are now intending to visit this Province, having been very little in it,
and to stay the Yearly Meeting, and so down to Maryland, if the Lord will,
and towards Virginia and Carolina,
supposing it will be the latter part of winter at the soonest,
before we can be clear of this Continent.
Clearing exercise seems to prolong our journey beyond what was hoped for;
but through the continued goodness of the Almighty,
and the renewing of that love and virtue which drove us hither,
we are pretty clear of begrudging our time or strength,
yet we hope we shall spare no reasonable pains to shorten time.
In the renewing of abiding love I salute thee and thy dear wife, R. Wilkinson and wife,
and your family, and our dear Friends at the Quarterly Meeting, as thou art free.
Thus concludes thy companion, in my small measure,
in travail for the spreading of the fame and beauty
of the Truth to the ends of the earth.
Farewell!

[.signed-section-signature]
John Fothergill.

--
