== Chapter XIX.

[.chapter-synopsis]
* Meetinghouse at Airton
* William Ellis`'s House
* Provision for the Free Entertainment of Ministering Friends
* William and Alice Ellis`'s Gift for Putting out Apprentices
* Alice Ellis`'s Legacies and Arrangements for the Entertainment of Friends
* Decease of Alice Ellis, and Testimony Concerning Her
* Present state of Airton Meeting, and Settle Monthly Meeting

The Meetinghouse at Airton, which is represented in the frontispiece of this volume,
as sketched by Thomas Tatham, of Settle, stands with its back to the village street.
On the opposite side of this street, William Ellis erected his own dwelling,
in the style of a comfortable farm-house.
There is, over a doorway which has been walled up, in the front of this house,
the date of 1690 with the initials W.E. - A. Over an ample arch of neat structure,
inclosing the fire-place in the kitchen-sitting-room, there are the same initials,
with the date, 1702.
This date is also on the fire grate of the same room.
In a wider portion of the street, and a little higher up, a dial formerly stood,
mounted upon a pillar by William Ellis; and it is not to the credit of the village,
that this monument of his public spiritedness has long since been suffered to be removed.
The pillar is now lying in an obscure corner of the burial-ground attached to the Meetinghouse.

As the great object of the lives of William and Alice Ellis was
to promote the maintenance and spreading of the sound Christian
principles in which they found peace with God through Jesus Christ,
so they made arrangements to promote the promulgation of these principles in perpetuity,
in the place in which they lived,
by providing for the entertainment of such ministers free of charge,
as should uphold these principles.

Through a large portion of their lives,
this worthy couple had entered with much sympathy
into the condition of youths placed out as apprentices,
particularly of those in low circumstances.
Many of these had come under their own care,
being apprenticed to William Ellis to learn the art of weaving linens.
Their care for these youths and other persons in their employ,
both temporally and spiritually,
will have been gathered from some of the earlier letters in this collection;
and toward the close of life,
William and Alice Ellis provided funds designed to perpetuate such care,
and in other respects to help the poorer class of youths
by putting them out apprentices to suitable masters.

For these objects William Ellis, some years after his return from America,
conveyed his house, with certain lands to trustees,
retaining the use of them for the remainder of the joint lives of himself and his wife,
and directing them "`after the death of the survivor to farm the said premises,
a pennyworth unto Friends, by way of scorn called Quakers,
who should willingly entertain such Teachers as might be called of God,
and by him commissioned and sent abroad to preach the Gospel in the free dispensation
thereof;`" of which said Teachers the Farmer or other inhabitants of the said
premises should take no reward or satisfaction for such lodging or entertainment,
nor have the same allowed out of the yearly rents by the Trustees.
After deducting the cost of repairs, with yearly taxes and reasonable expenses,
the first year`'s rent of these premises was to be paid by the
Trustees to the Friends of the Monthly Meeting of Settle,
for putting forth the poor children of Friends to some honest and plain trades.
The second year`'s rent in like manner was to be
paid to the Friends of the Quarterly Meeting at York;
and the third year`'s rent to be employed in putting forth to be apprentices unto Friends,
the poor children of the inhabitants of Airton, Calton and Scostrop,
of what profession soever, to honest and plain trades.
Alternately and successively the rents were to be applied to these purposes.
None of the Trustees are chosen out of Settle Monthly Meeting,
but on the decease of any of them,
that Meeting nominates others from other parts of the county,
to the Quarterly Meeting of York, by which they are appointed.
The original Trustees were Thomas Carr, John Tomlinson, and John Rawson.

Soon after the death of William Ellis, his widow,
for the full answering and further ratifying the will and mind of her late husband,
conveyed her house and premises then in her possession
or in that of any other person under her,
which had fallen to her either by the gift of her
husband or by virtue of her executorship to his will,
being chattels or leasehold, to Henry Jackson, Jr.
Michael Milner, Thomas Aldam, Francis Harrison, John Fothergill, and Bossall Middleton,
to let and set the same premises to farm "`a good pennyworth,`"
to such person of the people called Quakers,
as should willingly at the said mansion or dwelling-house entertain
such teachers as might travel amongst the said people,
to preach the Gospel, they being in society and unity with the said people;
of which persons who might so come unto or lodge at their house,
the farmer or dweller upon the said house or lands should take
no reward or satisfaction for such entertainment or lodging,
provided such a tenant could be got.
The rents accruing were, after deducting repairs, yearly taxes, and reasonable expenses,
to be applied as follows:--The first year`'s clear rent toward
putting forth poor children of the people called Quakers,
apprentices, who inhabit within the compass of Settle Monthly Meeting,
to some honest and plain trade;
and the second year`'s clear rent in putting forth
poor children of the people called Quakers,
belonging to the Quarterly Meeting of York, and inhabitants of the said county,
apprentices to some honest and plain trade;
and the rents of the third year were to be employed in putting
forth poor children apprentices who should be inhabitants of Airton,
Calton and Scostrop, of what profession soever, to honest and plain trades,
to be placed to learn them with some of the people called Quakers,
if such masters could be got.
If the inhabitants of Airton, Calton and Scostrop should sue or disturb,
or call to account in any court any of the Trustees in regard to the said trust,
they were thenceforth debarred from any further interest in the trust.

Alice Ellis also conveyed to Richard Wilkinson, Robert Tunstall, John Moor,
John Tomlinson, Simeon Wilkinson, and John Rawson, a close called Welldales,
in the precincts of Calton, the rents of which, after certain small deductions,
were to be applied in paying the tenant of the house in which she then dwelt,
for the lodging and entertainment of such honest and faithful
Friends as might have occasion on Truth`'s service to travel,
and were in unity with the Monthly Meetings to which they should belong.
The said tenant was to make account yearly to the Trustees;
and any overplus to be paid in yearly to the Friends of Settle Monthly Meeting,
for the relief of the poor not maintained at the common charge of Friends,
and especially, poor widows.

Also that six men`'s coats,
and six women`'s hoods which had been kept for the use of travelling Friends
who might have occasion for them by reason of wet or other foul weather,
either in attending meeting or upon any other honest or lawful occasion,
should be kept for the same use,
and like the furniture be renewed or repaired so long as her trustees should see meet.
She likewise directed,
that in case there should be a clear annual surplus
of four pounds accruing from her effects,
that then, once in three years,
the sum of four pounds should be paid to the Quarterly Meeting at York,
to be employed in the relief of the poorer sort of Friends,
especially such widows as were not constantly supplied by Friends.

In this manner arose "`William and Alice Ellis`'s Gift for putting
out Apprentices,`" and the other benefactions herein noticed,
by which the names of the worthy donors have become familiarised to the ears of many,
by whom their virtuous example and their desire for
the extension of the Redeemer`'s kingdom,
have been little known.

Alice Ellis survived her husband eleven years; her age is not known,
the record of her birth not having been found,
nor any document by which her age could be ascertained.
Her decease is not to be found in the register of the Monthly Meeting;
but the following Testimony, with the notice of her death and burial,
was found among some loose papers, preserved with the records of Settle Monthly Meeting.

[.embedded-content-document.testimony]
--

[.blurb]
=== Alice Ellis, wife of William Ellis, late of Airton, in the County of York, died the 27th of the 5th month, and was buried the 30th of the same, in Friends`' burying ground, at Airton aforesaid, in the year 1720.

[.letter-heading]
A Short Testimony, given by Friends of Settle Monthly Meeting, concerning Alice Ellis,
deceased.

We find ourselves concerned, for the Truth`'s sake,
and in duty that we owe to the memory of our said deceased Friend,
to give forth the following account, and to say of her,
that ever since the time of our first acquaintance with her,
she hath shown evident demonstration of great love to, and zeal for,
the promotion of the blessed, holy Truth, she made profession of;
both by her conversation amongst us, her friends,
and also amongst people of other persuasions.
It being her great care to walk inoffensively before all men,
her conversation amongst us was very exemplary, in many respects,
more than can be mentioned here; yet we shall say a little thereof,
that others may be the more excited and stirred up to follow her pious and godly example;
that so they may at last attain to the like blessed end, which we doubt not,
she is arrived at.

She was a very constant attender of first-day and weekday meetings,
at the meeting places she belonged to;
and also accompanied travelling Friends very often to neighbouring meetings,
wherein she manifested great diligence in a spiritual concern and travail,
for a full enjoyment of divine love and life in her own particular;
and also that the same might abound,
and be plentifully shed abroad in the hearts of others,
in the meetings where it was her lot to be.
And we believe her travail and labour of spirit were answered to a good degree,
relating to herself, wherein she seemed to be much comforted;
and sometimes she appeared in a public testimony,
when constrained thereto by the operation and aboundings
of the divine love and power of God in her heart;
which +++[+++testimony]
was very acceptable to the faithful; being delivered in great fervency and zeal,
it had a tendency to stir up the minds of Friends
to labour for the enjoyment of Truth in themselves,
and also to promote the honour thereof in all respects.

She was also a very constant attender of meetings
for the business and affairs of the church,
viz. the Preparative and Monthly Meetings; and while she had health and strength of body,
was a diligent attender of Quarterly Meetings also:
in all which she was very serviceable amongst her own sex,
being zealously concerned that the younger women might keep to the decent
plainness in apparel that Truth led Friends into in the beginning,
and such as the Apostle spake of in his Epistle to Timothy; and that they might,
in apparel and gesture, keep out of vain modes and foolish fashions of the world,
which render those who are found therein too much like the
daughters of Zion spoken against by the prophet Isaiah,
in ancient times.
She also showed a godly and christian concern and care that
things might be well in all respects amongst Friends,
freely giving advice when she saw occasion;
and also being herself a good example in doing that she advised others to.

She had a tender regard to the poor amongst all sorts of people,
and took great delight in ministering to their wants;
being very free to distribute part of what she had gained by great pains and industry,
when she met with suitable opportunities,
and it would in any wise tend to advance the honour of Truth, amongst Friends,
or others not of our Society,
she being in a particular manner devoted to acts of hospitality, in many respects;
the which, in her life-time, was evidently demonstrated to be her great delight.
And not only so, but likewise to the same end and purpose, in a peculiar manner,
she took care to settle and secure the greater part of what she was blessed with,
so that it might be employed to the same good use after her decease.
And such was her care and conduct,
that although by reason of her business in her outward and temporal affairs,
she had occasion to deal with persons of divers ranks and persuasions,
she gained a good report from, and was well esteemed by most,
if not all that she was concerned with.
Many both poor and others have seemed to lament the loss of her, as we, her friends,
have likewise cause to do,
who have been greatly benefited by her company and help for many years; and therefore,
now that she is removed from us, find our loss to be great.
But we desire to be content, and rest satisfied in the will of God,
who is able to raise up others in her room,
and to qualify them for the service of his church, to his praise and glory,
and the comfort of his people.

We might say much more of the zeal and faithfulness of this our friend,
but for brevity`'s sake, shall only further add, that it is our firm belief,
that it was her hearty and sincere desire to serve the Lord, his truth and people,
to the utmost of her ability, throughout her age and generation;
and that he hath helped her to perform the same to a good degree.
Her reward, we believe, is sure with him, forevermore.
She departed this life the 27th of the 5th month,
and was buried in Friends burying-ground, at Airton aforesaid, the 30th of the same,
in the year 1720, many Friends and others being there.
Divers living testimonies were borne to the comfort of Friends;
and also several others signified their great satisfaction therewith.

[.signed-section-closing]
Signed by order and in behalf of our Monthly Meeting, held at Settle in Yorkshire,
the 1st of 1st mo.
1720-21, by

[.signed-section-signature]
John Atkinson, William Holt, Thomas Clarke, Simeon Wilkinson, John Rawson, Joseph Hall,
William Stockdale, Julian Frankland, Eleanor Carr, Alice Atkinson, Elizabeth Hall, Eliz.
Bradley, Hannah Wilkinson, Eliz.
Armistead.

--

The present tenant of the house at Airton, formerly occupied by William and Alice Ellis,
is John Shackleton, a Friend, who, with his family,
gladly carries out the design of the original occupants,
in the hospitable entertainment of ministers and other Friends.
The great coats and hoods provided by Alice Ellis have long ceased to exist;
better accommodation for travelling,
and the fewness of the visitors of the meeting having rendered them unnecessary.
A small congregation now assembles in the meetinghouse at Airton,
in which also Settle Monthly Meeting is held, in the Fifth and Tenth Months.
There is at this time no person remaining in the Monthly
Meeting in the station of an acknowledged minister;
and the five meetings of Settle, Bentham, Newton-in-Bolland, Lothersdale and Airton,
of which the Monthly Meeting is composed are all very small.
