[quote.epigraph, , Prov. 10:7]
____
The memory of the just is blessed
____

== Preface.

The names of William and Alice Ellis,
had long been familiar to the editor of this volume,
in connection with a fund for putting out apprentices, provided by these individuals;
and he had heard traditional anecdotes of their benevolence and piety,
but was far from justly appreciating their character, until he met with a manuscript,
the property of Settle Monthly Meeting, containing their correspondence.
The perusal of this manuscript threw a light upon their character,
and on the history of the Society of Friends,
at the period in which this worthy pair lived, which deeply interested him;
and he became impressed with the belief that benefit
would arise from making this correspondence public.
The Friends of Settle Monthly Meeting concurred in this belief,
and readily allowed the letters to be copied for this object.
These letters had originally been transcribed, probably under the eye of William Ellis,
with such great care, that they required little correction for the press,
even of a verbal character.
With the exception of a few passages and a very few of the letters,
which did not contain interesting matter, they are here presented to the reader.

Short biographical sketches of the correspondents of William and Alice Ellis,
and of persons mentioned in the letters, have been copiously introduced by the editor,
under the impression that some knowledge of such parties
adds much to the interest of this kind of correspondence.

The other materials interwoven with the letters,
and relating to the life of William and Alice Ellis,
have been gleaned from various sources; they are but scanty,
yet they help to depict examples of Christian faith and practice well worthy of imitation.

The names of places and persons are variously spelled in most ancient records;
the spelling of them adopted in this volume is that of modern maps and printed documents.

In describing the travels of Friends on religious service,
their journeys are frequently mentioned by the editor as "`apostolic;`"
his object in adopting this term was to mark such journeys as being
undertaken in the true spirit and liberty of the Gospel,
according to the apostolic practice, before the restrictions imposed by man,
in the early days of the corruption of Christianity,
had limited the religious labours of individuals to "`their own parishes
and districts,`" and thus introduced a system greatly interfering with
that compliance with the requirements of the Holy Spirit,
which the true Christian minister often finds laid upon him.

A notice of the first gathering of the Society of Friends,
in the district comprised within Settle Monthly Meeting, is introduced as an appendix,
under the apprehension that it will be read with interest
in connection with the other portion of this volume.

The editor ventures to hope that few will peruse this record
of the dedication and zeal of many in time past,
without having their own devotedness to the Lord deepened,
and their zeal quickened for the promotion of his cause.

[.signed-section-signature]
James Backhouse

[.signed-section-context-close]
York, 10th of 5th Mo. 1849.
