== Chapter II.

Certificate to Ireland.
Letters to Alice Ellis--to Friends of Settle Monthly Meeting--from Samuel Randal and
Joseph Pike,--and to Alice Ellis--Notices of Thomas Trafford and James Dickinson.

The following certificate was given to William Ellis, on his visiting Ireland.
It is well worthy of notice, as a document of this kind, of very early date,
and as exhibiting the christian love and the soundness
of the faith of those who issued it,
as well as their lively sense of the right order of the Gospel.
The John Tatham who signs it,
was a predecessor of the present clerk of Settle Monthly-meeting,
who also bears the same name.

At our Monthly Meeting, at Settle, in the county of York, the 5th of 10th mo.
1694.

To our Friends in the unchangeable Truth of our God, in the nation of Ireland,
whom he has called to believe in the light of Ms Son:
Grace and peace be multiplied in and among you.

Whereas William Ellis, a friend and member of our meeting,
unto whom the Lord has committed a gift in the ministry of the word of life,
and sent him forth many, or several times in his work and service,
has put it into his heart, and laid a concern upon his mind,
to go to visit the meetings of Friends in Ireland,
of which he has given us to understand;
and also how he has ordered and disposed of his outward
concerns to the care and comfort of his wife,
and his wife`'s willingness and freeness to give him up in that service,
to our satisfaction.
All these things being weightily considered, in the fear of God by us,
and we finding nothing but that all was well in all things concerning him,
do certify you, or whom it concerns, that we have good and perfect unity with him,
and do commend Viim unto you, to receive him as a brother in the Truth,
and fellow-labourer in the Gospel of our Lord and Saviour Jesus Christ,
to whom be glory forevermore.

From your Friends and brethren in the Truth, met at the Monthly Meeting at Settle,
in England, the day and year above written.

Signed on behalf, and by appointment of, the meeting, by

John Tatham.

The progress of William Ellis in his visit to Ireland,
may be gathered from the following letters.
They all exhibit his care for the honour of God in all things, temporal and spiritual,
at home or abroad.
The notice in the letter to his wife, of the Farewell which some gave him,
on his setting out on this journey, indicates,
that his uncompromising integrity was not cordial
to some who shrunk from faithfulness to the Lord.
Such have in all ages been a source of trial to the spiritually minded,
and have themselves sustained grievous loss,
in regard to spiritual comfort and many other blessings.

Thomas Trafford, who is mentioned in the following letter,
appears to have paid a religious visit to Ireland in 1690,
and subsequently to have settled there: he resided at Wicklow,
and was committed to the jail in that place, in 1701, at the suit of a priest,
for tithes, and kept there two years.
See Gough`'s History of Ireland, and Besse`'s Sufferings.

William Ellis to His Wife.

Daiford, in Ireland, 26th of 11th mo.
1694.

Dear Wife,

After my dear love to you, by this you may know that I am now in Ireland,
but I stayed at Liverpool two weeks, because the wind served not.
It was some exercise to my mind, but when we got to sea, we went well away,
and got to the Irish coast in about thirty-six hours.
There were several passengers that were given to much wickedness,
which was a great disturbance to my mind; also I was sick; but when we got to land,
I soon mended, and my mind rose again.
Our landing was at Dublin, the 21st instant, where we were kindly received by Friends,
who received account of me from England.
The report of our coming to shore got soon into the city,
and several Friends sought us out.
The first man I knew was honest Thomas Trafford, whom I found in the city,
who seemed more than ordinarily glad to see me.
The night we were on the seas, were two Whitehaven ships taken by a privateer,
I suppose in or near the way we went, but we escaped all dangers;
and now being here with Friends, the goodness of the Lord has come upon me,
in the like manner as it often did in my own country,
when the exercise of this journey was upon me.
So calling to mind all these things, with more than I`'ll now speak of,
does much confirm me, that my service for the precious Truth is,
and will be acceptable before the Lord, for which my soul has much travailed;
blessed be his pure and holy name forever and forevermore!

Now the next thing that I have to remind you of is this, that you take care of yourself:
first of your mind, that you do not overdo it; and that you take care of your body,
that you do not overwork yourself: it will be enough that you see the work done.
Twice I dreamed of my men, how that they were not quiet one with another.
Tell them to be sure that they live in love; and though I be not with them,
yet the presence of my Master will be with them, to guide in all the ways of quietness,
if they do but incline to his counsel.
My dear love to them all:
and whatsoever you see would be my place to speak if I were present, speak it;
and as to doing, do in like manner; and let none despise you.
Truth is one, in wife and husband;
and I know none fitter to do the husband`'s work than a wife:
fail me not in this my desire, for my soul is concerned for the honour of God,
let all the unruly say what they will.

My dear love to Richard Wilkinson and wife and family;
and be sure you keep open the door of kindness;
and let nothing be lacking that you can serve one another with.
Mind my love to Thomas Stockdale and his family,
and to old Phineas Parkinson who comforted me, and to Friends generally;
and let me have a full account how Friends manage their affairs,
and what is come of William Hartley and Francis Atkinson,
and whether James Conyers be quiet or not.
If you let in that unruly spirit, it will lay the vineyard desolate;
and the wall being thrown down, the boar of the wood will enter in,
and then will devour every green thing; therefore,
be zealous that the wall which is God`'s salvation, is not broken down.
I am sensible that as the mountains are about Jerusalem,
the Lord is round about his people: and as to my zeal for the Truth,
that has been upon me when among you, I am more and more confirmed;
because the goodness of God does still open upon my spirit.
My mind is greatly eased of all those things that I spoke of to you,
which engages my mind, to love and serve the Lord with all my soul and strength:
and further, it is great ease to my mind, that you parted so freely with me;
for though we be separated one from another, yet I well consider what it is for; for,
for this cause, even discharging our duty when required,
our days may be lengthened to live together to the praise of God,
and the comfort one of another.

My dear love to yourself and to all my men, bidding them have a care of an angry mind,
that leads out of the fear of God.
My love once more to Richard Wilkinson and his wife and children;
I earnestly desire his edge may be kept sharp at all times,
that he may help his fellow in the day of battle, who does fully intend,
by the strength of the Lord, not to fail him in any of his exercises, he may meet with.
Bid George Leemin keep out of foolish pity, which will blind the eye; that is his danger;
and as to such as love this world more than the Truth, blend not with them,
let them pretend what they will: the Lord has opened my eye to see beyond that spirit.
The farewell that some gave me, when I think of it, saddens my heart; but who they are,
it makes no matter, for they have lost their place in my mind.
One thing more I have to tell you of;
James Dickinson has gone through that great city of London, to cry against it.
My love to sister Jennett Davy and Jennelt Stall, and bid them mind the time,
to war when they have their armour on.
So with dear love I rest, your truly loving husband,

William Ellis.

James Dickinson, referred to in the preceding letter, was from Cumberland:
he became a minister in early life, and laboured diligently in the exercise of his gift,
in various parts of the world; he died in 1741,
aged 82. The circumstance alluded to by William Ellis
is recorded in James Dickinson`'s Journal,
Ed. 1847, page 143.

The following epistle was probably addressed to Friends of Settle Monthly-meeting.

Cork, the 26th of 12th mo.
1694.

Dearly Beloved Friends,

Though I be separated in body,
yet is not my travail ended for your good and eternal welfare;
but as my mind was sometimes exercised when with you for the prosperity of Truth,
so are my earnest desires still, that whereas you have received the Truth,
every one with all carefulness may walk in it; and as I have often exhorted,
so I would put you in mind again, that you meet often together, and when met,
labour to be rightly exercised in mind towards God in your particular gifts,
and that none give way to an indifferent mind or a conceited spirit,
which blinds the eye of the pure mind;
but every one keep to the power +++[+++of the Holy Spirit],
so in that you will be enabled to withstand that spirit that leads to sleep and unconcernedness,
which some have been too much inclined unto, to the great dishonour of God,
their own great hurt, and to the trouble and grief of honest Friends;
for where Truth is not lived in, in the inward parts, that spirit takes place,
and so brings forth such fruits.

Also be tender to every green thing that appears,
and labour that such things be weeded out of your assembly as cumber and hurt;
for this I do see, that neither a man nor a meeting shall ever be right before God,
till evil be purged out of the heart.
Let the notion of religion be what it will, those that walk in the Truth, do,
and will receive the goodness of God when met together:
it is such that take delight to come together on God`'s account, and cannot cry,
"`My business, my business`" neither will they be hindered by it,
for they know the great business is to increase their strength in the Truth.
Another thing I desire,
that where the great wolf has fastened or may fasten his teeth upon any,
and they be not destroyed, be sure the wound be truly dressed,
and then pour in the oil of God`'s kingdom,
which men by all their wits cannot prepare or make ready.
And as my mind has often been concerned, so it is,
that when met together on Truth`'s affairs,
which is no less than the helping to set up the government of Christ,
that as the heart is given up to worship,
so the outward things he is to have the disposing of, and not we.
Pray what means the Prophet, when he says,
"`The ships of Tarshish shall wait to bring your sons,
and they of Sheba shall come and bring their silver and gold,
and lay it down at your feet,`" or words to this effect.
So the sons were not to come only, but the glory of all outward things with them:
so then by this, Christ Jesus is to have all, body, soul, and substance;
and the world will never be brought to its right foundation till those things be so.
Labour to set up Christ`'s government among you,
and then I know that whatsoever makes for the Truth and the promotion of it,
will be earnestly pursued.
Let the Spirit bring it forth in whom it will, old or young, high or low, rich or poor,
all is and will be one.
The Lord has opened my understanding to see that there is
a great exercise to be come to and gone through,
in setting up Christ`'s kingdom, besides the preaching of the Truth in words;
so all walk in the Truth, then peace will be found one with another;
for Oh! my soul mourns with a bitter lamentation for all those that walk not in it,
and measure themselves by themselves,
and take the rules of their own making and walk by them.
But this I have in spirit--the Lord is risen in the greatness of his strength,
and has shaken, and is terribly shaking the heavens, and will mightily shake the earth,
with the thunder of his power;
and this is to make ready a people for Himself to dwell in,
that in the end he may bring them to that kingdom that shall never be shaken:
and these are they that do walk,
and more and more will walk according to the rule and government of his Power,
for which my spirit travails, that it may be set up among you.

One thing more has opened in my understanding, and is of some weight upon my mind,
that you be all found in that which gives ease to the souls one of another,--that is,
quickened in the seed of Christ, both in your conduct and in time of worship;
and give no occasion to those that are without; so peace and love will abound from.
God, and will be multiplied one to another;
and in the completing of these things my soul will
be more glad than in the increase of this world,
if I live to see you again.
I am much comforted in my travel in this kingdom,
because the Lord`'s power often comes upon me, by which I am enabled, in body and mind,
to complete that which is fallen to my lot in my day.
My love is dearly commended to all honest Friends,
and great is my travail for such as are not what they should be.
This from your truly loving friend,
who labours with all his strength to exalt the government of Christ in his generation.

William Ellis.

Both the Friends whose names are signed to the following letter,
were Elders in Cork Meeting,
and were highly serviceable in the discipline of the society.
There is a notice of Samuel Randal, in the Sixth Part of Piety Promoted he died in 1718,
aged about 64: and an account of the life of Joseph Pike, who died in 1727,
aged about 72, was published by John Barclay, in 1837.

Samuel Randal and Joseph Pike to William Ellis.

Cork, 14th of 1st mo.
1695.

Dear Friend,

Yours of the 26th of the 8th mo.
to Samuel Randal, came to hand last week, the receipt of which was gladness to us both;
and according to your desire, we shall acquaint Friends of your love to them.
Dear friend, we take notice with refreshment to our spirits,
of the aboundings of the goodness of the Lord with you:
and believing it will be comfortable to you to hear how it is with us here,
we have freedom to let you know,
that Truth does prosper and grow in the hearts of several in our meetings;
and the Lord`'s work goes on among us: blessed and praised be his holy and worthy name,
who is strength in time of weakness, and makes rich those that are truly poor!
Oh! that we may forever be preserved in pure humility;
that Truth may more and more enlarge itself in our hearts;
and self in all its transformings forever be abased, is the earnest desire of our souls;
and believing the fervent prayers and breathings of the righteous prevail with the Lord,
we desire to be had in your remembrance, in the time of your near approaches to him.
We remain your truly loving friends,

Samuel Randal.

Joseph Pike.

William Ellis to His Wife.

The 30th of the 1st mo.
1695.

Dear Wife,

After my dear love to you, for so it is, by this you may know,
that I am now at Lisnagarvey, where Thomas Swire lives,
and have visited Friends South and West, and have but eight meetings to go to,
and then I hope I shall be clear of Ireland;
only I think to see Friends at the half-year`'s meeting, so may spend time till then,
and then I hope to see England again.
The Lord`'s power has greatly borne me up;
I know not that I was ever before in so much need to try its strength;
and in the greatest need of all, it has brought me through,
even as through deep and rough waters; so that I can say, with a freshness in my heart,
The Lord is my shield, my fort and my tower, my stronghold, my rock and my deliverer,
his goodness is now become my deep delight, even as a morning song,
so that my spirit does exceedingly rejoice in God`'s goodness;
and I am persuaded he will give me to see through things in myself,
and also to see through that which stands in Truth`'s way, in many others.

My love to Richard Wilkinson, his wife and children; to all my servants,
and to Abigail Stott; and bid them labour to get to week-day meetings;
and there to get hold of the sweetness of the Truth.
My love to sister Jennett, and to Daniel,
and bid him order his affairs so that you may have his company at week-day meetings.
There is a brave gift in him, if it be but stirred up to increase.
Bid Solomon love the God of his father, and of his father`'s servant; if so.
He will be found of him in all his straits.
My love is to all Friends that love Truth.
I see we shall have brave times, if that old devil be but cast out, that sits so close,
and has so many faces and parts, and is sometimes like a lamb.
This from your truly loving husband,

William Ellis.
