== Chapter IV.

[.chapter-synopsis]
* Certificates to America
* Aaron Atkinson
* Letters from John Tomkins to William Ellis
* from William Ellis to Thomas Aldam
* to John Hall
* and to Alice Ellis
* Memoranda made at sea
* Letters from Francis Plumstead
* John Tomkins to Alice Ellis
* William Ellis to Alice Ellis
* to Thomas Aldam

The certificates with which William Ellis was furnished
on his going to America having been preserved,
copies of them may suitably introduce the correspondence connected with this engagement.
He was accompanied across the Atlantic by Aaron Atkinson;
and they travelled together until the illness of this individual,
and some variety in their religious engagements, occasioned them to separate.
William Ellis appears to have felt released from the exercise
which had attended his mind respecting the West Indies,
noticed in the previous letters, and to have returned to England before his friend.

[.embedded-content-document.testimony]
--

[.blurb]
=== From Settle Monthly Meeting, in the County of York, in Old England, the 1st day of the 7th mo. 1697:

[.letter-heading]
To our friends and brethren in the unchangeable Truth of our Lord Jesus Christ,
in America, or elsewhere (whom it may concern),
whom He has called to believe in the light of his Son.

[.salutation]
Grace and peace be multiplied in and among you.

Now these are to certify you, that our dear friend and brother, William Ellis,
has given us to understand, that it has been in his mind, in the love of God,
for several years, to visit Friends in America;
and we having had knowledge of his labours and travails for the Truth`'s sake,
do hereby certify,
that he has been a faithful labourer in the work of our Lord Jesus Christ,
not only in word and doctrine, but in propagating of every good work;
according to his measure,
labouring to bring up good order and sound discipline in the church; to that end,
that all those that are come to the knowledge of the Truth,
may be established upon that sure Foundation which cannot be shaken,
so that the ancient purity and comeliness that was in the church of old,
may again be restored in this our day.
Thus it has pleased the Lord to exercise him in his work and service,
so that we can truly say our unity with him has been and is,
in that which is beyond words.
And if it please the Lord that he come safe among you, our desire is,
that he may be received by you as a faithful brother and labourer in the work of Truth;
hoping that as he has been concerned among us, he will labour among you,
according to that ability God has given him, in word and doctrine,
and what else the Lord may be pleased to concern him in, for the glory of his Name,
and the good and benefit of his church and people.

[.signed-section-closing]
Signed on behalf of our aforesaid meeting, the day and year abovesaid, by

[.signed-section-signature]
Samuel Watson, John Moore, George Atkinson, John Armistead, John Battersbie, John Kidd,
John Robinson, William Windle, Richard Ibason, Richard Wilkinson, George Lemin,
Thomas Wild, John Moore, Adam Squire, Henry King, Christopher Foster, Thomas Carr,
Thomas Chapman, Thomas Stockdale.

[.asterism]
'''

We whose names are here under-written, being members of the Quarterly Meeting at York,
being this day acquainted by our dear friend, William Ellis,
of the intention of his travel (if the Lord permit) into America, upon Truth`'s service;
and having also seen a Certificate from the Monthly Meeting to which he does belong,
as on the other side, concerning the same,
do hereby further signify unto all Friends to whom this may come,
that we have unity with him in his undertaking;
having known him to be a man of integrity and a sincere
lover of Truth and the prosperity thereof,
and a faithful labourer therein among us, according to the grace bestowed upon him,
since the day and time the Lord gave forth his word
unto him and made him a publisher thereof;
in whose testimony we have been many times truly comforted when with us;
and hope it will be so with all honest Friends where the Lord shall order him.

This from our Quarterly Meeting at York, this 22nd of the 7th month, 1697.

[.signed-section-closing]
Subscribed on the behalf of our said meeting, by

[.signed-section-signature]
John Blaykling, Michael Lazenby, John Taylor, John Jepson, Thomas Aldam,
Marmaduke Beckwith, Thomas Musgrave, John Burgess, Stephen Wynn, George Canby, John Hall,
Francis Harrison, Thomas Thompson, John Walker, John Loft, Bossall Middleton,
Thomas Pinder, William White, William Sharpe, James Rich, Stephen Hunter,
Alexander Hopwood, Thomas Greene, John Smith, Peter Hardcastle, John Burleigh, Sr.,
Michael Milner, Thomas Buck, Francis Thompson, William Thompson, John Harding,
Thomas Johnson, Thomas Hammond, Abraham Kindell, John Bradford, Charles Cannabie

--

Aaron Atkinson, the companion of William Ellis, was born at Moss Thorn,
in the parish of Stapleton, in Cumberland, in 1665,
and was educated among the Presbyterians:
he was convinced of the soundness of the principles of Friends,
when about 29 years of age, by the ministry of Christopher Story,
at a meeting at Hetherside in the parish of Kirklington.
He became a minister of the Gospel while but a young man;
and his friends testify that "`he was the means of bringing many,
not only to the acknowledgment of the Truth,
but to sit under the teaching of Christ our Lord,
the only Shepherd and Bishop of souls.`"
While in the vigour of life, he travelled much in the service of his divine Master.
He died at Leeds, where he had for some time resided, in 1740, aged about 75 years.

John Tomkins, the writer of the following letter, was a minister among Friends,
and the compiler of the first three parts of [.book-title]#Piety Promoted#,
in the fourth part of which there is a notice of him:
he died in London in 1706, aged about 43 years.

[.embedded-content-document.letter]
--

[.letter-heading]
John Tomkins to William Ellis and Aaron Atkinson

[.signed-section-context-open]
London, the 1st of the 10th mo. 1697.

[.salutation]
Dear Friends, William Ellis and Aaron Atkinson;

These are intended as a memorandum,
to put you in mind of my request,--That if it please God you arrive at West Jersey,
in America, you would be pleased, for my sake, if I have any interest with you,
to visit the family of a relation of mine in that country,
and stay at their house as many days as your service will permit.
Give mine and my wife`'s dear love to them, their children and their father.
My kinsman`'s name is John Wills, son of Daniel Wills.
They dwell upon Northampton River, not far from Burlington, in West Jersey.
John Wills`' wife`'s name is Hope; she is my first cousin.
I love her in a double relation, both according to the flesh and the spirit;
for I hear by several honest Friends, that she loves the Truth,
and walks according thereunto.
When you are there, take account from them of their welfare,
both as to things of this life and to the Truth;
and if you see that there be need of advice, give it them;
I doubt not but they will tenderly receive it.
And forget not to let me hear from you by all opportunities,
especially after you have been at their house; and let me know how they fare.
I shall be glad to answer your love and care in this matter,
in any service I am capable of!

And now, my dear friends, the living God, the Lord of heaven and earth,
who has gathered the wind in his fists, and whom the proud waves obey,
in the limits he has set them, be with your spirits,
and preserve you by his almighty power, from all dangers, inwardly and outwardly.
You know in whom you have believed, and on whose errand you are going;
trust in Him alone, He is sufficient for all things.
And go forth boldly in his Name.
I know you are not accustomed to Saul`'s armour;
but I believe you have tried the Name of the Lord, and found it to be shot-proof.
The Name of the Lord is a shield to the righteous,
a breastplate and a helmet of salvation: in short it is the whole armour of God.
It is also a strong tower; it never failed any that trusted in it;
therefore get into +++[+++the authority of]
his Name, whenever you declare his Name, for power accompanies his Name,
and it will make way for the word preached, that it may profit them that hear it.
It was this which gave David victory over Goliath, though that giant, in his pride,
despised him because of the lowness of his appearance,
What! come to me with a staff and a sling! but David came in the Name of the Lord,
and it was that which gave him victory, and made those mean weapons successful,
to the bringing him gasping upon the earth, who defied the armies of the living God;
and it was this Name, through faith in it, by which those of old,
blunted the edge of their enemies`' sword, quenched the violence of fire,
and put to flight the armies of the aliens: it was preaching in this Name which,
was the cause that such multitudes were converted at once:
it was this also which tamed the rough and cruel jailers,
and so softened them towards their poor prisoners for the Truth,
that they washed their wounds instead of wounding them any more;
and which so pricked them to the heart, that they cried out, "`Men and brethren,
what shall we do to be saved?`"
Their answer was, "`Believe on the Lord Jesus and you shall be saved, and your house.`"
This is that Name in which all true preachers went forth, and converted souls to God;
and this is the Name that you have to preach, with the apostles of old,
who declared that there was no other Name given under heaven whereby men must be saved,
but the Name of Jesus.

Dear friends, I was not aware my pen should run thus far before it stopped,
when I first began to make my request to you in the beginning of this paper;
but `'tis an effect of the love of God in my heart to you,
and for your success in the work--that good work whereunto you are called,
and in which you are concerned in spirit; therefore in the same love accept it from me.
And when you are sailing upon the mighty waters,
let your souls be lifted up to the Lord for your native country, which you have left,
and for your intimate friends and brethren, and for the church of God in general`';
that those who have believed may be preserved steadfast in their faith,
and those who are yet strangers may come to believe
in the same Name wherein we have found salvation;
that the numberless numbers, which John said no man could number,
may be gathered from the four winds;
that the kingdom of our God and the power of his Christ may come,
and he may rule and govern in all the kingdoms under heaven.
Farewell, dear friends!
In the love of God and holy fellowship in the Truth, does my soul salute you,
and take my leave.

[.signed-section-closing]
I am your friend and brother, and one who prays for the prosperity of Zion.

[.signed-section-signature]
John Tomkins.

--

Thomas Aldam, of Warmsworth or Warnsworth, near Doncaster,
to whom the following letter was addressed,
is said to have "`received the glad tidings of life and salvation,
by the preaching of that eminent and faithful servant of Jesus Christ, George Fox,
in the year 1651.
He became an eminent minister among Friends,
and was one of the first of their society who were
imprisoned on a religious account in York Castle,
by the high, but unchristian and unreasonable, professors of Christianity in that day.
He died in 1660.
See [.book-title]#Piety Promoted#, Vol.
I+++.+++ Part 2.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Thomas Aldam.

[.signed-section-context-open]
London, the 4th of the 10th mo. 1697.

[.salutation]
Dear Friend, T. Aldam, whom I dearly love;

These are to let you know that the time of our departure from hence is this day.
Aaron Atkinson is like to be my companion.
We have had a fine time in this city.
Here is a Friend out of Essex, and another out of Southwark,
that go with us in the same ship.
Friends are generally glad of our going: and the prayers of the church are put up for us:
and for my part, I am greatly encouraged; and many cautions come up in my mind,
which I see are for my great profit, and suitable to my exercise.
It fills me with admiration to consider what strength is come upon me;
so that the nearest thing I know of, is nothing to me in a manner to leave behind;
but it is God`'s work, and not mine.

Now if you go to York, remember my dear love to Friends in the meeting in the morning,
and be sure to stir Friends up to faithfulness.
The Lord has raised up many of low degree in the world,
and blessed them with the gift of his Holy Spirit,
and has given them substance enough to answer his requiring;
and now if we forget from where we have come, and for what we were raised up,
it will greatly displease the Lord; this is often before me, and makes my mind travail,
to answer the end for which the Lord raised me up, that so I may go through to the end,
and die in the favour of God.
I desire that Friends may pray for us, in that spirit to which the Lord never said, No;
and I desire you with faithful Friends,
to put Friends forward in good order and sound discipline;
it is for that my mind has long travailed; and I am glad that it increases in our county,
as in many other places.
I see there are many that God is raising up, to work the work of their day,
in truth and righteousness.

With dear love to you, your wife, children, and Friends with you, I shall remain,

[.signed-section-closing]
Your real friend,

[.signed-section-signature]
William Ellis.

--

John Hall, of Skipton, to whom the following letter is addressed,
joined Friends by convincement in a silent meeting: he became a minister in the Society,
and was a sufferer with many others in that day for his faithfulness to Christ,
his Lord and Master.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to John Hall, of Skipton.

[.salutation]
Dear Friend;

After dear love to you and honest Friends who know me, by these you may understand,
that I am, with three Friends more, now going off to sea,
in order to our voyage to America, in the service of Truth.
And now, when I am about to leave my native country, some things come into my mind,
with weighty concern for the prosperity of Truth,
and things relating to our duty and service in the church,
for the good of the members thereof, and particularly concerning my old dame,
Abigail Stott.
Considering the station she has been in,
and that in which she is now (she has had service for the Truth above
thirty years) let her be helped in her present decayed condition.
She told me she was willing to give up all she had towards the satisfaction of the creditors,
and desired that Friends would assist her in the management of her affairs:
so I would entreat you to use your endeavours to forward Friends in the matter,
to help her to make money of what she has, to pay as far as it will go.
It was of old, and is still, a part of the pure religion,
which is undefiled before God the Father, to assist the widow in her distress,
and to relieve the fatherless.
If for her sake alone it is not sufficient to move Friends in this charitable act,
let them remember the faithfulness of him that is gone--I mean her deceased husband.
My heart is in exercise and sorrow, lest any blemish should come upon his name,
who is in his grave.
If it be too much for one or two to undertake,
I hope you will find seven Friends or more, if need be, to assist in this matter.
It was so of old, that men of honest report, full of the Holy Spirit and wisdom,
thought it not beneath them to take care of widows, and serve at tables,
while others gave themselves up daily to prayer and to the ministry of the word.
I desire that neither you nor Friends may take what I have thus signified amiss,
it being in the tenderness of my mind.
My love to Abigail Stott, Ann Kingshal, and your wife;
they helped me much in the day of my convincement.
With my love once more to yourself and Friends, I rest your real friend,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
From Deal, on the Kentish Sea Coast, the 8th of 10th mo. 1697.

[.salutation]
Dear and Loving Wife,

After dear love to you, by this know, that I thought good to give you a few lines,
to let you know where I am, because I have no more known time to do it.
I left London last seventh-day,
and have ordered my affairs so that I hope you will not be uneasy at all,
as I gave you account before in a few lines; and as I said before,
I am still cheerful as to my travel, and hope abides with me,
that the Lord will help me through what is before me.
Friends at London are much concerned for our welfare.
Now my dear love,
you know how the Lord`'s goodness has attended and borne us up many times,
when we have been low and under great exercises;
and He has extended mercy in a large manner,
so that I find all too little that I can do for his Name.

Now that I am separated from you, you are likely to have your exercises to the full;
therefore I desire, if possible, that you may live nearer the Truth than ever,
and travail for the increase of it in yourself;
thus your understanding may be more opened by it, so that you may be clearer than ever,
to speak to anything that will advance its fame: and above all,
see you keep your secret retirements, that you may be certain your strength is renewed.
I see that will stand when all words and discourses come to an end.
In the secret of your mind pray for my support,
and that I may be saved out of the enemy`'s reach, both in myself,
and from unreasonable men, and from evil tongues.
I have had much in my mind to write, but time permits not.
Pray remember my kind love to Friends, as Richard Wilkinson and his wife,
Thomas Atkinson, Thomas Stockdale, and Adam Squire.
Tell them to see that Truth`'s affairs be managed with a lively zeal and fervent love.
The time is coming when they will see the good effect of it.
I have made remarks in my mind, how things were left in order, and if I live,
I intend to see what improvement is made.
Fail not to set Truth over all, to your utmost strength; and if I should not come back,
fail not to pay my father`'s debts when you have paid mine.
My love to all my men; bid them love Truth with their whole hearts:
and if they serve you with sincerity, the Lord will greatly bless them.
So with dear love to you, and all Friends as you see fit,

[.signed-section-closing]
I remain your truly loving husband,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.paper]
--

[.blurb]
=== Memoranda of William Ellis

_The 4th day of the 9th mo. 1697.
Made at Sea._--Then was the time I left my country, and took my journey for London,
in order to visit Friends in America.
I stayed in London till the 4th day of the 10th month following, and then went to Deal,
near to Dover.
On the 7th day of the 10th month, I came on ship-board, in the Downs,
and lay there wind-bound till the 15th, and then set sail for America with a fair wind.
On the 21st, a boy fell overboard into the sea, and was drowned,
and about the same time another died and was cast over, and buried also in the sea.

[.small-break]
'''

_The 7th day of the 11th mo. 1697._--
Now concerning Collections, let every one give freely of his substance;
and let none complain of being overcharged, neither deny their substance to the church,
neither say, I have but very little; but remember Ananias and Sapphira.
For as God knows the secrets of all hearts, and how to minister thereunto,
so he knows all your substance better than you yourselves, and how to add to it.
Also let all Friends be careful in meetings that Friends
sit in fear and reverence before Almighty God,
and in that, speak, one by one, to anything that comes before them;
and let every word be duly considered before it be spoken.
So will your meetings grow in gravity;
and the Lord will give the spirit of a sound mind to guide you in all your concerns.

[.small-break]
'''

_The 9th day of the 11th mo.
1697_--We had a meeting, and through deep travail of mind,
the Lord answered and filled my heart with the sense of the good things of his kingdom.
And the night following, I awaked, when the seas tossed;
and immediately a fresh feeling opened upon me that the Lord`'s power was over the seas,
so as to still the strong waves thereof.
And on the next day wind came up in a fresh, steady gale, and pleasant,
so that we ran above six miles in one hour.
Blessed be the Lord for his goodness!
Now I see, it is easy to drink the cup of sweetness and comfort;
and many will be thankful to retain it;
but to drink a bitter cup of exercise at the Lord`'s hand, many are unwilling;
yet it is good to labour to take it thankfully, at the hand of the Lord:
for those that do so in patience may be sure that the Lord
will give them to drink of the cup of consolation.

--

Francis Plumstead, the writer of the following letter, was an ironmonger,
in Duke`'s Place, Houndsditch, London, and a useful member of the Society of Friends:
he died in 1710, aged 60.

[.embedded-content-document.letter]
--

[.letter-heading]
Francis Plumstead to William Ellis

[.signed-section-context-open]
London, the 25th of the 10th mo. 1697.

[.salutation]
My dear and nearly beloved Friend, William Ellis;

I hope you received my few lines in the Downs, but because I am not certain thereof,
I make bold to send these unto you,
desiring of the Lord that they may meet you in health, according as you can desire;
also that you may meet Truth and the affairs thereof according to your soul`'s travail;
that in your journey outward as well as homeward, you may have comfort and consolation,
so that all may work together for the comfort and consolation of those that love Truth,
and the honour and prosperity of it, above all things whatsoever.
God knows my very secret, inward cry and prayers are for this end,
both in the particular and in the general.
Oh, that nothing may ever befall any that have in part
obtained an earnest of an immortal crown,
to eclipse it in the least measure! but that all may so run as
to obtain the full enjoyment of a heavenly and glorious crown,
that never can fade or be eclipsed!--I desire your prayers for a poor travailing soul,
who thus makes bold to visit you with a few brotherly lines outwardly,
which can be read only and truly in that which is beyond words.
As you left things with us, so they continue to be, and are likely to increase,
as far as I see.
Many exercises are likely to attend us, because of the old men that would be great,
and who, because thereof,
are likely to be yet greater burdens to those who would
have Truth only to prevail and be greatest of all,
and self and man, and the man`'s part of no reputation;
so that there is a contrariety which can never be reconciled: the one is for,
"`I am ancient and was in the Truth before you were born,
and therefore be quiet young man;`" the other looks not at old or young,
but at Truth only, both in old and young, at home and abroad,
in the particular and in the general, the prosperity and increase of which,
is all they desire.
Our dear love is to yourself and to all dear Friends;
so I remain your dearly loving friend,

[.signed-section-signature]
Francis Plumstead.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Tomkins to Alice Ellis.

[.signed-section-context-open]
London, the 3rd of the 12th mo. 1697.

[.salutation]
Dear Friend;

With dear love to you, for your dear husband`'s sake,
who is dear to me for the love and zeal I felt in his heart
for the promotion of that ever blessed Truth,
which God has brought us to the knowledge of;
and which I doubt not but he will continue to use his utmost endeavours to promote.
And doubtless he shall not lose his reward, who so cheerfully can forsake wife, house,
land, and all that is near and dear in this world, for Christ`'s sake and the Gospel`'s;
and I am firmly persuaded also, that you will have a share of the same reward,
who so cheerfully has given him up in this service,
as having regard to the carrying on of the good work which God has begun on the earth;
believing that the Master, on whose errand he is gone, can preserve him in his journey,
and bring him safe back again to you; or else, if He please to order it otherwise,
is able, and will, no doubt, make up the loss to you in Himself,
in giving you a plentiful portion of his love, life, and presence, even in this world,
besides in the world to come,
an everlasting inheritance of glory with his saints and servants, world without end.

[.signed-section-signature]
John Tomkins.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
Maryland, the 22nd of the 1st mo. 1697.

[.salutation]
Dear and Loving Wife;

After my true and unfeigned love to you,
which does so abound that I cannot express it with ink and pen,
these come to let you know, that once more the Lord has extended mercy to me,
and brought me to my desired haven.
We have passed through such perils by sea that I cannot express it;
and when we came within two miles of land, we had like to have been wrecked on the shore;
but through all, God has delivered us; for which my heart is thankful to the Lord.
When I set my eyes on the country,
my heart was so filled with the Lord`'s goodness that I was hardly able to contain.

We landed the 14th instant, and have been at several meetings,
where we were gladly received by Friends and other people;
and the Lord`'s goodness has so filled my heart, that words have failed to express it.
This day we had a meeting where many Friends came, and others;
where my heart was opened in the Word of Life, to sound forth the day of salvation;
my heart was more glad than of thousands of gold and silver!
Aaron and I are for going towards Virginia and Carolina,
in about five or six days`' time, and we intend to come back in three or four months,
and go for Pennsylvania.
I cannot express my solid satisfaction that I have, which makes my faith and hope strong,
that the Lord will assist me.
I suppose I shall be about the countries of Pennsylvania,
about ten or eleven months from this time;
so send me a few lines by way of Liverpool or London.

Theodore Ecclestone will take care to send to me, or forward it.
I will endeavour to clear myself as I go from place to place;
and I hope the Lord will assist me to do it.
Now I desire you to live near to the Truth;
and by it you will be preserved over all the troubles
that may come upon you for lack of my assistance;
and labour to keep your family in good order; and if any body seem to be contentious,
do what you can to quit your hand of them; and labour to bring things into such method,
that if it please God to bring me back,
all things may be managed to our ease and comfort, that, if possible,
we may serve Truth more than ever.
And labour in God`'s wisdom, to subdue evil in your family and in the meeting;
but on the other hand, when you have cleared yourself,
be sure not to fret yourself at evil doers; but commit your cause to God,
who will ease you in his time.
I know we have had our part of trouble, but the Lord has set us thus far over it all;
and I hope he will preserve us to his heavenly kingdom.
Fail not to send me a few lines with anything that is needful;
and as to the present station you are in, hear all things, bear all things,
and suffer all things; and in due time, if you faint not, you will overcome all things.
I have abundance in my mind to say to you, but time fails,
but I hope to write again in three or four months time.
So with my love to Friends in general, I rest,

[.signed-section-closing]
Your truly loving husband,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Thomas Aldam.

[.signed-section-context-open]
Maryland, the 22nd of 1st mo. 1691.

[.salutation]
Dear Friend, whom I love in truth, and for the Truth`'s sake;

These few lines I have written unto you, to let you and Friends know of my arrival,
which was on the 14th instant.
We had a long passage.
Our ship had liken to have been wrecked on the Capes off Virginia,
with many apparent dangers, but escaped all; for which my heart is thankful to God.
We are kindly received by Friends, and many other people,
though we have not had many meetings yet.
I see here is great need of faithful Friends to visit these parts;
and I hope the Lord will stir up the hearts of many to this service.
Soon after I set my eyes on this country, my heart was filled with the goodness of God,
so that I was not able to contain myself; and it much dwells in my heart,
which makes me think the Lord`'s mercy is much to these countries;
also it is a great confirmation to me,
that the Lord will assist me with his good presence,
which has been my chiefest pleasure for many years.
I intend to spare neither my body nor time,
so that I may discharge myself of what is fallen to my lot;
and I often think in my heart,
that all is too little that I can do for the worthy name of God,
such have his mercies been to me, whereby to make me willing, both with body,
soul and substance, to be given up to serve him.
Oh! the goodness of Truth fills my heart!
I desire that all that know it may be persuaded to love it.
There is no glory nor beauty like unto it;
and I desire that such as God in his lovingkindness
and mercy has bestowed gifts of his Holy Spirit upon,
may be stirred up rightly to improve them,
to the advancement of the honour of their Lord and Master;
and that they may labour always to be found in those things that make for peace and love:
so will their unity increase with the Father and the Son and one with another.

I desire you to remember my true love to Friends, met together at the Quarterly Meeting,
with whom my soul has had unity for twenty years or more;
and my heart and mind has laboured in secret for Truth`'s prosperity among them;
and when anything has appeared which has brought trouble on that meeting,
it has greatly afflicted my spirit; and when Truth has prevailed,
my soul has greatly rejoiced; and the last time I was there,
my heart was filled with thanksgiving to God,
because I saw a holy zeal stir in many Friends`' hearts for good order;
and that it might increase from one end of the country to the other.
I pray God increase it more among you.
And this I have to say to Friends, in the word of Truth,
That if a true care and diligence be observed,
the Lord will bless your endeavours and prosper his work in your hands; for out of Zion,
the perfection of beauty, has God shined,
not only to convince people of the evil of their ways, by his Truth,
but to establish them in the sound and holy order of the Gospel.
Oh, the comeliness of the government which the Lord is putting upon the true church,
and the beauty of that dwelling he is about to settle her in,
affect my heart! but libertines cannot behold these things,
therefore are they sorely displeased at such as labour to see this work completed.
The Lord is on his way;
therefore it is my desire that all may be strong for God and his Truth.
Remember my dear love to Friends of the morning-meeting.
I desire you to send a copy of this to my wife.
So with true love unto you, your wife, children and friends, wishing all your welfare,

[.signed-section-closing]
I rest your Friend in the Truth,

[.signed-section-signature]
William Ellis.

--
