== Chapter V.

[.chapter-synopsis]
* Letters from America to Settle Monthly Meeting
* Alice Ellis to her husband
* William Ellis to his wife
* Aaron Atkinson and William Ellis separate
* Letter from Aaron Atkinson
* Anecdote from Thomas Story`'s Journal
* William Ellis to Thomas Johnson

The care of William Ellis for his Friends in England
was soon made manifest after his arrival in America,
as will be seen by the following epistles to his own monthly-meeting,
and several of the following letters.
No journal of his travels in America appears to have been kept,
but his course may be traced by his correspondence in this and subsequent chapters.

Settle Monthly Meeting,
at the period at which the following epistles were addressed to it,
was composed of the Preparative Meetings of Settle, Bentham, Newton-in-Bolland,
Rilston (including Airton), Scarhouse, Salterforth, and Selside.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to the Monthly Meeting, at Settle, in Yorkshire.

[.signed-section-context-open]
Maryland, the 25th of the 1st mo. 1698.

[.salutation]
Dear Friends,

This comes with my true love to you all, to let you know,
that through the great mercy of God, I have escaped many apparent dangers,
both by sea and land.
We arrived safe in Maryland on the 14th instant,
and I feel the Lord`'s power near to assist me through the great work that is before me,
for his Name`'s sake; and by it my heart is warmed, my faith strengthened,
and my hope established.
Now my dear friends and faithful brethren, though I am separated from you,
yet you are often in my mind, because I know that the Lord is with you;
and many times have I known and felt in your meetings,
the love of God to fill my heart among you; and it has been my great joy,
to feel the Lord`'s weighty counsel among you, to direct you in your affairs;
for his Truth and Name.
Oh! the remembrance of it fills my heart now, as it did when I was with you;
and my heart is thankful to God,
that he has counted me worthy to labour with you in those
things which have wrought for the honour of his Name,
and the spreading of the fame of his Truth abroad.
It has been the kindness of God, and his love in our hearts,
that has engaged us to this service; and Friends,
you know that since the day that the gracious God has concerned me,
how that I have served him, not only in word and doctrine according to my small gift;
but my strength, understanding,
and all that little substance that God has given me in this world,
have been given up to his service.
Let God have the glory of all we can do,
and let the beauty and comeliness that is in the
Truth shine through every believer therein.
And further, it is my advice to you in the love of God,
that as he has opened many good and wholesome orders and methods among us,
for the discipline in the church of Christ, so let your hearts grow strong for God,
and full of mighty and holy zeal to put them in practice; and labour with all diligence,
that you may be found in the practice thereof, in every particular meeting;
so that all coldness of zeal and indifferency of spirit in religion,
and looseness of conduct may be watched against and put a stop unto,
as much as in you lies, and that every green and tender thing, whether in poor or rich,
be cherished; and if any have done amiss, let the time past suffice,
that they may now seek the Lord by true repentance,
and hearty acknowledgement of their offence;
that if the day of their visitation be not past, they may find mercy with the Lord.
Oh, let your waiting be upon the Lord in your monthly-meetings, and at all other times,
for wisdom and counsel to manage the Lord`'s business; and for a spirit of discernment,
that you may distinguish between true repentance and feigned humility;
for the hypocrite cannot approach the Lord so as to find favour with him.

And the great desire of my heart is,
that all Friends be advised to keep to that Power that will keep their souls alive,
fresh and open to the Lord, in their retired meetings for the worship of God;
so that all idleness and sleepiness may be kept from among Friends;
that those Friends who may be concerned for God in
public be not burdened and grieved with such things;
but that their joy may be full in the Lord, in the increase of their gift,
in the root of life; and then, as anything opens upon them,
doubtless it will be to the affecting of the hearts of all that hear them.
Oh! the weight that my soul has gone under,
that I might see the work of Truth accomplished among you;
and I desire you to make inquiry how the weekly-meetings are kept up,
and see that Friends grow in it duly.
The strength that I have often gained in those retired meetings,
I do find stands in me steadily in this my travel.
Oh! my heart is warmed within me, when I remember those good seasons,
and how the Lord filled the hearts of the faithful,
that they could not forbear to meet together,
that they might purely enjoy the presence of God; and I have made some observations,
that those who have been indifferent in that work,
I have not seen grow to the stature of a strong man in Christ Jesus,
who is Lord of our assemblies.

And my desire is,
that that good work of taking care of poor Friends`' children may be minded among you;
and that Friends be minded to give freely towards the relief of the poor,
as God has blessed them; for as the Scripture says,
"`God loves a cheerful giver;`" and it has been a saddening to my heart when
I have heard complaining of need in the time of sacrificing at the altar.
In the time of the old Law, the Lord required this,
That none should appear before him empty, and I know the Lord requires it now.
And dear friends, labour in the life of Truth,
which God in his love has opened in your hearts, to keep in the bond of peace,
and that all contention,
and all that would contend for false liberty may be kept out of your assemblies,
so as to have no place among you; so will you grow fruitful as a garden enclosed;
and the works of your hands will send forth a pleasant smell.
God, through his tender mercy has showed me these things in the opening of life in my heart.
And so the Lord prosper his work in your hand, is the desire of my heart;
so that if it please him to bring me back,
I may behold the glory of the Lord among you,
and be partaker of his joy and consolation among you,
is the fervent prayer of your real friend,

[.signed-section-signature]
William Ellis.

[.postscript]
====

P+++.+++ S.--When you are met together, and you feel the Lord`'s power upon you,
present your requests to God for my preservation every way;
and let this be read in your men`'s and women`'s
meetings in the same love that it is written in.

====

[.signed-section-signature]
William Ellis

--

The epistle, from which the following extract is taken, appears to have been,
in some degree, a duplicate of the former one,
but some of the additional matter is of too much value to be omitted in this collection.

[.embedded-content-document.epistle]
--

[.letter-heading]
Extract from an Epistle of William Ellis to Friends, at their Monthly Meeting at Settle.

[.signed-section-context-open]
Maryland, the 30th of the 1st mo. 1698.

[.salutation]
Dear Friends;

As I have been exercised among you,
it still is my fervent desire that you may be faithful
to what God has committed to your charge,
and be careful to meet diligently together on the week-days,
and let not things of this world overcome you,
and cause you to make excuse for negligence in your duty;
but wait that your minds may be kept under a concern for Truth,
and that will keep out the spirit of the world which will bring
thick darkness over your minds and sleepiness over the body;
but wait in, and stand fast in the name of the Lord;
so that that life that outlives all that is contrary to God may fill your hearts,
and that by it your strength may be renewed to serve the Lord and one another;
and I know that those who are found lacking in their duty to God,
will not grow up to God`'s honour, nor be helpful to the building up of the church,
but will be found complaining like people that dwell in a barren land.

Dear friends, since the day of my convincement,
I have seen and felt the benefit of meeting the Lord`'s people;
and I am thankful that I am kept sensible, even unto this day,
of the benefit of inward retirement before the Lord: and Friends,
keep up your Preparative Meetings,
and wait in God`'s wisdom that your hearts may be filled with his
counsel to act and speak forth those things that are most for the
honour of his Name and good of the whole assembly.
And minister diligently to the necessities of the poor, and fatherless, and widows;
and labour in the power of God, and in that, rule over all disorderly and unruly spirits,
that the government of Christ may be known to be upon his shoulders; for `'tis said,
"`Of the increase of his government and peace,
there shall be no end;`" and labour to keep out all that which would disturb your unity,
which stands not in shaking of hands, nor inquiring of the welfare one of another,
but in the spirit of our Lord Jesus, our Foundation and chief Corner Stone.
Beware of feigned humility, but be tender of all those who are coming up to serve Truth;
and let those Friends who are anciently convinced be good examples in their places,
that those who are young and are seeking the Lord and the knowledge of his way,
may not be hurt by their examples;
and let none sing without the spirit and understanding also;
but labour that the life of Truth may fill your hearts;
that is it which makes all capable to serve the Lord with acceptance.

Pray take notice and call to mind respecting some
that have professed Truth in times past among us,
but walked after the devices of their own hearts;
what misery and distress came upon them, even to the end!
The remembrance thereof has often filled my heart with sorrow;
yet I bless the Lord with my whole heart,
because he has given me to see that he is about to
raise up such as will answer him with a willing mind;
and it is my great joy to see Truth prosper.
Though I be far separated from those things which have been and are dear to me,
yet the presence of God makes me to say, all is too little that I can do for his Name.
This day we have had a great meeting, where abundance of people came,
and three justices of the peace, where it was opened to them from the Lord,
that he had sent the Physician of value,
who has the Balm of Gilead to heal the wound of the daughter of Zion.
The Lord is about to spread the fame of Truth in these countries.
With dear love to you all,

[.signed-section-closing]
I remain your dear friend and brother,

[.signed-section-signature]
William Ellis.

--

The excellent spirit of true helpers in Christ, exhibited in the two following letters,
as well as in many others in this series, deserves the serious attention of the reader.
The tender affection of William and Alice Ellis,
and their devoted dedication to the Lord, are touchingly set forth,
and depict a fervency of spirit, such as might lead to the expectation,
that the divine blessing would attend their labours,
and that the work of the Lord would prosper in their hands.

[.embedded-content-document.letter]
--

[.letter-heading]
Alice Ellis to Her Husband

[.signed-section-context-open]
Airton, the 15th of the 2nd mo. 1698.

[.salutation]
Dear and Loving Husband;

After the salutation of endeared love to you,
I thought fit to signify my mind a little to you.
Dear love, you are often fresh in my remembrance to my great comfort and satisfaction.
I feel the renewings of the love of God to be shed
abroad in my heart in a larger manner than ever,
that the Lord who drew your mind away from all that was near and dear,
may make your journey a prosperous journey, and make it effectual,
for the end for which he called you;
not questioning at all but the Lord who has stood by us in great trials and exercises,
will carry us on and through, to the glory and honour of his great Name,
and to our own satisfaction and comfort,
as we serve him truly in the sincerity of our hearts.

So my dear love, though we be far distant in body,
yet as we keep in the universal love of God, we are present in spirit,
and as near as ever.
I cannot word the nearness I feel in the remembrance of you,
which many times causes my soul to rejoice;
but at times it has pressed upon my mind with weight,
that you do not travel over fast forward, but that you may take time,
that thereby you may discharge yourself more clearly in the sight of God; and this will,
I believe, tend to your own satisfaction and future happiness both here and hereafter.
If your companion would seem to draw you or hasten you to get your service over,
I earnestly desire you to be very careful to mind the drawing of the Father`'s love,
which will open to the view of your mind, and give you a clear discovery,
where your service lies.
I have been a little afraid for some time, lest you should be drawn homeward too soon,
and you should leave some places or Islands unvisited, which would cause uneasiness,
and deprive us both of the benefit we might enjoy hereafter.
These things have been much in my mind both by day and also in the night season;
when in sleep, I thought I had been talking with you, and saying, "`Take your time,
and perform your service fully;`" and withal, I earnestly,
praying unto the Lord to enable you to perform the same.
Take no care for me, as for outward things; for I believe things will be well,
and I intend to endeavour to answer your mind in what you wrote to me from London.
Now I feel my mind eased; only when the goodness of Truth is in your heart,
then remember me.

[.signed-section-closing]
So I rest and remain, your true and loving wife,

[.signed-section-signature]
Alice Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
Written at Chuckatuck, in Virginia, the 19th of the 2nd mo. 1698.

[.salutation]
Dear Wife;

This with true love, comes to let you know how and where I am.
I wrote to you and several Friends before, but lest the letters should miscarry,
I have added these few lines, to let you know that we have gone through part of Virginia.
We find many poor dejected people that profess Truth,
who for lack of true care in themselves, and of visiting by Friends in love and zeal,
are grown too cold.
You have known the manner of my exercise where such things have been,
so that I need say less on that account.
However, we labour sore to bring to people`'s remembrance,
the beauty and comeliness that is in the Truth,
and people`'s hearts begin a little to warm;
but I cannot see but that we must see Friends twice over in some places.
Here is a Yearly Meeting intended to be kept in the third month, where we hope to be;
and we intend to speak to the Elders among Friends, to be more zealous for the Truth,
and for the good order of it; and then we intend for Maryland, and if we live,
towards Pennsylvania.
I suppose we may be in these countries till the 11th or 12th month;
so if Robert Haydock send any ship for Pennsylvania, send me a few lines: and dear wife,
I am much concerned for you every way, and earnestly desire your foot may not slip;
for now is our time to labour to get the heavenly crown;
and seeing we have so long and hardly travailed to obtain it,
that we may not fail now when our time cannot be expected to be long;
for the time comes that those who win the race must have the gold.
I cannot express my care for you,
because I know you will meet with many enemies for Truth`'s sake,
I being separated from you.
While I was with you, I know false hearted people were made to bend,
yet it is my comfort that you have some true-hearted Friends to stand by you.
Be sure if you open your heart to any, let it be to such as you can really trust.

My dear love to Adam Squire, bid him be sure he marry such a one as loves the Truth.
My love to my family in general, and to Thomas Atkinson, if he be alive;
he has spoken of true love and pure innocency;
I hope he will have a measure of them both to accompany him till the last.
Tell Simeon Wilkinson to walk in the Truth without wavering,
and that he fall to work upon that part that works
in his nature to make him of a testy or angry mind,
so that God`'s blessing may come upon him in his old age.
Likewise bid Joseph labour to overcome the inclination of his mind,
and speak to every one according to their inclinations.
My love to brother Daniel and his wife,
I heartily desire he may get through all his outward trouble,
and then to knock the world on the head,
and make it his business to serve the Truth to the utmost of what it requires of him.
My love to Lawrence King, and tell him not to tie himself to the world,
but upon sound terms, that he may have the more time to serve the Truth.
A poor people here sit for many weeks in meetings, and hear few or no words spoken.
Yesterday I was told that several poor women came ten miles on foot to meeting,
and some brought their little children in their arms.
Discourage nobody that is really inclined to come to these parts to see Friends,
for here is a great work to be done before the fame of Truth be set over these countries.
My love to Elizabeth Moore, and tell her that I am much concerned for her son John,
that he may get such a wife as will really love and serve Truth,
that as her zeal and love has increased, so her comfort may increase in her old age.
I live in hope to return back and enjoy your company,
which is more to me than all things that my outward eye has seen; and till then,

[.signed-section-closing]
I remain your loving and affectionate husband,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Extract of a letter to Alice Ellis from her husband.

[.signed-section-context-open]
Page in Creek, in Virginia, 19th 3rd mo. 1698.

We have been once through Virginia, and through Carolina,
where we have found many tenderhearted people, and had much hard service,
things being much out of order among Friends, and wrong-minded people bearing sway;
but the Lord has wonderfully appeared and assisted us to set Truth over all opposition,
so that I hope we shall go clear out of this country.
The last First-day we were at a Yearly Meeting, and two days after,
being the 19th instant, eleven Friends took a boat to go to a Friend`'s house;
and the wind rose, and we were in great danger of being cast away,
water driving into the boat, so that we were like to sink,
and I with two or three Friends more were thrown out of the boat;
but the Lord had mercy on us for his name`'s sake;
so that by hard toil we got to a vessel; but to conclude the matter,
we were all preserved. There is much travel here by water, but I will take what care I can,
and the rest must be committed to God.
Thus with true love to you,

[.signed-section-closing]
I remain your true and loving husband,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to His Wife

[.signed-section-context-open]
West River, in Maryland, the 16th of the 4th mo. 1698.

[.salutation]
Dear and Loving Wife,

After the remembrance of my true love to you,
by this know that I have written often to you, but lest letters should miscarry,
I think fit to write as often as I have opportunities to send.
Here has been a Yearly Meeting that has held five days,
whereto many of the great men of the country came, and several priests and the Governor,
and the Lord was pleased to assist me to my great comfort and Friends`' gladness,
though I had gone through more exercises two or three weeks before, than I can express;
it brought both body and mind low, but I have been made able to bear it.
I left Aaron in Virginia, but hope he will be here in a little time;
then we shall be for Pennsylvania if health be granted,
but here is a great mortality through most parts of these countries.
There are three public-friends coming out of these countries for England.
Robert Heaton`'s son will tell you of me.

And dear wife, know that you are often in my mind, and my soul is much concerned,
that though we be far separated,
we may be preserved every way to God`'s honour and our own comfort.
I earnestly desire you to take care of yourself, and not overwork yourself,
but let your desires be to God for my safety.
I hope we shall have gone through these countries by the end of this year,
and if we go not for Barbados, may endeavour for England.
I have been under some deep exercises about going to that Island,
and I hope the Lord will clear up my understanding, if it be my place to go there.
Remember my love to Friends in general, but especially to Friends about town.
I pray God you may all be found in those things that make for peace,
and that love may abound among you as one man,--that you
may keep dominion over all that which is of another nature,
and fret not yourself too much at evil doers,
nor say in yourself you will let every one do as they will;
for evil doers to whom the Lord has offered help, and who will not mend their ways,
will grow worse and worse.
Yet my desire is that God will raise up a people that will love the Truth.

Pray keep up your weekly meetings,
and advise Friends to feel God`'s goodness to fill their hearts,
so will you grow in your inward man.
Tell Richard Wilkinson not to let his mind out to
think of coming into these countries to live;
but if any young people be so warm, that they cannot be guided,
let them take their course, when you have eased your minds:
I doubt not but such will get cooled on their first coming here.
My mind is much concerned for brother Daniel and his wife,
that they may come up in their full duty and serve the Truth in the dominion of it.
My dear love to sister Margaret, bid her mind her latter end:
she has known my mind many years,
and has seen the Lord`'s hand that has been with me for my own good,
and for the good of my kinsfolk, and friends;
and that no weapon that has been lifted up against what I have stood for, has prospered;
therefore bid her walk in the Truth, and seek the enjoyment of it,
and keep out of society with such as are unsound in works and judgment,
so will the blessing of God be upon her.
My love to all my kinsfolks, and servants, and neighbours, as you see fit and convenient.
I desire you keep in patience in your troubles,
and be careful that the Truth suffer not in any case by us;
then as it has been and as it is, and as we have been and still are,
so we shall be blessed.
So my dear love, farewell!

[.signed-section-closing]
I still remain yours,

[.signed-section-signature]
William Ellis.

--

Aaron Atkinson not feeling his mind easy to leave Virginia
when William Ellis believed it right for him to go forward,
they separated; and soon after parting,
Aaron Atkinson was attacked by intermittent fever, as noticed in the following letter.

[.embedded-content-document.letter]
--

[.letter-heading]
Aaron Atkinson to William Ellis.

[.signed-section-context-open]
The 5th of 5th mo. 1698.

[.salutation]
Dear Friend;

Right glad was I to hear from you; your care and love to me are great I must needs say,
and you have quitted yourself of me like a companion indeed.
My dear friend, I have been very much out of order since you left me; for the most part,
my fit returns every other day; I can walk about on my easier day, but I sweat extremely.
I forced myself one day to the meeting and was refreshed,
but lay almost all the week following keeping my room,
and came downstairs but once I think that week.
I am so weak in body that I do not know that I am able to ride two miles.
My dear friend, though the Lord has been pleased to afflict me,
yet I believe it is not in his wrath;
I am not sensible of any occasion given by me that has justly brought it upon me.
So far as I can see, it is the Lord`'s will to stay me for a season,
it may be for some service that I see not the end of, blessed be his Name,
and his holy will be done forever.

I am now at John Woodson`'s, the doctor'`s, and have been near three weeks;
there is good air, and he is very kind,
but all medicine is in vain for ought I am sensible of, as to putting away my distemper.
My dear friend, as there is no likelihood of my coming seasonably to you,
I fully and freely give you up to answer what the Lord requires of you,
and to go on as soon as you find freedom.
Give me freely up into the hand of the Lord, for he is sufficient for me.
It rests still with me to visit those meetings I told you of.
I shall be glad of my health, but I must wait the Lord`'s time.
My dear love to Samuel Galloway, and his wife and children,
and all other friends that ask of me.
These are with true love to you,
and sincere cries to the Lord to be with you to the end of your days,

[.signed-section-signature]
Aaron Atkinson.

--

The following anecdote is from the journal of Thomas Story,
who became much interested in the salvation of the negroes
when on a religious visit from England to America,
and travelling in North Carolina in 1699.
Speaking of some coloured men who attended the meetings of Friends, he says:

[quote]
____
I had inquired of one of the black men, how long they had come to meetings; and he said,
they had always been kept in ignorance, and disregarded,
as persons who were not to expect anything from the Lord, till Jonathan Taylor,
who had been there a year before, in discoursing with them, had informed them,
that the grace of God through Christ, was also given to them,
and that they ought to believe in, and be led and taught by it;
and so might come to be good Friends, and be saved as well as others.
Of this they were glad; and on the next occasion,
which was when William Ellis and Aaron Atkinson were there, they went to meetings,
and several of them were convinced.^
footnote:[See the Life of Thomas Story, 8vo. Ed. 1786, p. 115.]
____

Thomas Johnson, to whom the following letter was addressed, died at Richmond,
in Yorkshire, in 1710, aged about 73 years.

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Thomas Johnson

[.signed-section-context-open]
Maryland, the 22nd of the 5th mo. 1698.

[.salutation]
Dear Friend, Thomas Johnson;

After my dear love to you,
by this know that you have come into my remembrance of late time,
as also have faithful Friends about where you live,
and therein has my heart been comforted.
My heart has been often gladdened since I saw you,
that I lived to see an end put to the great trouble that
has been so great a hurt and sorrow to Friends about you,
for so many years, and that love was like to come up among you; and in order to that,
my hearty desire is,
that whatever has been spoken or done by any that was not according to the Truth,
let all be buried in the land of forgetfulness,
and the very root of all discord be taken out of all hearts by the Spirit of Truth.
And if you, or any honest Friends know anyone that is not come to this,
labour truly with such in the love of God to overcome it;
and it is my hearty desire that the goodness of God may
increase among you and through your whole monthly meeting.
And I wish that every one may call to mind the Lord`'s
goodness that broke forth many years ago,
and his glory that shined through his faithful servants, to the affecting of your hearts,
and to the uniting of your souls together, by which you were made strong for God,
and strong to help your brethren; and if it be found upon search, that there has been,
or is to this time, any loss of strength, or dimness come over you,
or any lack of the breaking forth of that former beauty
and comeliness that I am sensible came over your meetings;
I desire that all who are sensible thereof may labour before the
Lord to have those things restored and brought up again.

And dear friend! labour thus with your whole heart,
to stir up Friends to love and good works; and persuade all Friends to walk in the Truth.
Oh! the sweetness of it has comforted my heart above twenty years;
and it is as sweet as ever it was,
and abounds to all that love it with their whole hearts: it is still so good to my soul,
that though I be concerned to leave all, and to travel into these deserts for his Name,
yet all is too little that I can do for Him.
My soul is comforted at this time; blessed be his holy Name forever and ever.
I desire you to remember my love to your Friends, and to Friends at Masham,
and in Wensleydale.
There will be a brave people thereabouts if they keep in the Truth.
With true love to you and all yours,

[.signed-section-closing]
I remain your real friend,

[.signed-section-signature]
William Ellis.

--
