== Chapter VIII.

Notice of John Field--Letters from John Field to Alice Ellis--and from Aaron Atkinson
to William Ellis--On the Payment of Ministers--Letter from William Ellis to his wife--Notice
of Daniel Gould and letter from him to William Ellis--Notice of John Bowstead and letter
from him to Alice Ellis--Letter from William Ellis to John Wynn.

John Field, the writer of the following letter, was the author of several short essays,
some of them controversial:
he was likewise the editor of the fourth and fifth parts of "`Piety Promoted.`"
He took a deep interest in the welfare of the Society of Friends,
and died at Hammersmith near London in 1723, aged 75.

John Field to Alice Ellis

London, the 26th of the 9th mo.
1698.

Loving Friend, Alice Ellis;

I have received a letter from your husband, dated the 13th of the 5th mo.
last, in Maryland, wherein he desires me to write to you,
and to let you know that his dear love is to you and to Friends;
and he signifies that he has been out of health, at times, but kept travelling;
and the Lord has helped him wonderfully;
and in three weeks or thereabouts he intended to be in Pennsylvania.
And my desires and prayers unto God are, that he will be with him,
and that the angel of his presence may attend him,
and that by the Lord`'s counsel and in his wisdom he may be ordered,
and may order all things to the Lord`'s glory and his people`'s comfort and edification;
and that you and he may be preserved near to God and in his fear;
that you may enjoy his blessing: and that you may know him to be to you as a husband,
which I doubt not but it will be the case, as you are so preserved unto the end.

And, dear friend! let me say, although unknown to you,
It is certainly our duty and interest to be freely resigned unto the will of God,
in what state or condition, or under what exercise or affliction he may allow us to be;
and to that end we ought daily to wait on him and to pray to him,
and be found in the faithful discharge of our duty;
and then he will not fail to extend his goodness and renew his mercies to us daily;
but he will be near to us and comfort us under all the afflictions that may attend us,
and will sweeten them to us.
And although the Lord has concerned and employed your husband in his work,
and honourable service in countries remote, he is able to preserve him and you,
and by his good Providence so to order it as that you may
see and enjoy one another again to your mutual comfort,
which I truly desire.
So with my kind love to you and Friends,

I rest your truly loving friend,

John Field.

Aaron Atkinson to William Ellis

The 1st of the 10th mo.
1698.

Dear William Ellis;

My true companion, whom my soul loves; you are often in my remembrance,
and the thoughts of your true zeal to God`'s everlasting Truth, in every appearance,
is comfortable to me.
Our dear friends, Edward Shipping, Richard Easton, and Daniel Sakra, are well,
and their love is to you.
We four have been together to the east, and have had a blessed time among them,
both as to good weather, and service for the Truth.
We had fifteen meetings beyond Salem.
Oh!
I can truly say, the Lord`'s goodness was plentifully handed forth among these people.

Dear friend!
I cannot freely come from this place straight to you to Rhode Island,
by reason of a concern that is on my mind to go to Scituate again, and from there,
either to Sandwich or to John Tucker`'s; I cannot yet tell whether;
but I hope I shall find freedom to omit Sandwich, and places that way, to Sunnycane,
and so come to John Tucker`'s, and have three or four meetings thereabouts only,
and one at Joseph Wanton`'s as I come to Rhode Island.
So I shall leave you to your freedom in the Lord, whether you will visit the main,
and go on to Long Island with H. C. or stay and rest your body till I come.
My love in the Truth to honest Friends.
Dear friend! be not discouraged in yourself, for you have a good service for the Lord.
Your solid weight reaches to the consciences of many,
and makes some shake the head when they know not what to say; or only to say,
He is a true man.
With true love to you,

I rest your real Friend,

Aaron Atkinson.

Although the Society of Friends bears a decided testimony
to the practice of taking money for preaching,
under the conviction that such a practice is opposed to
the precept of Christ respecting authority from him to preach,
"`Freely you have received; freely give;`" yet,
according to the circumstances in which it was said,
"`The labourer is worthy of his hire,`" they entertain the travelling
messengers of the Gospel hospitably and free of charge,
and likewise generally provide for the payment of their travelling expenses.
In some instances, however,
their ministers have thought it best to pay their own travelling expenses,
and in this respect also, to "`make the Gospel of Christ without charge.`"
This seems to have been the case with William Ellis,
in order that he might "`cut off occasion from them which
desired occasion,`" as appears by the following letter.

William Ellis to His Wife

Chester County in Pennsylvania, 1st of 11th mo.
1698.

Dear Wife;

After my true and unfeigned love to you, by tins know,
that I received your letter with great gladness, and am glad you are well every way,
for my desires are answered on that account, and that all Friends are well,
and of the establishment of the meeting of ministers at Settle.
And I pray God that all Friends concerned may wait in God`'s counsel;
and that the service may be really answered for which the meeting is intended;
and that all may help in that which makes for peace and comfort.
I have had several kind letters from London that have comforted me.
Now as to my travel, I shall give you an account as follows:

Since I wrote to you in the 7th month, I have been in New England,
where I have travelled with much difficulty, being very weak in body; yet this I can say,
The Lord has wonderfully assisted me, and in my weakness every way,
he has made known his strength; and through the various tempers of men`'s spirits,
he has made way for me,
and opened my heart to go through such exercise as fell to my lot; and in various places,
the cold-minded are warmed, and the indifferent-minded stirred up,
and the mournful are comforted; and many begin to see the beauty of Truth,
and are of a mind that I love, that is, to live nearer the Truth than they have done.
I came back here about three weeks since; and the Lord`'s goodness fills my heart,
and my spirit comes up over most of things that have bowed me down;
and I think my mind grows easy and full of gladness in my goings on,
so that I hope in this condition I shall set my face for England again.
Aaron and I parted in New England, for our exercises were heavy and days short.
It was by free consent, and he is not yet come here.
I hope I shall be ready to take ship in the First Month;
and I am likely to have a fine company of Friends.

Likewise further know, that you are often in my mind,
and I cannot express my care for you.
Sickness has been so much upon me, that for a time I could not see through it;
but my heart was much bowed, and you were much in my mind;
and I saw such exercises that were likely to attend you if I was removed,
that my very soul melted in me, in that love I have to you.
And now the Lord that tries the hearts of men, and comforts the bowed down,
has restored me again;
and I am now as cheerful in body and mind as I have been for a long time.
I also accept of Friends`' love in general; and as to my men,
I take it kindly that they remember me with love; and I wish they may take it kindly,
that I wish their welfare, and that my fervent prayers are for their safety out of evil,
and that they may devoutly serve the Lord in their day.
I kindly accept of Richard Wilkinson`'s love, and his wife`'s,
whom I have loved many years;
but I should have been much more glad to have had a few lines from his hand.
I wrote to him and to John Tomlinson, and Thomas Stockdale,
of some things that were in my mind; I hope they have got the letter by this time.
I wrote to Friends of Settle Monthly Meeting,
because of the true love that is in my heart.
My love is to all my kindred, and there is sometimes sorrow in my mind,
that they will not believe that God has given his good Spirit to them, that +++[+++if accepted]
will open to them the earnest of the pleasure of God`'s kingdom.
I would gladly have heard if any had been added to Friends.
You say nothing of the death of George Myers; it is reported so here,
but I cannot believe it; if he be not dead, mind my love to him,
and to John Hall and his wife.
Every time I think of John Hall it is a comfort to me that he has left his inn-keeping.

Advise Friends to live in love and to be all of one mind,
and then will peace and quietness abound.
I cannot express the good I had by Adam Squire`'s letter; tell him I say not much,
but my deep desires are that he may be safe from the hurtful things in this world.
If Simeon Wilkinson be set up, bid him set Truth before his business;
tell him it has been his master`'s way so to do, and the Lord shows mercy to him.
Tell Friends to show mercy, but before that,
that true judgment be kept up in your meetings.
Advise sleepers to awake and come to judgment while time is.
My love to John Wade who has shown kindness to me for the Truth`'s sake;
I hope the Lord will show kindness to him in a needful time.
Remember my love to Friends of Bentham Meeting; tell them they are often in my mind.
My love to Friends of Settle Meeting, and Salterforth Meeting.
My love to all my men, and if Christopher Tatham be gone, bid him think of my advice;
I know it will be to his profit; he is, or may be sensible of my care and love to him.
In your affairs see that the widows and fatherless be not neglected;
on these accounts I have said most that may be needful at present, only this;
be sure you do not overdo yourself in business; that if it please God we meet again,
it may be to our ease and comfort.
Further know, that I have travelled through these countries, and Friends are very kind;
but I have not laid my hands on one penny from Friends, to defray my charges with,
though I have often had it offered.
So if any upbraid you therewith, and say that I have left you,
in order that I might get money, tell them in the name of the Lord, that it is a lie.
So with true love to you, wishing we may live sensible of the great mercy of God,

I rest your truly loving husband,

William Ellis.

The following notice of Daniel Gould, the writer of the subjoined letter,
is extracted from the "`Record of the deaths of Friends and their children,
of Rhode Island Monthly Meeting,`" page 24:--"`Daniel Gould, aged near ninety years.
He departed this life at his own house in Newport on Rhode Island,
the 26th day of the 1st month, 1716,
and was buried in Friends burial ground near our meetinghouse,--who
bore a faithful testimony for the Truth he professed,
both in suffering many stripes at Boston, with frequent testimonies in public,
and finished this life in a full assurance of life eternal,
which he signified on his deathbed,
and encouraged all to believe and walk in the same Truth.`"

Daniel Gould to William Ellis

The 1st of the 11th mo.
1698.

Dear William and Greatly Beloved!

For the soundness and savouriness of your spirit,
and the sweet savour you have left behind you, many have you in good remembrance,
and would be very glad to see you here again.
If the Lord should so order it, your pruning hook, I hope, will do good among them,
for skilful vine dressers are precious,
who first have a discerning between the necessaries and the superfluities,
and then cut with an even hand; and the trees that are saved shall bless the pruner.
My love to Friends wherever you go, that have a remembrance of me;
and I would also have them remember their first love,
that they keep it and grow in the simplicity thereof;
this will warm and comfort their hearts, being knit together in love.
So with my hearty and true love to yourself and Friends where you come, Farewell!

Daniel Gould.

John Bowstead, the writer of the following letter, was a native of Cumberland:
he joined the Society of Friends when young,
and became a laborious minister among them.
He died in 1716, aged 57, and was buried at Scotby near Carlisle.
See Piety Promoted, Part VI.

John Bowstead to Alice Ellis.

Bainbridge, in Wensleydale, 9th of 11th mo.
1698.

Dear Friend,

You have often been in my remembrance since your dear husband
was drawn from you into the Lord`'s service beyond the seas;
where I understand the Lord has blessed his labours with an acceptance and good success;
and seeing it is the Lord`'s own doing in separating your dear husband from you,
I do not doubt but that the Lord that has made you willing to give him up,
will also sanctify your exercises to you, as you keep in his pure fear;
and as he that was a blessing and a comfort to you when present,
was so made to you by that hand which separated him from you for his own Name`'s sake,
so whether he live or whether he die,
he is the Lord`'s. And he that has blessed you together,
can also bless you when asunder for his Name`'s sake, and make good his ancient promise,
that he would be a father to the fatherless and a husband to the widow.
I write this in love to you, as knowing that your husband is a man of God,
and has served him fervently and faithfully in this his glorious day;
and may He that blessed him, bless you too, is the fervent desire of your true friend,

John Bowstead.

John Wynn, to whom the following letter was addressed, resided at Bradford, in Yorkshire,
and was a minister much esteemed among Friends:
he is mentioned in page 24 of this volume, where there is also a letter to him,
and there is a Testimony respecting him in a subsequent chapter.

William Ellis to John Wynn

Philadelphia, the 28th of the 11th mo.
1698.

Dear Friend,

Whom I have dearly loved many years, because of your love to the Truth;
nor could that lurking spirit that privately goes
about making itself busy in other men`'s matters,
under the pretence of building up the Church,
take hold of my mind to lessen you in my esteem;
for I know its end is to break the unity of brethren, let its pretence be what it will.
And know, that though I be far off, yet you have been often in my remembrance to comfort;
because I have a sense, that you would stand by my poor wife in any right thing.
And further, know that I have gone through great exercise in body,
and sometimes I have questioned my being taken away.
I have had sore sickness in New England, but the Lord,
that always comforts the distressed, has helped me.
Likewise the weight of what I am here about, has been weightily upon me; first,
that I might be kept to the Root,
from which I have ever been supplied with virtue and life to perform my duty;
and as I have been under danger of dryness possessing my heart,
I being so often under exercises in public and great meetings,
it has the more humbled my mind in secret;
and my heart and soul are thankful to the Lord,
that he has grafted that daily care in my heart,
to supplicate him daily for new supplies; for I see this is the way to keep down pride,
and conceitedness of men`'s own works and doings,
to be better than other men`'s. I see little to boast of unless it be weakness,
as without the help of the great God we are but men;
and as I have travelled in the sense of these things,
the Lord has wonderfully assisted my spirit,
so that I have been filled with might and power to the awakening of the indifferent-minded,
and hypocrites, and double dealers;
and to the comfort of such as mourn and have been ready to say, as Zion said of old,
"`The Lord has forgotten me.`"
O, the sweetness of the Truth, and the joy of it,
that has often filled my heart! it has made me to cry aloud,
and not to spare my strength in the congregations of the Lord`'s people:
and my prayers are, that through all services and attainments,
my soul may be affected with the sweetness of that life by which my strength is renewed;
for I am much of a mind that those who abide here will never be moved.
When we went to New England our exercises were such,
that we thought it best to separate by free consent;
showing the reason to some honest Friends; and it seemed good in their eyes;
so I have but once seen Aaron Atkinson since.
And finding my body fail, I had a mind to come here with what speed I could,
visiting Friends as I came; and I have been here about three weeks, waiting for Aaron,
expecting him every day, or to hear from him.

Now, know that I find my mind much eased, and in a little time,
hope I shall be easy to leave these parts; but Aaron being so long sick in Virginia,
he has yet West Jersey, Pennsylvania, and many Friends in Maryland to see;
so that I begin to doubt of his company home, though I should gladly have it;
but as far as I can see,
I hope I shall be easy to return to England in the latter end of the First Month,
or early in the Second.
And if the Lord show me favour, to bring me safe and right and clear every way,
it will make my heart glad; and to see my old friends in England again,
whose love has always been firm and true to me in my exercises.
My dear love to your wife and daughter; I wish she may grow sensible of the life of Truth.
My love to my dear wife whom I am much concerned about, for her safety every way,
and that she may be preserved out of the reach of the enemy,
and the hands of unreasonable men.
My love to all true-hearted Friends wherever you come,
and if any inquire of news from far,
tell them that the Lord is at work to make Zion a compact city, and build up her walls;
and the Lord is bringing back the captivity of his
people that they may dwell in the midst of her:
glory and honour and everlasting thanks be given
and sounded forth to his worthy and glorious name!

This is from your real friend,

William Ellis.
