== Chapter X.

Letters from William Ellis to Theodore Eccleston, William Edmundson,
Richard Johns--Notice of John Haydock--Letter to Samuel Galloway and others--to William
Ellis from Gilbert Thompson--Notice of Richard Hill--Letters from John Tomkins,
and William Edmundson.

The letters in this chapter relate chiefly to the services of William Ellis in America,
and to his return from there.
They also contain much excellent counsel.

William Ellis to Theodore Eccleston.

Airton, the 3rd of the 5th mo.
1699.

Kind Friend!

This with good wishes for the increase of peace and love among the brethren,
comes to let you know, that I got well to York, and met with my wife,
and many good Friends from various other parts, as well as our own county;
and a great meeting there was, and love, peace, lowliness, and submission one to another,
seem to increase and abound among Friends.
Friends seem to be more closely united than in some times past;
and Church discipline goes on well,
and a great number of young Friends come up in public testimony; and it seems in my eye,
as though there is to be a new plantation here,
or as though Lebanon should bring forth new stems again from the old roots.
And I pray God Almighty, that all such as are overseers of this forest,
where the goodly cedars are to grow, may daily walk there with their sharp axe;
and that every superfluous branch may be so cut off as that
the tree shall take no harm in the place where it is cut;
but that all may be truly pruned and dressed, and that the locusts and caterpillars,
and earth-worms, may be taken away,
so that sap may spring from the root into every branch;
then both green leaves and good fruit will grow,
and the sound of the going of the Lord will be heard there,
as the wind among the mulberry trees.
I cannot enlarge, yet you know what I mean.

Now as to the books that are to be sent to New England, I was too short about them,
but you may know, that I thought three of George Fox`'s Journals, and divided thus:
to Hampton Monthly Meeting, one; to Salem Monthly Meeting, one;
to Scituate and Sandwich Monthly Meetings, one; and order Friends,
that the books go to and fro, that all may have the benefit thereof;
and John Tomkins`'s book,
entitled "`The Harmony of the Old and New Testaments,`" would be of great service thereaway,
as they show to the world that we own the Scriptures;
for the dark Presbyterian priests labour to persuade the people that we do not.
Pray follow this thing closely until it be perfected; in so doing you will ease my mind.
My hearty desire is, that peace and love may abound among you,
and that you may go on closely together,
to put away the cursed thing out of the camp of God:
and that nobody run one against another, but all against that which is naught;
and that as fathers nourish their only sons,
whom they intend to possess their inheritance when they are gone,
so ancient Friends may show kindness and true respect to the young;
and young men as sons, show due respect to such as were in the Truth before them,
and rule well, not by constraint only but of a willing mind.
God Almighty did not call us from the ends of the earth, where the devil had his walk,
that we should be broken in pieces again, either by the riches or the glory of the world,
nor that the glory that is in the Church should be tarnished; therefore with all speed,
labour to quench all heats,
and keep your bucket always full of water to quench them with;
and let everybody be afraid to think or speak hardly one of another;
it will not be as it should be till it be so;
for by thinking and speaking hardly of others,
we may justly provoke the Great God to think of our past doings,
and to bring them to our remembrance, in a way which will not be to our gladness.

As you have always taken patiently what I have written to you, so do so with this;
for it is the remainder,
or part of what I spoke to you on the morning that I left the city.
Such has been my trouble, at times, since my return,
that I could hardly keep it out of my mind; for there had like to have been sad work,
before I got here; but the Lord who delights to replenish Zion with peace,
and to give prosperity upon her borders, has helped, and things are now settled;
and I am greatly glad thereof.
My wife tells me of your kindness to her, and we together acknowledge it.
With true love to you and yours, and to Friends,

I remain your real friend,

William Ellis.

William Ellis to William Edmundson.

Airton, the 3rd of the 5th mo.
1699.

Dear and Much-esteemed Friend;

After the remembrance of my unfeigned love to you, by this know,
that I thought it fit to give you an account of the affairs of Friends beyond the seas.
After we landed in Maryland, we travelled into Virginia and Carolina,
where we found several ancient Friends alive, as James Hill`'s widow and Francis Tomes,
who inquired respecting you;
and it filled their hearts with tenderness to hear you were yet alive,
and able to labour to promote the Truth.
Many young people there are, and great brokenness among them:
also several negroes come among Friends at times;
and the Lord`'s hand is at work on them, and many are lately convinced there.
About Chucatuch there are many Friends;
and several are under exercise that Truth may increase;
but there is too much indifference among some.
We had hard exercises thereaway, but the Lord helped us greatly.
One Thomas Paidge is a public minister there, and in my sense Truth increases in him.
There is a convincement in those countries.
Many ancient Friends are dead in Maryland,
yet there are still good serviceable Friends left, if too much riches do not hurt them,
and too much finery the young people.
Friends are under exercise to bring things to the standard that tries all things.

In Pennsylvania things are indifferent well, and Truth prospers,
and that trouble which George Keith and his party made,
has turned to the profit of truehearted Friends.
The Lord blessed my travels greatly among them; disciples increase;
it is thus also in most parts of West Jersey, there is little in East Jersey,
only at Shrewsbury; George Keith has mostly spoiled the rest, also at New York;
but Friends have got a meetinghouse newly built up:
William Bickley and John Rodman are there.
In Long Island there is an increase, many being convinced about Flushing.
John Bond`'s son is a public preacher, and the Lord`'s goodness is to that family.
Banters grow weaker than they were.
We had good service as we passed by land towards Rhode Island:
the Lord`'s goodness is to those parts.
The Lord made my service prosperous in Rhode Island; but I had hard exercise at times:
a good people there is,
but they have been too much overruled by some that were too indifferent;
but as my understanding was opened, so I laboured, and Truth broke through,
and Friends brought judgment over things that had been amiss,
in the management of their affairs, and love greatly increased among old and young;
and the Lord`'s goodness filled our hearts at parting.
I thought it was worth my labour, if I had gone from England on purpose only for that.

New England has been in a low condition; but in my sense,
the Lord is about to break forth upon Friends,
and in various places several are convinced, as about Hampton, Salem, Scituate, Sandwich,
Spicam, and Portsmouth.
There is little exercise in black Boston, yet a seed remains,
and as it was in my mind to see Friends thereaway,
so it was in my mind to labour with the ability I had day by day;
and many straits I was in, and great need I saw I had both of power to carry me through,
and of wisdom from God, to guide my tongue;
and under the sense of my need of these things, I was brought very low,
and into great straits; for I thought I had often seen the mad work that men had made,
who put their wits to work when the Lord did not answer their desires.
But though it was the Lord`'s pleasure to deal thus with me,
yet I kept my dependence more upon him;
and in needful times he did eminently appear in life and wisdom;
and when in deep engagements with the power of darkness, he brought me off with victory,
his great power triumphing and having greatly prevailed.
Thus was my travel mostly from one place to another, with great fear,
lest when I was somewhat eased, I should say, Well done, to myself;
also I had much weakness of body mostly through my travels,
yet it is the crown of all my comfort, that that Arm which first reached my heart,
did and does, as it is joined with, help to tin`'s day;
and inexpressible comfort has filled my heart at my return to my own country again.

Many Friends inquired of your welfare,
and were glad to hear of your constancy to the Truth in your old age.
Where I thought it might be of service,
I spoke of the Lord`'s great goodness to your nation;
and it gladdened faithful Friends to hear of it,
and especially those of your own country.
I had thought to have got to the Yearly Meeting at London, but cross winds hindered.
I stayed not long there; but it may be I may go again,
for some things are in my mind to tell Friends of,
that may help forward the work of Truth.
I came to York at the time of the Yearly Meeting; and a great meeting it was;
and great peace and love, and condescension for good there was one to another;
and the work of reformation in many hearts, houses and habits goes on;
and many are raised up of late both into public service,
and to help forward good rule and order,--many that I hope will be mighty men for God,
if humility be kept to.
This is needful to be preached among us now-a-days.

Many Friends think and speak often of you hereaway,
and bless Almighty God that cast your lot among us.
And when I considered, and saw things work to my content, I said in myself,
that the child yet unborn will have cause to bless the Lord on account of those visits.
!Now as to my wife, she has been well borne up,
and things have answered as to the outward;
she has answered her own part and mine too in a great measure;
and the Lord has taken in hand to be master among my servants; so that in my sense,
they much more fear the Almighty than when I left them.
I saw some Epistles in London;
I wish we could have a hundred or two of them in our parts;
if they be not free I would pay for them myself.
If it seem good to you, you may get a friend to draw two copies of this letter,
and send one to Joseph Pike and Samuel Randal, and the other to Amos Strettel.
It would be acceptable hereaway to have a few lines from you;
also if you find anything in your mind that might be of service to us,
write to me or to anyone else you know,
and I think we will do our best to answer your will,
in putting in practice the doing part.

One thing more I think good to let you know,
that we have got a meeting of ministering Friends once a quarter,
in Settle Monthly Meeting, and being but young in such weighty affairs, I know good,
sound Friends`' company would be very acceptable to us whether in person or by Epistle.
That you think often of us, and pray for our safety,
is the earnest desire of him who intends, by God`'s help,
to labour in my measure to promote peace and Truth in my day;
and to live nearer the mark than I have done to this time.
My wife`'s dear love is to you, and she is cheerful.
Loose professors of Truth have warred sore with her;
but her arm is made strong by the Truth, to contend for it,
for which my heart is melted with thankfulness to God,
that has showed such great mercy to us.
I have written a deal, but could not easily compress it into less compass, else I would;
and yet I have given but hints of tilings.
So with true love to you, your wife, and all Friends where you think fit,

I remain your truly loving friend,

William Ellis.

John Haydock, who is mentioned in the following letter,
was born in the parish of Standish, in Lancashire, in 1640.
He joined the Society of Friends in 1667,
and a few months after was committed to Lancaster Castle,
a prisoner for the testimony of a good conscience: here he was detained four months.
Soon after his release he received a gift in the ministry,
in the exercise of which he travelled much in Great Britain, Ireland and America.
He suffered much persecution,
with spoiling of goods and imprisonments for righteousness`' sake,
and died a prisoner in Lancaster Castle, for his testimony to the Truth, in 1719,
aged 79 years, having been a minister about fifty years.--See Piety Promoted, Part Vn.

William Ellis to Richard Johns.

Airton, the 31st of the 5th mo.
1699.

Dear Friend,

Whom I truly love for the Truth`'s sake; my true love is to you and yours.
As God Almighty in mercy has blessed you, in basket and in store,
and has opened your heart to serve his servants with a willing mind,
my soul desires that in like manner his goodness may come upon your posterity.
Likewise I know that God has blessed you with a good understanding, and sound judgment,
and has opened your eyes to see a comeliness in his Truth;
and you see in a good degree what makes for the honour of it, and what makes against it.
Now my hearty desires are, that you may arise like a man of war,
to help the weak and the feeble-minded, and to draw water for the thirsty,
and to drive out all that would hinder the arising
of living water in the Church of Christ.
I know you are a man spirited for such a work,
and am persuaded that the Lord will bless your endeavours;
for I know it is God`'s mind it should be so,
that nought should abide that hurts in any member of the body.
I fell short of the meeting at London, but got to York to the Yearly Meeting,
and account was given of great reformation mostly through the county, in many things;
and of many being raised up lately to publish the Truth,
and the Truth has shaken the whole county in general; the Lord go on says my soul.

Stir about now and then, and see how Friends meet on week-days;
and when your spirit is full of life and sweetness,
if you drop a word or two among Friends, I do think it will be to profit.
Stephen of old did so, though his office was to take care of widows;
and if such as be public ministers stir about from one place to another,
and drop a few words in the sense of life,
it will help to strengthen them that may be weak, and to comfort the mourners.
My true love to Friends beyond the Bay;
I wish that love and charity may abound among them; tell them that although I am here,
my thoughts j are running to and fro among you and them.
Help forward the good work that is begun:
put Friends in mind to visit John Lewis`'s meeting now and then.
I was with John Haydock lately, and he was glad to hear of you and of your welfare.
I hope you will not be offended with my thus writing; you know it is not for self-praise.
This with my true love to you and yours, and all Friends everywhere where you come;

I rest your real Friend,

William Ellis.

William Ellis to Samuel Galloway, Solomon Sparrow, William Rix, Samuel Thomas, etc.

Airton, the last of the 5th mo.
1699.

Dear Friends;

After my dear love to you and yours, know that I got well home,
and I find things every way well.
Where Friends keep out of the earth, and abide in the love of God,
they go forward and Truth prevails.
Know hereby that I cannot forget you, though I am afar off, but I pray for your welfare,
and that Truth may prevail and gain ground among you;
and in order thereunto I would give a word of counsel unto you.
Inasmuch as many ancients are gone to sleep with their fathers,
and the oversight of the church in those parts is likely to fall upon you,
with others of your brethren, and God has given you a large portion of his Spirit,
which opened your understandings to discern things,
and has given you judgment to divide between the precious and the vile,
I beseech you with, all diligence, put your hands to the work, in the Name of the Lord;
whatsoever is against the Truth in the heart or house, or in traffic,
spare not to advise against it, and let it be done away; and my desire is,
that your brethren may arise with you to the work of the Lord;
and when you divide between the precious and the vile,
let it be with the Word of the Lord, the sword of the Spirit;
that sword which is of tried mettle, whose edge cannot be blunted;
nothing it can meet with shall be too hard for it, and it is very piercing.
Those valiants of old time who handled this sword, gave this testimony of it,
that it was quick and powerful, and sharper than any two-edged sword,
piercing even to the dividing asunder of soul and spirit, and of the joints and marrow,
and it is a discerner of the thoughts and intents of the heart;
this is the weapon of the saints`' warfare;
let us see that by the power and operation of this Word,
our own hearts and houses be cleansed;
then will you be able to answer the mind of the Lord in his will concerning others.
By this Word, true judgment will be laid to the line, and righteousness to the plummet,
and judgment will be executed upon all that is contrary to the will of God;
even upon those evils also which may be covered with a specious pretence.
Remember how Samuel of old time hewed Agag in pieces before the Lord in Gilgal.

Dear Friends, go on in the Name of the Lord, and do his work faithfully,
preferring that to your own profit and advantage in this world.
What does it signify,
if because of your attending upon the service of God you
do not grow so rich in this world as some of your neighbours,
who mind only earthly things,
or if you cannot lay up such earthly treasure for your posterity as many others do.
Let me put you in mind, that you have the word of our great Master for it,
That every one of you that forsakes, or that has, forsaken, houses, or brethren,
or sisters, or fathers, or mothers, or wife, or children, or lands for his Name`'s sake,
shall receive a hundred fold in this world, and shall inherit everlasting life.
Besides the Lord has said, Jer. 49:11. "`Leave your fatherless children,
I will preserve them alive, and.
let your widows trust in me.`"
Is not this encouragement enough to all to trust in the Lord?
Take heed and watch against that spirit that would lead into a foolish pity, saying,
spare this thing and spare that thing, and be tender to all,
though it be to that which displeases God.
I never saw that spirit work for the Truth; therefore I advise you, keep judgment,
and in true love, work closely for the Truth;
and whatever is against the Truth indulge it not; and such as excuse themselves,
that they see no evil in things that are evil in themselves,
labour to convince of their ignorance, in the spirit and love of our God,
that they may be helped out of the snare of the enemy.
And those who are tender and well-minded, I beseech them,
when they come to see things are not right, to submit, and lay those things aside,
for Truth`'s sake,
and for the sake of that precious unity that is in high esteem in the eyes of a remnant.

And, dear Friends, labour as true watchmen,
that all your meetings be kept in the Name and Power of our Lord Jesus Christ,
and that all dulness, dryness, and that which tends to death and bondage,
may be absolutely banished out of your assemblies,
and that the sweetness of life may arise and come up in your assemblies,
and that all uncomely behaviour in meetings may be testified against in the love of God;
and some of you now and then step down to Potomack,
and sit among that poor people there;
you may comfort their hearts even if not a word be spoken to them;
and run over to the Bay now and then, sometimes one and sometimes another of you,
and take some of your public-friends with you;
and if you visit them from meeting to meeting,
I believe the Lord will accept this service at your hands, and will say unto your souls,
Well done! and before you leave this world,
you may come to see the travail of your souls,
and be satisfied in the goodness of the Lord towards his people.
This is the real desire of your friend.
My dear love to all Friends where I have travelled;
and if you think fit to let them see this, you have my consent.

This is from your real friend,

William Ellis.

Gilbert Thompson to William Ellis

Sankey, the 3rd of the 6th mo.
1699.

Dearly Beloved Friend, William Ellis,

I gladly received yours, with the enclosed to William Edmundson,
which I purpose to transcribe, and take care to send it away;
I find no superfluous complement in it: I seldom or never find you err on that hand.
The love I now feel in my heart towards you,
and that rooted esteem which has had a bottom, these many years, and lessens not,
can afford you this compliment; that the remembrance of you tenders my heart now,
and at some other times; and your courage for the Truth, and success therein,
helps my droopings now and then; for I must confess, though the Lord be gracious,
and endues me with understanding, yet a doubting, weakly spirit attends me,
to my exercise: it makes me conclude that men of courage have a special advantage,
and lay more fast hold on faith, and thereby gain victory and keep a good conscience,
more than such as I do.
I would willingly be content with my station,
and sometimes feel desires to answer Truth in my capacity, and have sometimes hope,
that tribulation may work patience, and patience experience, and experience hope.
I would have you bear this simple expression, in which I magnify not man, but the Lord,
as some formerly magnified God in Paul; that in my thoughts you grow mightily,
set your candle on a candlestick, and excel in many things most of your brethren.
Proceed, and let nothing hinder you,
and though you may find the courage of a Hon in your engagements,
yet remember to exercise matters in the lamb`'s nature;
because it is the Lamb must have the victory;
and sometimes when others may screw a matter as high as can well be borne,
yet exercise tenderness, patience and forbearance,
and that will cross the expectation of some, who wait for your shooting of darts,
because the Lord has made you strong in battle.
I hope before long we shall see you and your good wife here,
and be comforted in your company.
In the mean time my constant true love is remembered, and in it I remain yours.

My wife`'s love is to you both,

Gilbert Thompson.

Richard Hill, who is mentioned in the following letter, was a native of Maryland,
and a useful member of the Society of Friends: he settled in Philadelphia,
and was twenty-five years a member of the Governor`'s Council,
and several times Speaker of the Assembly:
he also filled the office of Commissioner of Property, and was,
for the last ten years of his life, one of the Provincial Judges.
Proud in his History of Pennsylvania, Vol. I. page 478,
says respecting him, "`His sound judgment,
his great esteem for the English constitution and laws,
his tenderness for the liberty of the subject,
and his zeal for preserving the reputable order established in his own religious community,
with his great generosity to proper objects,
qualified him for the greatest services in every station in which he was engaged,
and rendered him of very great and uncommon value in the place where he lived.`"

John Tomkins to William Ellis

London, the 9th of the 6th mo.
1699.

Dear Friend, William Ellis;

I received yours dated the last of the last month, and am glad I can serve you;
therefore have, according to your desire, transcribed your Epistle to Maryland,
with what alterations I saw fit, as you desired me.
I hope it will answer your sense, and the drift of your spirit: I took care therein,
even in those places where I have enlarged.
If I have offended you, or pleased you, let me have a few lines from you.
I have put your Epistle into the care of Richard Hill, as advised in yours.
I am sorry for the present exercise you are under in respect to what you write.
I hope Providence will order it for your ease, and the safety of your person,
as well as the reputation of the Truth, which I believe you have regard to above all.
What else I can be serviceable to you in, you may freely require it of me.

This day at our Morning Meeting, our dear friend, William Penn,
took his leave of the brethren; he leaves this city the latter end of this week.
Indeed the glory and power of the Lord covered our assembly,
which united the souls of the brethren together, as were the souls of Jonathan and David;
and the faithful were bound up together in the bundle of the living.
In much tears, love and comfort, we enjoyed the presence of the Lord;
and in this were our supplications put up one for another.
A season that if you had been present,
would have comforted your heart! and I believe it will not be easily forgotten by us.
It was an evident visitation from God, in great love to us:
the Lord shall have the praise, it was his doing.
Our dear friend, William Penn, intends to take shipping at Southampton,
on the next Second-day come a week, for Pennsylvania.
With mine and my dear wife`'s dear love to you both.

I am, dear friend, your real friend and brother,

John Tomkins.

William Edmundson to William Ellis

Dublin, the 22nd of the 6th mo.
1699.

Dear William Ellis;

I received yours,
and am very glad to hear of your prosperous service for the blessed Truth,
and your safe return;
you and your service in those remote parts have been often
under my serious consideration since you took that journey,
with fervent prayers for your well-doing,
and the blessing of the Lord on your labour of love;
and I should have been more glad if you could have given me a good account of your service,
Truth`'s prosperity, and Friends`' steadfastness in it, in the Caribbee Islands, Jamaica,
and the Bermudas, where I had successful service for the Lord,
that may not be easily forgotten.
Friends have been visited this many years with great sickness, and many of them removed,
and the remnant that is left needs to be visited;
and very few have been with them in these times of their great affliction.
My service was great there; having been three times there;
and I hope I left them in a prosperous and flourishing state,
through the good hand of God that was with me,
and made things prosper on many accounts in the Lord`'s service.
But I am now too old for such journeys, so am the more concerned for them.
Truth`'s affairs in this nation prosper on all accounts,
and things in general are well among Friends;
the glory of the Lord shines forth more and more;
and his irresistible arm is with us in his work and in the service of this great
and glorious day of the restoration of all things into their proper places,
use and service, as they were created and ordained by the great and wise Creator,
and settled in harmony, before disorder got in.
This blessed work of a thorough reformation goes on, the Lord`'s power carrying over all;
and in his blessed Seed is counsel and wisdom, and it gives dominion:
his great Name is to be reverenced, praised and magnified forever and ever.
I gave your letter to Amos Strettel, who will take care to send a copy as you directed;
and I ordered him to send you some of those Epistles you speak of,
with some other papers that may be serviceable,
and I know will be acceptable to some among you,
that are concerned for the propagating of close Gospel order on a sound and right bottom.
I am very well through the mercies of the Lord,
who is large in mercy to me on all accounts,
and lengthens out his mercies as he lengthens out the days of my pilgrimage.

I am thus far on my journey to the north, to visit Friends,
accompanied by George Rook and some others;
and intend to be at their Province Meeting this week, and so on in Truth`'s service,
as the Lord opens our way and gives ability.
Mind my love to your wife and Friends about you, to Thomas Aldam, and Thomas Thompson,
when you see them, and to all honest, true-hearted Friends that desire to hear of me.
So with my love to you,
in the fellowship of the Gospel of our Lord and Saviour Jesus Christ;

I am your ancient friend and brother,

William Edmundson.
