== Chapter XI.

[.chapter-synopsis]
* Yellow Fever
* Notices of Thomas Duckett and Thomas Musgrave
* Letters from Nicholas Wain and William Fishbourn
* Notice of Roger Gill and his death
* Letter from Samuel Carpenter
* Notice of Edward Shippen
* Letter from Edward Shippen
* John Slack to Alice Ellis
* Letters from John Tomkins and Theodore Eccleston
* Notice of John Wynn
* Testimony of William Ellis respecting John Wynn

Several of the letters in this chapter describe the ravages of the Yellow Fever,
in one of its most formidable attacks upon the city of Philadelphia.
The sympathy excited toward the afflicted and bereaved,
and the solemn impressions produced by this visitation,
are dwelt upon in a manner which claims the serious attention of the reader.
Thomas Duckett, who was among the number that died of this disease,
visited England and Ireland as a minister in 1694.--Thomas Musgrave
had visited America as a minister from Yorkshire in 1694:
he appears now to have been going out as an emigrant,
and to have died on the passage along with many more,
from the unhealthy state of a crowded ship.

[.embedded-content-document.letter]
--

[.letter-heading]
Nicholas Waln to William Ellis

[.signed-section-context-open]
Philadelphia, the 22nd of the 7th mo.
1699.

[.salutation]
Dear Friend, William Ellis;

My dear love in the unchangeable Truth is unto you and your dear wife;
for in that does my soul salute you, hoping you are in good health, as,
blessed be the Lord!
I, my wife and family are at this present time.
This is a great mercy from the hand of the Lord; for since you left these parts,
we have met with great exercises,
and a great mortality has happened in the town of Philadelphia, and some in the country.
We may truly say,
it is an exercising time,--a time to drive many home to consider their standing,
and upon what foundation they are building,
and what they are building upon the Foundation;
whether it be that which will abide the fire, yes or no; for of a truth,
the Lord is trying his people, and it is a day of humbling.
But may we not honestly say as Job said, "`Shall we receive good at the hand of God,
and shall we not receive evil?`"
for as it is written, "`When the judgments of the Lord are in the earth,
the inhabitants of the world will learn righteousness.`"

So my dear friend, I am willing to give you a short hint of things,
and who they are that have laid down their bodies,
and of those persons we had great love for; our dear friends, Esther Hoskins,
Thomas Duckett, James Fox, Margaret Beardsley, her daughter Mary Gray, George Pox,
Thomas Smyth and his wife and son and son-in-law, William Harwood, William Alaway,
and several others that I name not.
My dear brother-in-law, James Dilworth is dead,
and was buried the First-day before our Yearly Meeting;
Charles Sanders and Stephen Coleman, and a great number of the world`'s people also.
Now, my friend, as touching our Yearly Meeting, it was but small,
by reason of the sickness;
but we may truly say the Lord our God made up our deficiencies;
for his living power and sweet refreshing presence was with us,
to the comfort of his,--whose hearts are true to him.
He is the same that ever he was, and as he was good to his Israel in days past,
so we may say, he is good to his Israel in this very day;
blessed be his holy Name forever and forevermore!
Our dear friends, Aaron Atkinson, Thomas Story and Roger Gill, were with us,
who were of good service there.
Our dear friend Aaron being very weak by reason of his sickness, was but little with us.
He was with us the Fifth-day following our Yearly Meeting,
and I do believe he cleared himself very well, to the satisfaction of several,
if not all, that were then present.

Now, dear William, I seeing a letter that came from you from London,
can truly say I was right glad, when I heard it read,
in which you remember your love to me, which I kindly accept.
My dear love is unto you and your wife once more.
I desire you to remember my love to all Friends that may inquire of me,
or to whom you think fit.
My dear wife desires to have her love remembered to your wife;
and we were right glad when we heard your wife was well.
My dear love to my sister, Ann Dilworth, if you see her,
and let her know that her dear children are well.
My son Richard desires to have his kind love to you and to your wife, though unknown,
and to his aunt Ann Dilworth;
and I desire you to remember my love to all our relations and friends in Bolland.
Sixty passengers died out of that ship which came from Liverpool,
some of them were Thomas Musgrave, Thomas Wilson, Henry Michel, Robert Driver,
and Grace Driver, but Grace died after she came here.
This from,

[.signed-section-closing]
Your friend and brother,

[.signed-section-signature]
Nicholas Waln.

--

Roger Gill, whose death is noticed in the following letters, was from London,
where he joined Friends about 1683.
While on a religious visit to America, in company with Thomas Story from Cumberland,
he was brought into great sympathy with those afflicted with the Yellow Fever in Philadelphia;
and he prayed fervently that the Lord would stay his hand, and that he would,
if it pleased Him, accept his life for the people.
Soon after this Roger Gill fell sick, and in a few days he died, in great peace,
aged 34 years;
and it was observed that few died of the disease afterwards.--See Thomas Story`'s Journal,
and [.book-title]#Piety Promoted#, Part III.

[.embedded-content-document.letter]
--

[.letter-heading]
William Fishbourn to William Ellis

[.signed-section-context-open]
Philadelphia, the 27th of the 8th mo. 1699.

[.salutation]
Dear Friend, William Ellis;

These come with the salutation of my dear love to you,
trusting this may find you well at home;
and I can truly say I am glad in the remembrance of you.
I hope you may find opportunity to let me hear from you.
Through mercy I am now indifferent well,
though I have lately been dangerously ill of a distemper
that has been very violent among us at this place,
and has carried off several of our Friends, I believe to their rest with the Lord.
The Lord, if it be his will,
sanctify to us that are yet spared this dispensation of his judgments,
and bring us all low and humble before him, into true obedience to his holy will! and O,
that we may have strength to serve him,
and walk worthy of his love and mercy! for I firmly believe he has,
in this the time of sore affliction, abundantly mixed mercy with judgment,
in taking away the prepared, that others may be humbled, and prepare to meet him.
The Lord knows, I often thank him in secret,
that he was pleased to visit me in the beginning of this sickness,
although it was very violent on me, and I was out of hope of recovery by many;
but the Lord in mercy raised me up again; and O, that I may walk worthy,
that I may make suitable returns to him for his love!
I thank the Lord, he has brought me a little lower than I was before;
and his love is now sweet to my poor soul; and I humbly beg of the Lord,
to bring me yet more and more into obedience.
Oh that I may serve him!
My soul has rejoiced, although in this humbling day,
that he has come to purge Philadelphia; for as I may say, he sat as a refiner`'s fire;
he has come near, even to the bottom of the heart, to cleanse it.
Oh!
I am thankful for my portion of this visitation, and so, I have great cause to believe,
are many more besides me; the Lord bring it home to us all.
This sickness began about the first of the Sixth Month,
and continued till about two or three weeks ago, very violent,
carrying people off in four or five days generally, some longer and some sooner;
there were sometimes four or five buried in one day,
and sometimes as many as seven or eight.
I only hear of one taken ill this two weeks last past,
so that it appears that the sickness is abated.
By the accounts received, we suppose in all about 230 are dead.
I have thought fit thus to acquaint you how things have been,
and how they are as near as I can.
There has been none buried out of this family except dear Roger Gill;
though in most families in town, some are dead, and most sick;
there is but here and there one dead hereabouts in the country,
and it is mostly as healthy as at other times.
Thanks be to the Lord, his Truth prospers through afflictions.
With dear love to you,

[.signed-section-closing]
I am, in haste, your friend,

[.signed-section-signature]
William Fishbourn.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Carpenter to William Ellis

[.signed-section-context-open]
Philadelphia, the 4th of 9th mo. 1699.

[.salutation]
Dear Friend, William Ellis;

I received your two letters from Maryland, and one from London,
soon after you arrived there, and one from dear Walter Fawcitt; and with Friends here,
was truly glad of your safe arrival and health.
As to the Lord`'s visitation over this poor town, since the beginning of the sixth month,
in which time many of our dear Friends and others, have been removed,
I suppose to the number of 200 within ten weeks`' time,
I refer you to dear Aaron`'s and to other accounts.
It has pleased God in great mercy to spare me, my wife and children, and family hitherto,
which I look upon as a mercy more than ordinary; and desire we may all prize it,
and walk worthy of it, for we have had, at times, in both families,
above twenty persons taken sick, some violently with the distemper,
and none have died but dear brother Abraham Hardiman and dear Roger Gill,
who died in our house: it being in a time when the distemper wis exceedingly mortal,
so that few recovered,
and some whole families of our near neighbours were almost all taken away.

Dear Thomas Musgrave and Thomas Wilson`'s wife,
and near fifty more of the passengers and ship`'s company
died on board a vessel coming here from Liverpool;
and about twenty more since they came on shore; of which number Thomas Wilson was one.
Here are many poor fatherless children and widows, of these,
and of others that died here;
so that the care and concern upon Friends now is greater than ever;
and there are fewer to perform the work of the day;
but I hope the Lord will raise up more,
and fit and prepare Friends for their particular services and duties,
and make them willing and cheerful in the discharge thereof,
though at present the work seems difficult, especially in this place.
The Lord enable us and make us diligent and faithful, and then hard things will seem easy.
Mine and my wife`'s dear love is to you and yours, and to dear Walter Fawcitt,
our dear love also to Joseph Kirkbride;
I received his letter enclosed in Nathaniel Puckle`'s,
which gave account of their arrival; his family is well, for ought I know,
also dear Walter`'s. This comes by dear Richard Gove to Maryland,
who intends for England with Aaron; I have not time to enlarge,
therefore conclude with my dear love to you and yours,

[.signed-section-closing]
Your friend,

[.signed-section-signature]
Samuel Carpenter.

--

Edward Shippen, the writer of the following letter,
was the father-in-law of Thomas Story: he was a respectable Friend, formerly of Boston,
and subsequently of Philadelphia: he was Speaker in the House of Assembly in 1695,
being member for Philadelphia.--See Proud`'s [.book-title]#History of Pennsylvania#, Vol.
II. page 26.

[.embedded-content-document.letter]
--

[.letter-heading]
Edward Shippen to William Ellis

[.signed-section-context-open]
Philadelphia, the 27th of 7th mo. 1699.

[.salutation]
Dear, and Well-beloved Friend, William Ellis;

I received your letter from Chester, also your last from London,
which gave account of your safe arrival in London, which we were all glad to hear,
and were also rejoiced to hear the hopeful account you gave of my son.
I desire as you have opportunity when in London to advise him for his good.
I read and considered your letters, and I have sent by our dear friend, Aaron Atkinson,
// lint-disable invalid-characters "¾"
12¾ oz. of gold, it cost here £76 10s. currency.
I suppose it will sell in London for something above £50 sterling,
the which I have desired our friend Aaron to dispose of or sell;
and I do leave the disposing of it to you and him among poor Friends,
where there is most need, either in Yorkshire or Cumberland;
for I have nothing in my eye to one county or place more than another,
but where it may be most helpful to poor Friends; and if there be a meeting at Alethey,
where I was born, I desire to know; and whether they be in need;
and if it be not too much trouble, what their names are;
and as you have opportunity and freedom, I shall be glad to hear from you,
if it should please the Lord to spare me a little longer,
for it is an exercising time with most here, and it still continues very sickly.
The Lord has been pleased to take a great many from us.
I shall leave the particulars to our friend Aaron to give you an account;
my desire to the Lord is,
that we may all be fitted and prepared to meet the Lord when it
shall please him to take us out of this troublesome world.
So with mine, my wife`'s and children`'s dear love to you, in that which changes not,

[.signed-section-closing]
I am your real friend,

[.signed-section-signature]
Edward Shippen.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Slack to Alice Ellis

[.signed-section-context-open]
Aykebank, 10th of the 7th mo. 1699.

[.salutation]
Dear Friend, Alice Ellis;

These with the salutation of that love to you which manifests
us to be Christ`'s disciples before the face of all people.
My friend, you are often in my remembrance, and mostly when Truth is near;
and when it is so, I cannot easily withhold praises from the Lord on your behalf;
for your carriage and deportment, and all I saw you concerned in,
did tend to the honour and glory of God, the exaltation of his Truth,
and the good of his people.
I believe the Lord is with you, and has blessed you, and will bless you,
as you abide faithful to him.
I believe he has made you a right, and an honourable nursing mother in his Israel,
and a sure pillar in his house, which shall never go out.
Oh! my friend, as you find freedom, let your prayers ascend up to the Lord for me,
that I may be preserved near him in my little and low station; for blessed,
yes ever blessed be his worthy Name, his divine pleasure is such as to touch my heart,
as with the finger of his divine love, I think, not to make me to appear in public,
but for the drawing of my mind more near unto himself.
Truth I hope is on the growing hand: people are inquiring the way to Zion.
I hope there are several convinced, if not converted unto God in righteousness.
Many eyes are over us; some for good; the Lord, says my soul,
take all stumbling blocks out of the way,
that the poor and needy souls may go safely on their way.
The Lord keep Friends`' minds near him, out of pride, high-mindedness,
self-righteousness, and vain glory,
and that their whole delight may be to give all glory and
honour to the Lord God and the Lamb who is eternally worthy,
now and forevermore, world without end, Amen, Amen.
My dear love is to your husband and Adam Squire.
Dear Alice, I desire to have a few lines from your hand as you find freedom.

[.signed-section-closing]
These are from your poor, weak, and low friend,

[.signed-section-signature]
John Slack.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Tompkins to William Ellis.

[.signed-section-context-open]
London, the 2nd of the 10th mo. 1699.

[.salutation]
Dear Friend;

Yours I received of the 18th of last mouth,
after it had been some short time with Samuel Harrison;
and I am glad at all times to hear of you,
but sorrowful that you are under so much exercise.
I cannot blame you for mourning for the loss of a good man, +++[+++John Wynn,
of Bradford]. Good men are too few everywhere;
and it is our Christian duty to be kind and affectionate one towards another.
Good men, who were devout, in the primitive times,
made lamentation for the loss of Stephen; and it is a fault to be otherwise minded;
for God complained in old time,
that the righteous were taken away and no man regarded it, or laid it to heart.
The Lord help you in your service for him, and stand by you,
if he take away your outward helps;
he is able to supply their place abundantly by the divine aid of his Holy Spirit,
and to give you power over unclean spirits; yes,
if you tread on scorpions they shall not hurt you;
but I am not without hope that as he calls one servant out of the vineyard,
he will send another servant into it; for he knows that the work is great,
and that there are at present few hands to do it,
of such as are true and faithful in their labour.
He is the great Lord of the harvest; he knows what is best, and he takes pity on his own,
and will not work them over long in the field,
though some he allows to tarry longer than others,
for ends best and indeed only known to himself; and those servants whom he calls away,
it is in mercy to them; they have the advantage of us that tarry behind,
in a double respect; not only that they are discharged from their labours,
but also that they are thereby secured from losing the reward of their work;
being where there is no sin, nor temptation to sin;
but where they forever receive an endless portion of life and joy;
and to eternity praise and glorify the name of God and of the Lamb.
My dear love to your wife; my wife`'s dear love to you and to her.
William Robinson is well; Friends here are the like.
I am confined to small compass in paper, but not in love, wherein I am large, and remain

[.signed-section-closing]
Your true friend and brother,

[.signed-section-signature]
John Tomkins.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Theodore Eccleston to William Ellis

[.signed-section-context-open]
London, the 13th of the 10th mo. 1699.

[.salutation]
Dear, Friend, William Ellis;

I have received your two letters about your sorrowful
exercises on parting with your ancient friend,
counsellor and comforter.
It was a hard case of old,
when the righteous were taken away and no man laid it to heart,
though surely they were taken from the evil to come.
There are few good men now removed but many find the miss of them, and although,
through the goodness of God, many honest-hearted are still among the living,
yet which of them can be spared?
But when they must go from us, we though sorrowful in parting from them,
must conclude that though it is our loss, it is their great gain,
a cessation from their exercises, their sorrows, their diseases,
their cares and their fears of being drawn into temptation,
and from a world of troubles and ruffling storms,
into a heaven of sanctity and sweetness of peace, such as is best guessed at by us,
by the sweet earnests of it which our souls have had comfortable tastes of by the way.
Oh! that nothing may divert our daily progress towards it, and our further fitting for it.
Your friend is not the alone worthy servant of the Lord, of late removed;
our late letters give an account from Pennsylvania of many; two, well noted,
I remember by name, are dear Roger Gill, that was Thomas Story`'s companion,
also Thomas Duckett.

It has been a sore time there, and in Carolina.
In Carolina, it is written, 150 have died, and in Pennsylvania many in a day.
We have had repeated warnings, and a contagious sickness has been in many lands,
and wars almost round about us, and this nation yet greatly preserved.
How well were it, if the long-suffering of God did lead men to repentance!
It was said of old, If judgment begin at the house of God,
where shall the sinners and the ungodly appear;
and how far the sufferings of the people of God in our land
may fall under that consideration is worthy of notice.
The Just did suffer for the unjust, that he might bring many sons to glory;
and how far the Lord may cause the sufferings of his people to redound to his own glory,
and the good of men, is worth observing.
Many, during times of sufferings were convinced, and Friends having,
through the Lord`'s assistance,
somewhat overcome by suffering them that caused them to suffer, have arrived at peace.
This also is a day of gathering men to the knowledge of the God of Peace,
that has in measure bruised and brought Satan`'s power down, in that sort;
and though in times of peace men of craft have set up for themselves,
and gathered to themselves, and with shows of outside religion,
gained people to themselves,
yet not having either loaves or fishes to feed the multitude with,
it is my firm persuasion, they will faint and grow weary,
and many come to see their real lack of bread from heaven in this wilderness.
As the body by amazement or diversion, may for a time forget the food it needs,
yet that forgetfulness will not always last;
so the souls of many have been diverted from considering their real need;
but I do hope the Lord is bringing, and will bring, many to a sense of their hunger,
and then they will cry for bread.
While men dream that all is well with them, and that they are eating and drinking,
how are they pleased, but when they awake and find themselves hungry,
how willing then are they to enjoy in substance, that which before, in shadows,
they only dreamed of.
This, I believe, is the state of multitudes, and thanks to the Lord,
he is raising up many to run to and fro, to awaken people,
that they may be aroused and see where they are, and what they have been doing;
and those whom he thus commissions are a people that are awake themselves,
and see that the night is far past, and that the true Light does shine,
and thereby they discern the feast that is prepared and the table that is spread,
where nothing is lacking but guests with the wedding garment on.
Oh! that none who are bidden may any more sleep the sleep of death;
but that they may haste and come away and partake, and partaking, praise the Lord.
I am glad your dear wife is of this number; the Lord, if it be his will,
strengthen her faith and confidence, that trusting in him,
she may be strong in his might, and bold in his moving,
to declare his great and notable day, that has broken forth to a remnant,
and must go on to the ends of the earth.
The Lord hasten this his work, for his own glory,
and for the good of the souls of men! that righteousness may be everywhere exalted,
and Truth and peace flow as a mighty river;
that high praises to his power may everywhere be sounded aloud henceforth and forever!
So with unfeigned love, I salute you and Friends who know me, and rest

[.signed-section-closing]
Your hearty friend,

[.signed-section-signature]
Theodore Eccleston.

--

John Wynn, whose death is referred to in the two preceding letters,
was convinced of the soundness of the principles held by the Society of Friends,
while a soldier in London, about 1662: he laid down his arms at a review,
and when discharged he removed into Yorkshire, and settled at Bradford,
where he worked at his trade as a clothier: he became an able minister of the Gospel,
and was a nursing father in the church of Christ:
his service in this character is affectingly set forth in
the following testimony respecting him by William Ellis.

[.embedded-content-document.testimony]
--

[.letter-heading]
The Testimony of William Ellis, concerning John Wynn.

There has been a testimony upon my mind for some time concerning John Wynn of Bradford,
in the County of York,
who died in the favour of God and in unity with his faithful brethren,
on the 16th of the 9th month, 1699.

I may truly say, the Lord`'s goodness has been great to mankind in these last days;
in which mercy and kindness he reached to my heart and soul,
about the seventeenth year of my age.
And in those days the Friend above-said was made an instrument in the hand of God for
my help and confirmation in that faith that the Lord had bestowed upon me;
and as I grew in years, he having a sense that grace did abound in me,
to the working out of the old corruption that had gotten fast root in me,
he grew tender to me,
and laboured to help forward that good work which the Almighty had begun.
And when it pleased God to work upon me so as to
open my heart to bear testimony to his holy Arm,
that was and is revealed and made bare for the recovery of man again,
he had abundance of care over me,
and often exhorted me to attend truly upon him that had bestowed his good gift upon me,
that so I might grow in the Root of Life;
and he would be now and then telling me where he saw many had gone
out and lost themselves that had received good gifts.
And he often gave me advice to beware of wrong spirits,
in resisting their diverse ways of appearing, to deceive the simple;
and on this manner his care was over me for more than twenty years.
And often he sounded his trumpet in meetings where my lot was cast; and I must needs say,
though his ministry was sharp, yet it was searching and powerful, with effect in it,
even to the awakening of my soul to judgment,
and that I might meet the Lord in the way thereof.
And it was so, that my heart was made willing to receive his reproofs, admonition,
and good counsel, from time to time: and a little before his departure out of this life,
he came to visit Friends hereaway, and Oh! what strength and power,
and zeal were upon him;
in which he advised Friends to continue steadfast
in faith and in love to God and one to another;
and that Friends might keep up their testimony against all
that would break in upon the liberties God has given them;
and that a true labour might be continued to keep good order in the church.

And when I heard that he was taken away, my soul was troubled within me,
knowing the great advantage I had gained; yet after a time of great retirement,
my heart was overpowered with that ancient virtue of life
that springs from the Fountain of everlasting life;
and in this I did then firmly believe, that his soul was gone to rest forever,
to sing the songs of thanksgiving to the Lord and to the Lamb, forever and ever.
Oh! the unutterable joy,
and harmonious sounds of songs of high praises that
have filled my heart when I have remembered him,
with many others whom I am satisfied did delight to serve God in their day,
and followed him truly like the worthies of old.
And the sense of this reward and crown of life being laid up for the faithful,
makes my soul the more earnestly to travel forward,
and be the more watchful over my ways,
and labour fervently to be the more given up in soul, body, and substance,
so that at the last upshot of all,
through Him that has loved me and washed me from my sins in his own most precious blood,
I may receive a sentence of Well done;
and come to know an entrance into the resting place with the Almighty,
and with the spirits of just men made perfect in Christ.
The sense of these things has been at times upon my mind,
and I could not truly see that I should discharge myself till I had written the abovesaid.

[.signed-section-signature]
William Ellis.

--
