== Chapter XII.

[.chapter-synopsis]
* Letter to William Ellis and Aaron Atkinson from several Friends in New England
* Letters from Samuel Galloway, John Tomkins, Samuel Carpenter, William Edmundson
* Notice of Joseph Scarth
* Letters from Joseph Scarth and Aaron Atkinson to William Ellis
* William Ellis to Richard Johns and Samuel Galloway

Peleg Slocum, one of the persons whose names are signed to the following document,
is mentioned by John Richardson in connection with
a remarkable visit to the island of Nantucket,
as an honest public-friend, from near Rhode Island,
and master of a sloop.--[.book-title]#Life of John Richardson#, Ed. 1843, page 84 to 94.

Some of the other parties are mentioned incidentally by Thomas Story.
In his Journal Folio, pages 349 and 350, he says "`On the 4th I went to Dartmouth,
and lodged that night with John Tucker; where I met with Jacob Mott the younger,
returned from Virginia, Maryland and Pennsylvania;
of whom I had an account of our affairs there within the compass of his travels.
On the 9th I was at Dartmouth Meeting again, and that evening I went with Peleg Slocum,
where I stayed till Second-day evening, and then went home with Stephen Wilcox,
who came on purpose to conduct me to his house,
which was between Dartmouth and Seconet.`"

[.embedded-content-document.letter]
--

[.letter-heading]
Friends in New England to William Ellis and Aaron Atkinson

[.signed-section-context-open]
Portsmouth, in New England, the 11th of 10th mo. 1699.

[.salutation]
Loving Friends, William Ellis and Aaron Atkinson;

Our souls salute you in the unchangeable love of our Heavenly Father,
who laid a concern upon you, to pay us a visit here in New England,
which has been to the convincing of several in this place,
and of great service and refreshment to our souls; God be praised for it!
The Lord opened the hearts of Friends in this place,
to contribute freely to the building of our meetinghouse: and it is accomplished,
and we had our Yearly Meeting in it.
There were many Friends from other places present; and we had a very good meeting;
for the presence of the Lord was with us, to our great comfort and satisfaction;
and we have a men`'s and a women`'s meeting settled among us once a month,
which is of good service; and we can truly say that Truth does grow and prosper among us,
and that we have reaped the fruit of your labours;
and we pray the Lord to keep us still in love, truly, to himself, and one to another,
to the end of our days;
so the work of the Lord goes on and our meeting is greatly increased in this place;
blessed be the Name of the Lord for it!
Having given you this short account of how things are among us,
our dear love is remembered to you both, in the blessed Truth which changes not,
which reached unto us in the beginning, from Him who has gathered us to be a people,
who were not a people, and has said,
Jacob shall dwell alone and shall not be mixed among the people;
praises be given unto him, who is God over all, blessed forevermore!

[.signed-section-signature]
Joanna Mott, Mary Slocum, Ruth Tucker, Cassandra Mott, Mary Lapham, Hannah Tucker,
Hasadiah Russell, Jacob Mott, Jun., Peleg Slocum, Abraham Tucker, John Lapham,
Eleazor Slocum, Stephen Wilcock, John Tucker.

--

For a notice of Richard Hill, who it appears by the following letter,
accompanied Aaron Atkinson on his return to England, see Chapter 10.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Galloway to William Ellis

[.signed-section-context-open]
West River, the 4th of the 12th mo. 1699.

[.salutation]
My Friend, William Ellis,

Whom I truly love and salute in the unchangeable Truth of our Lord Jesus Christ,
who in mercy to our poor souls and for the honour of his Truth,
has in this day of his power,
in a great measure plucked our feet out of the mire and clay, and set them on the Rock,
Christ, the foundation of the righteous in all generations.
Your kind letter is come to hand; your love in it I take very kindly,
and do in truth desire a renewedness of correspondence.
Our dear friend, Aaron Atkinson, has had a great service among us,
and now is bound home with Richard Hill;
the Lord I hope will conduct him safe to his own country.
By Aaron Atkinson come these lines, so I shall be at this time the shorter to you,
seeing he is able to give you an account of the affairs of Truth with us; but in short,
and in truth, this account I have to give you; Truth prospers with us,
and there is a greater convincement among people than I have known in my time.
The Lord, if it be his will, raise up those that may sound forth his Truth among us.
So dear friend in that which first brought us acquainted the one with the other,
do I salute you,
and conclude with mine and my dear and honest wife`'s love to you and yours,

[.signed-section-signature]
Samuel Galloway.

--

[.embedded-content-document.letter]
--

[.letter-heading]
John Tompkins to William Ellis

[.signed-section-context-open]
London, the 10th of the 12th mo. 1699.

[.salutation]
Dear Friend, William Ellis;

In the fellowship of Truth I dearly salute you; remembering your love,
and having your zeal for God in mind, and that your desires are that the Church,
which is the Bride, the Lamb`'s wife, may be all pure and fair,
made beautiful through the comeliness which He is putting upon her;
and that there may be a spirit of love and zeal and true judgment, in a sound mind,
found in every member thereof, according to the measure of the gift of Christ.
That every one in a true concern and care, as in the sight of God,
may know his own place in the Church;
every one walking according to the rule of the new creature;
all having regard unto the Head, holding the Head, as the Apostle says,
in whom every member is so fitly joined unto the body,
that in the receiving of the mercies of the life of the Head,
which supplies and nourishes every part, all parts thereby may grow up,
and together make a spiritual house unto God, all eyeing him,
and knowing their places in the body,--that body which edifies itself in love;
that body which is at unity with its own members:
all praising God in their several offices,
being also comfortable one with another in the exercise of their offices in the Church;
all having regard unto the Lord, the supreme Head of all.
None will, as they keep to the Root, and know the Root to bear them,
boast themselves against the Root, but will daily be in a concern of spirit,
to feel the virtue and sap of the Root to arise up
and make their branches living and green,
fit to be serviceable in their station; and as all keep here,
none will desire to rise up against their fellow members of the same body,
nor assume the place or office of another;
but all will desire to know and to serve in their own places,
keeping their eye unto the Lord who is the dispenser of his own gifts,
and bestows his talents as he pleases;
remembering what was said by the Lord to those whose eye was evil,
because his eye was good.
Is it not lawful for me to do what I will with my own?
I do you no wrong; take what is yours and go your way.
Those who are truly sensible of the Lord`'s mercy to them,
will esteem it a great mercy to be but as the least in the Lord`'s family.
It was but one thing, chiefly, that a great and wise man of old time desired,
and that he purposed to seek, That he might dwell in God`'s house forever;
and it was not a great place that he sought in that house neither,
but that of a door-keeper, so that he might but dwell therein.
His mind was not high to desire like the two sons of Zebedee,
one to sit at the right hand of his Lord and the other at the left;
but he chose that mean office rather than to dwell in the tents of the wicked.
The true members of Christ are all in harmony and concord with Christ the Head, who said,
Learn of me, I am meek and lowly in heart.
Oh! before honour comes humility.
Do any desire to be preferred in God`'s service;
the way to it is to be like our great Pattern and Example; and then,
if we be faithful and content with the place we are in,
the Governor of the household and family of God, will take notice of us,
as it is said in the parable which Himself made to teach us humility;
When you are bidden to a feast, go and sit down in the lowest room,
// lint-disable person-mismatch "you comes"
that when he that bade you comes, he may say to you, Friend go up higher;
then shall you have honour in the presence of them that sit at meals;
for whosoever exalts himself shall be abased,
but whosoever humbles himself shall be exalted.
These few lines of our Lord`'s have abundance of doctrine in them.

Dear Friend, when I began I intended not thus to write; but thus it opened,
and I have sent it; I know that he to whom I write will receive it in the best sense.

I have considered your last letter, dated the 12th of 11th month,
and I think if any unruly walkers be among you, and of the female sex,
there is a very good exhortation from our ancient Friend, dear George Fox,
among the Epistles lately printed in one volume,
of which I suppose every Monthly Meeting took a copy;
it is to be found in the 868th folio, entitled,
"`An Encouragement to all the faithful Women`'s Meetings in the World, etc.`"
It was written on purpose to quiet unruly spirits
who were ready to make a mutiny in the church,
about the separation of J. Perrot and J. Wilkinson.
There are many brave instances of the worth and of the good behaviour
of holy women of old time in the Church of Christ Jesus.
I am sorry to hear of your indisposition, but am glad you were recovering:
I hope your health is perfected before this.
William Robinson, my neighbour, has been ill about a week, but is recovering.
I am, through mercy, indifferent in health, was lately out about a week,
am now going again about the same time or more.
Truth prospers; Friends`' hearts, who are faithful, are strong in the Lord,
and full of faith, so that notwithstanding the creeping of the subtle serpent inside,
and the roaring of the devouring lion outside,
Zion remains immovable and cannot be shaken,
being founded upon the Rock which is higher than all; blessed be the Lord forever!
Mine and my wife`'s dear love to you and yours.
I remain, desiring to hear from you,

[.signed-section-closing]
Your true and faithful friend,

[.signed-section-signature]
John Tomkins.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Carpenter to William Ellis

[.signed-section-context-open]
Burlington, the 28th of 12th mo.

[.salutation]
Dear William Ellis,

I was not willing to let this opportunity slip without signifying
mine and my wife`'s dear love to you and yours,
and to Walter Fawcitt, Joseph Kirkbride, and Ann Dilworth,
and to other Friends that know us,
particularly unto all those that have laboured in the love of God among us,
who have been prophets and apostles and as God`'s messengers to us; and so I esteem them;
and desire that we may be worthy of so great blessings to be continued unto us.
I think I sensibly miss them;
and it is matter of sorrow to remember the loss of several of our dear Friends by death,
before they returned to their dear relations, friends and brethren, namely,
dear Robert Barrow, Robert Wardell, Mary Rogers, and Jacob Fallowfield;
the last in his voyage from Barbados towards this place,
and dear Mary in her passage from Nevis or Antigua to Jamaica:
but though to us that remain, it is a loss, to them it is doubtless gain,
who are taken from the evil to come, and freed from those hardships,
exercises and travails which did attend them in their pilgrimage and services;
and I believe they enjoy as the reward of their faithfulness and obedience,
joy and peace with the Lord forever, where there are no dangers, temptations, trials,
sighings or sorrowings, such as are with us who remain behind.
Dear friend! time being short, and having many letters to write,
accept of these hasty lines as a token of my dear love and respect to you and Friends,
in remembrance of yours and their services for the Truth among us.
I desire that we may all answer the love of God to us therein,
and in all other of his renewed and repeated favours
and mercies everywhere extended towards us.
Dear Governor Penn, his wife, daughter, and young son are in health.

[.signed-section-closing]
I remain your dear friend and brother,

[.signed-section-signature]
Samuel Carpenter.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Edmundson to William Ellis

[.signed-section-context-open]
Rossenallis, the 5th of 1st mo. 1700.

[.salutation]
Dear William Ellis,

I received yours from Liverpool, the Sth of 12th month last,
and am glad to hear from you; and that you, with many more of the younger sort,
are so well concerned for the promotion of the blessed Truth,
which will be your crown and diadem as you continue in well doing;
for continuing steadfast to the end crowns all the
labours of all the faithful followers of Christ.
The Lord enlarge your understandings in the knowledge of his will,
and of the mystery of his kingdom,
and increase your numbers to stand firm in his testimony for Ins Truth,
and the rights and privileges thereof, without wavering, as pillars in his house!
I am glad to hear that Truth prospers and has dominion;
for it is Christ that must rule and have the government,
that all power in heaven and earth is given to, and is the strongest,
that is overturning all that stands in opposition,
and is reforming and bringing all things into their right order, use, and service,
according to the infinite wisdom of God.
Where the harmony is known,
praises are given to the wise Creator of all things visible and invisible;
and the glorious day of the restitution of all things shines forth more and more,
in its clear discoveries and manifestations of all
things that are needful for us to know;
and our part is, to arise in the light of this glorious day,
and shake ourselves from the dust of the earth,
and put on the beautiful garment of the righteousness of the heavenly man.
The glory of this bright Gospel-day shines among us,
and many are affected by the discoveries of it,
and have a godly concern upon their hearts for promoting
the Lord`'s work according to their utmost ability;
and the work of reformation prospers in their hands,
as instruments in the hand of the Lord.
Church affairs are narrowly looked into, and Gospel order is closely prosecuted,
and hidden things are brought to light;
and it is come to Jerusalem`'s turn to be searched;
and the Lord has enlightened the spirits of his faithful servants to be his candles,
to find out things that do offend, and must not enter the kingdom of Christ.
The Lord is with us in this close work for his honour, and crowns our assemblies with,
his goodness, and is mouth and wisdom in all services,
and the power of Truth is over all, blessed be his great name forever and ever!
Amen.

Now, Dear William, you and all Friends that desire to hear from me, may know,
that I am very well, and able to prosecute the service of Truth according to my station,
beyond the ordinary course of nature,
considering my age and exercises that have fallen to my lot in my time.
I bless the Lord, my understanding is firm as ever, and I am able to travel easy journeys.
This last summer George Rook and I travelled some hundreds of miles in Truth`'s service,
in Connaught and some counties in the north, in unbroken places,
where we had many serviceable and satisfactory meetings,
with good reception by many of various ranks;
and the Lord`'s testimony in his glorious power was over all,
and crowned our service over all opposers.
This winter, I am not so able to travel as formerly; but I am hearty and sound;
only old age comes on; but I love to be with the Lord`'s plough,
where there is occasion to plough up the fallow ground.
Too many are too earnest to sow among thorns, thistles, briers, and tares,
which hurts the Lord`'s husbandry, and obstructs the fruit that should glorify God.
We are hard and close at work in this great harvest day;
and I love to be with the Lord`'s workfolks, to see how the work goes on,
and to lend my hand and heart, in as much as I am able;
and it looks to me as though the Lord had something for me to do,
of some small revision of my day`'s work;
and his blessed will be done that never failed me, nor any that fervently trusted in him.
So with my true love to you and yours, in the unchangeable Truth,

[.signed-section-closing]
I am your sincere friend and brother,

[.signed-section-signature]
William Edmundson

--

Joseph Scarth, the writer of the following letter, was a minister in Whitby Meeting.
There is little on record respecting him,
bat that he married Miriam Smales of Bridlington, in 1688,
and was liberated by his Monthly Meeting in 1699,
to pay a religious visit to the West part of Yorkshire and some parts adjacent.
The register of his death is in 1710.

[.embedded-content-document.letter]
--

[.letter-heading]
John Scarth to William Ellis

[.signed-section-context-open]
Whitby, the 6th of 1st mo. 1699.

[.salutation]
Dear Friend, William Ellis,

With design I give you a few lines,
I have several times had you and your wife in my memory.
Not knowing that I shall be at the Quarterly Meeting,
I take this opportunity of sending per Scarbro`' Friends,
who represent our Monthly Meeting this time.
This perhaps may meet you or your wife at York.
With dear love I salute you both:
keeping in the covenant of love and life engages us to remember one another;
therein are we made living members of Christ and one of another,
desiring each other`'s good and prosperity in that unchangeable Truth of our God,
which he has, in his infinite love and by his living power, gathered and drawn us into,
that we may glorify him in our lives and conduct,
and labour therein for the honour of his Name and the mutual comfort of our poor souls.
I pray God preserve us, guide and direct us in his wisdom and counsel;
attend us with his divine power and presence, that we may continue unto the end.
With dear love to yourself wife, and friends, I conclude in haste,

[.signed-section-closing]
Your truly loving friend,

[.signed-section-signature]
Joseph Scarth.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Aaron Atkinson to William Ellis

[.signed-section-context-open]
London, 2nd mo. 1700.

[.salutation]
My Dearly Beloved and Esteemed Friend, William Ellis;

My love is kindly remembered to you and your dear wife;
you are Friends that I both love and esteem.
The God of Israel that heard the prayers of Cornelius, the same God, I believe,
often looks upon you; for I know you are found in the same good practice.
Dear friend,
I can never forget at times your bowed down countenance before the Lord for me,
and upon my account, in the time of affliction.
I believe the Lord looked upon your sincerity and the cry of your soul;
for which his Name is worthy to be blessed while we have a day.
My friend, I am glad when I think of you, in hope you may be a strength to me,
if we should live awhile near to one another.
I know the Lord loves you in his merciful kindness; and though some may think,
who know you not, that you are high, and think to be over them,
and that you take too much upon you, like as the rebellious thousand said of Moses;
yet I know you better, and that you have but very mean thoughts of yourself;
yet the Lord that has not failed you, bears up your head;
blessed be his worthy Name forevermore!

Dear William, I am well, and came on shore at Dover, in Kent,
the 27th day of the 1st month.
I came over in the same ship that you came in, and lay in the same cabin you lay in,
and I loved it the better for your sake.
I observed your order in your letter, I never went up upon the deck above the cabin,
no not all the way over.
I hope to be at Leeds before long after this comes to your hand;
I shall be glad to see you there.
I have several letters for you, but keep them to save the charge.
I have something to employ you in among the poor, a work you love to be concerned in.
These with true love from me your loving friend,
that loves and esteems you for your sincerity`'s sake, and prays for long life for you,

[.signed-section-signature]
Aaron Atkinson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Richard Johns and Samuel Galloway.

[.signed-section-context-open]
Airton, the 4th of the 9th mo. 1700.

[.salutation]
Dear Friends;

With the salutation of unfeigned love to you,
and all Friends in Maryland as you may see fit, this may let you know,
that through the Lord`'s mercy, I am indifferent well,
and that though we be far separated one from another,
yet you are often in my remembrance.
The love unfeigned that the Lord raised in our hearts is not forgotten by me;
and in that love my heart and soul are often in a deep travail for your preservation,
and that Truth may grow among you; and in order thereunto,
that all Friends be advised to put on zeal as a garment,
and let their love be fervent to the Lord.
Let your fervency be demonstrated in often gathering together; and when met,
let a firm travail be upon your minds for the enjoyment of the Lord`'s goodness,
that they may not be said No of him.
Let all Friends come up in their places and bring their children
and servants to meetings on Week-days and on First-days likewise:
and let all come over that doubtful spirit that is and has
been too apt to keep Friends back in their service.
Tell them, that if they serve the Lord to the full, their outward things will not fail.
It was said by one of the Lord`'s worthies,
That once he had been young but now he was old,
but he never saw the righteous forsaken nor his seed begging bread.
Whatsoever stands in the way of your coming up as aforesaid,
let the Lord`'s power come upon it, and whether it be poverty,
or the abounding of riches, it will remove it; and when thus met,
and the Lord`'s power comes upon any, do not limit it, but let it work;
and if it bring up a word of exhortation, speak it freely;
but be sure it be in the Name of the Lord;
and if any find a word upon them that is deep and weighty, so that they can say,
For Zion`'s sake I cannot rest, and for Jerusalem`'s sake I cannot be silent,
encourage all such to pour forth their complaints before the Lord,
that the Lord`'s work may prosper,
and Friends grow in their measure and the gifts bestowed upon them;
and in the Lord`'s power run from one meeting to another,
and stir up the pure mind in one another, and then the beauty of Truth will appear,
and the face of Him will shine that has been more marred than the face of any man;
and as his comeliness appears, the world and its glory will fade away.

My soul,
O my soul within me! is in a deep travail for your growth in the most precious Truth;
and that your young people may grow in the knowledge of it and in love to it;
and I humbly desire that Friends may train up their young
children in the knowledge of the Law and the Prophets;
that when the Truth reaches their understandings,
they may worship the God of their fathers,
believing all that is written in the Old and New Testaments;
that from one generation to another,
the Lord`'s Name may be famous among our own posterity.
And dear Friends,
as there were several among you that had a sense of my soul`'s travail;
that it was not only that worship and service might be performed to the Lord,
but that Friends might discern between the precious and the vile,
and that the Lord`'s Name and power might rule over your families,
and over your trades and trading, and over all superfluity in apparel,
or whatsoever else;
and as my travail was full as much in secret as I could utter with my speech,
therefore my desire is,
that all Friends may truly labour to bring Truth`'s testimony up over all that,
would oppose it; and I do not doubt that in so doing,
the Lord will descend upon you with multitudes of blessings,
and they will rest upon you as dew upon the tender grass.
And whereas it has fallen for your lots to be exercised with wrong spirits,
whose pretence was to build up Zion,
but whose works declared that they were for pulling down the walls thereof;
and the Lord has showed you great mercy in giving you length of days,
and to see his power come over these wrong spirits, and bring down their evil design;
now it is my advice, that all Friends, everywhere,
watch against such wrong spirits and with all speed let them be judged down.

Dear Friends, I desire you all that are sincerely affected towards God,
and feel his Word like a fire in your hearts, to run to and fro to spread the Truth;
and wherever there is anything that has life and substance in it, visit it,
and labour to bring the Truth up, which that ranting spirit has trodden down;
and remember that little meeting beyond the Potomack.
So that grace, mercy, and peace may be multiplied among you, is the desire of him,
who is your friend in that which changes not,

[.signed-section-signature]
William Ellis.

[.postscript]
====

The copy of this was sent into Maryland,
to be read among Friends at the Eastern and Western Shore, as might be seen fit.

====

--
