== Chapter XIV.

Notice of William Biles--Letters from William Biles and
Nathan Newby--Notice of John Estaugh--Letter from Francis Tomes--Notice of Thomas Thompson
and letter from him--Notice of Josiah Langdale--Letter from John Tomkins--Notices of
Henry Gouldney and Ann Wilson--Letter from Henry Gouldney--Notices of John Fothergill
and William Armistead--Letter to Richard Johns--Letters from William Armistead,
John Rodman, and Thomas Aldam--Notice of Sir John Rhodes, and letter from him.

William Biles, the writer of the following letter,
is described by Proud in his History of Pennsylvania, Vol. I. page 237,
as a preacher among the Quakers, and as being among the first settlers;
and to have taken up land under Governor Andros, of New York,
prior to William Penn`'s grant of the province.
He appears to have settled in Pennsylvania about 1681,
and to have resided near the Lower Falls of the Delaware, in Bucks County;
and to have been elected a member of William Penn`'s first Council, in 1683.
He is said to have been a very useful person both in a civil and religious capacity.

William Biles to William Ellis.

Philadelphia, in Pennsylvania, 1699.

Dear Friend, William Ellis;

In a measure of that universal Spirit of love and life with
which it has pleased the Lord to visit us,
by which Spirit we shall be and are near and dear one unto another,
so that neither sea nor land can prevent the Sowings forth
of it through the lovingkindness of a tender Father,
my spirit has often remembered the refreshing seasons
we have had with you when present with us.
It was the mercy of a tender Father, never I hope to be forgotten.
In a measure of this Spirit my soul salutes you at this time,
with all the called and chosen of God,
desiring that that Arm of eternal power that has
been stretched forth for the gathering of us,
and has made us a people that were not a people, might be still with us, to lead,
conduct and preserve us, so that that great Name by which we have been called,
might be more and more exalted in the earth, and many more might be gathered unto it,
so that the gathered of God might be many in this the day of his power.
I left my wife and family pretty well when I came from home;
she desired me to remember her kind love unto yourself and wife,
and Friends in your parts.
We were both glad to hear of your safe arrival at home;
my wife talks of coming to see you,
but how it may be upon that account I shall at present
leave unto the ordering hand of the Lord;
the voyage is great and she but weakly in body.
Friends at present, through the mercy of the Lord, are generally well,
both in this province and in West Jersey.
I was lately at Croswicks and Burlington.
Your old companion, Samuel Jennings, and his wife and children are well;
his two daughters are married since we went hence.
Our Governor, Penn, and his wife are well; he has had a son born since he came here.
Edward Shippen and his wife Rebecca are well, and desire to be remembered unto you.
Since you were here, it has pleased the Lord to visit this town, and many of our friends,
as well as others, are removed, whom I am well satisfied the Lord has taken to himself;
yet we cannot but lament our loss of them;
but we must submit unto the hand of the Almighty in all these things; knowing right well,
that all things shall work together for good unto such as love and fear the Lord.
I believe you have heard of the long passage of a ship lately arrived here,
and of the loss there was of many of the passengers at sea, and after they came on shore.
I think it to be a great piece of indiscretion in the undertakers,
to allow so many people to be thronged together in one ship;
it was enough to breed a disease among them;
and if any should incline to come here for the time to come, my advice is,
never to come so many in one ship;
for I look upon the coming of so many together in that ship,
to be a great cause of their loss.
I have not much to add, save kind love to you once more,

From your loving friend,

William Biles.

Nathan Newby to William Ellis.

From the Southern Bank of Nancemund, 1701.

Dear Friend, William Ellis;

This is to let you know, that I received your letter, by our well-beloved friend,
John Richardson; and was very glad to hear that your desire was answered,
and that you were brought home, to your great comfort.
The consideration of the contents of your letter has been very much on my heart;
and it is matter of joy to me, that you, with many more of the Lord`'s servants,
are made to remember us in this poor land; for indeed we are a poor people;
yet the Lord is rich in mercy to them that seek him, can a remnant of us truly say.
Loving friend! it is with me a little to give you some account how it is with me:
I have been for two years past, concerned to bear a public testimony for my God,
which has been the occasion of sore travail to me,
by reason of the hard dealing and great opposing that I have had,
from some that you had a great sense of when you were with us; and this,
with the buffeting of Satan, has many a time brought me very low,
and has brought an exercise upon me which I am not able to express;
none have I had to fly to but the Lord alone,
who has been and is a present help in time of trouble; he has been my great succourer.
Praise be returned to him for the same!
The consideration of these things does break my heart at this very time.
I am not able to let you understand what I have passed through since I saw you;
and I desire you to sympathize with me; and O that I could have a time with you,
if it cost me the travelling some hundreds of miles!

Dear Friend, think on me, and let your requests be to the Lord for me,
who I know hears his own seed.
John Richardson was well about five weeks since;
I parted with him at Edward Thomas`'s at the Yearly Meeting;
he has been very helpful to me;
he desired me to remember his dear love to you and Friends,
and to let you know you are often in his mind.
The two Friends were not with him, but were gone to the northward;
there is a young man with him who came over with them,
and who lives in the south part of England.
Friends here are generally well, and were glad to hear of you.
We have our meeting quiet; people are very desirous of hearing the Truth sounded forth,
and many are under convincement.
Thomas Page`'s love is to you; Agnes Wilson, with several others, have their love to you.
So loving friend, I have in some sort given you to know how it is with me, and with us,
and should be glad to hear from you,
and I pray you let me hear as often from you as may be:
glad was I to have these lines from you: and I hope to take the good advice given by you.
I showed your letter to several Friends, and they were glad of it.
I must conclude and rest your unfeigned friend in the Truth,
desiring nothing so much as the prosperity of the blessed Truth of our Lord;
and to him I commit you and myself,
desiring that we may always be guided and ordered by his divine hand.
Mine and my wife`'s dear love to you.

Nathan Newby.

John Estaugh, who is noticed in the following letter, was born at Kelvedon in Essex,
in 1676: he joined Friends when about 17 years of age,
and became a minister when about 18:
he paid religious visits to the North of England and Scotland previously to 1700,
when he visited North America.
In this country he married, and settled at Haddonfield in New Jersey:
he afterwards visited Friends in England, Ireland, New England,
and some of the West India Islands.
When in the Island of Tortola, in 1742, his companion in the work of the ministry,
John Cadwallader, died.
Soon after his death, John Estaugh was taken ill, and in a few days he died also.
John Estaugh is described in a Testimony from Haddonfield Monthly Meeting,
as a humble-minded, exemplary Friend, of a solid and grave deportment,
well becoming a minister of Christ.

Francis Tomes to William Ellis.

1701.

Dear Friend, William Ellis,

Yours I received from the hand of John Richardson, a blessed memorial.
These come to let you know of our welfare, and of the increase of Truth among us;
many are gathered in, and I hope the Lord has many many more to gather.
Blessed be the Lord! we feel his presence among us;
and his heart-breaking power in the midst of us in our assemblies many times;
but indeed we are not without exercises many times; but blessed be the Lord our God,
the Truth reigns over all the gainsayers!
Two of your countrymen were here, which was great joy and comfort to us,
John Richardson and John Estaugh.
We had four or five meetings with them in our country,
and the power of the Lord was such, that it melted the meetings, both white and black,
to the astonishment of many.
I hope the Lord will reward them for their labour of love.
I showed several Friends your letter; they are glad to hear from you,
and Gabriel Newby`'s and several other Friends`' love is to you;
so with mine and my wife`'s dear love to you and all Friends, though so far asunder,
I take my leave of you,

And bid you Farewell!

Francis Tomes.

Thomas Thompson, the writer of the following letter,
was a native of the East-Riding of Yorkshire, but resided at Saffron Walden, in Essex:
he became a minister among Friends when about twenty-four years of age,
and travelled in the exercise of his gift in Great Britain, Ireland and North America.
He died in 1727, and a short time before his departure,
he adopted a declaration like that of the apostle Paul, saying,
"`I have fought a good fight; I have finished my course.
Henceforth is laid up for me a crown of glory,
which God the righteous Judge shall give me at the last day; and not to me only,
but to those who love his appearance.`"--See Piety Promoted, Part IX.

Thomas Thompson to William Ellis.

New England, 1703.

Dear William Ellis;

A letter of yours bearing date about when we left England, coming lately to my hand,
the good advice therein contained to us all,
I could not but take notice of more especially, because I have a certain knowledge,
through the mercy of God, of the spirit and life from which it came,
and therefore could not be easy but make some reply thereunto,
with due acknowledgment to the Lord our God,
who has raised supplications in the hearts of his faithful servants on our behalf,
which I do sincerely desire may continue.

As to my own particular, I can say,
I had never more need of the prayers of faithful brethren than now;
and surely your spirit has been often with me in these wilderness countries,
and your memory, with the savour you have left behind you in these parts,
is sweet to the faithful in Christ; among whom I have been wonderfully favoured,
in the feeling of his glorious power, who is Almighty God,
which has wonderfully shone over meetings, to the gladness of the hearts of the upright.
To give account in writing of particulars, would be too tedious;
only I shall give a hint of New England, and Rhode and Long Islands,
where my service has chiefly lain as yet;
though some glorious meetings we have had in Maryland, Pennsylvania,
and East and West Jersey, but have made Little stay in these parts.
In New England, I visited several meetings seven or eight times over,
and am not yet clear of that country.
Upon Rhode Island, I hear is a young generation,
that is coming zealously up for the Truth; and the Lord is with them,
in whose name and power I have sometimes been made to thrash
the mountains that stood in their way and the Truth`'s way;
and many a grapple in spirit, I have had with them;
but the Lord has hitherto preserved and borne up over all; and through his great love,
I am well in body and spirit, and my heart, I can say in humility, is strong for him.
Upon Long Island I was greatly concerned to promote discipline;
for they are short in that, though there is an innocent people among them,
and not many tall cedars are there to be met with.
Since the other side was written, we have had a large and glorious Yearly Meeting here;
and indeed we may say.
The love of God is very large to his people here and everywhere.
That which is lacking is on our parts, namely:
a close walking with Him who is the God of the living, exercised, bowed down souls,
and who love those that walk in true humility before him.
In this frame of mind the Lord forever keep us! that
so the work which he has concerned us in,
may be gone through to the glory of his great Name, and the comfort of our own souls.
And dear friend! let me be remembered by you in your nearest approaches to the Lord,
in the feeling of whose divine power my soul salutes you with your dear wife,
and bids you dearly Farewell!

From your true friend,

Thomas Thompson.

Josiah Longdale, mentioned in this letter, was from Bridlington:
he visited America as a minister in 1700, and again in 1714;
and in 1723 he embarked with his family, with the intention of settling there;
but he was taken ill soon after sailing, and died on the passage,
making a peaceful close.
Some time afterwards his widow became the wife of Samuel Preston.--See American Memorials,
page 118.

John Tompkins to William Ellis.

London, the 4th of 2nd mo.
1704.

Dear Friend, William Ellis;

I have your letter dated 25th of 1st mo.
last,
by which I understand that John Richardson will pay the £40 to the Thompson`'s family;
but I am sorry to hear of a bad disaster which has befallen them, by a fire in the town;
it is a sore blow upon the poor ancient people in their old age,
and the poor wife of Thomas Thompson, now that her husband is remote from her.
I saw a letter that came this week from Antigua or Nevis, dated about six weeks ago,
giving account that Thomas Thompson and Josiah Longdale,
were at that time in that Island.
Josiah purposed to go to Jamaica,
but Thomas Thompson designed to return home from Antigua,
so that by next shipping we may expect him.
It is much surprise to me seeing he has stayed so long,
that he should leave Josiah alone at last; but it is time he was at home.
I perceive by yours that Jeremiah Grimshaw, Thomas Aldam,
and John Fothergill will come up to the meeting with another Friend;
I hope that Friend is yourself.
I should be glad to see you, and would invite you to my house, for quarters;
but our friend, Francis Plumstead, tells me that he has invited you already to his house,
since your landlord, James Tatham, died;
so I am forbid to covet my neighbour`'s property.
Dear William, my heart is toward the willing in Israel,
who offer themselves freely among the people,
and I remember you at this present time in the love of Christ Jesus,
wherein we have had fellowship, and taken sweet counsel together.
Come and see us, and be partaker with us, of that joy and gladness of soul,
which we trust the Lord will fill us with, when he brings us together again.
I am straitened for time, so must conclude in true love,

Your true friend and brother,

John Tomkins.

Henry Gouldney, the writer of the following letter, resided in White Hart Court,
Lombard-street, London.
It was at his house, in 1690, that George Fox died.
He seems to have used the term Landlord, in reference to James Tatham,
in the same sense as that in which it is used in the previous letter,
applying it to the person who hospitably entertained
William Ellis when he happened to be in London.

Ann Wilson, noticed in the following letter, was probably the same,
that about eight years before, by a simple communication in the ministry,
when at Brigflats Meeting near Sedbergh in Yorkshire, on a religious visit,
was instrumental in awakening Samuel Bownas to a
religious life.--See Life of Samuel Bownas.

Henry Gouldney to William Ellis.

London, 8th of the 2nd mo.
1704.

Dear Friend, Wk. Ellis;

The present circumstances of trade are such as that I am sorry they will not answer,
otherwise I should have desired a further correspondence on that subject,
but that however shall not interpose with our better acquaintance,
begun and held upon a more noble principle than that of outward interest.
Your honest landlord, James Tatham, is indeed gone; and I doubt not,
has now a better and more enduring mansion.
I should be glad to succeed him in the first, and I hope for a residence in the other;
for it is said in the Father`'s house there are many mansions;
and I question not that there will be room enough for the honest-hearted.

Dear friend, I love you for the sake of your noble and hearty resolution,
to serve in your high and holy calling;
and it is your great advantage that your yokefellow
is like-minded and draws the same way,
for this is not always the lot of faithful labourers;
exercises are the common companions of their pilgrimage;
but a second self helps to sweeten the bitter cup,
as your generous and cheerful wife doubtless very often does.
Though I am not likely to see you in the North this year,
yet I am pleased we have the hope of having you in the South, at our anniversary.
Let not indifferent things hinder you; for I assure you,
the coming of the Lord`'s worthies at that season,
besides the helping on of the business of the meeting, has a great service,
as they come up in the life and beauty of the Truth,
labouring that this may reign among us.
The life and beauty of the Truth will give a lustre to all the affairs of Truth.
Though the business must be done,
and Friends exercise a care that the hedges be unbroken, yet that,
without the glorious shining of the power of God will not be a
sufficient inducement for Friends attending that assembly;
and I would not, with submission to the will of God,
that an eclipse should come on that solemn occasion.
But I think sometimes that I observe obstructions in the way,
so that the virtue of the Truth does not circulate as one could desire,
considering the many vessels that seem to be filled with heavenly oil,
and the water-pots that are divinely filled, and should be be running over,
to refresh the souls of those that are thirsting after the refreshing streams thereof.
I think there is a nature that is rather for damming up these streams,
and is satisfied with the more puddled waters that will
not tend to the cleansing of the camp of God.

I am glad to hear Abraham Rawlinson came so well off at the court sessions,
for his family and the Truth`'s sake.
Things among us are much as usual;
we have not of late had the visits of so many worthies as heretofore;
yet our dear Friend, William Penn, is among us and has his share of service.
Ann Wilson, that was here lately, visited us,
and had a service to her own and Friends satisfaction.
I am, with mine and my wife`'s dear love to you and yours, and all Friends,

Your real friend,

Henry Gouldney.

John Fothergill, who is noticed in the following letter,
and was the writer of a subsequent one in this volume,
was born in Wensleydale in Yorkshire, in 1676:
he was brought up with great care by his parents,
who had joined the religious society of Friends.
He was attentive to the convictions of the Holy Spirit
upon his own mind from an early age,
and under the constraining power of the love of Christ,
became a minister of the Gospel when but a young man.
In his twenty-second year he paid a religious visit to Scotland,
and he subsequently visited various parts of Great Britain, Ireland, and America.
He was about 30 years of age when he paid his first visit to America:
he resided for some years at Knaresborough, where he died in 1744,
aged 69 years.--See Memoirs of Samuel Fothergill; also Piety Promoted, Part VIII.

William Armistead, the companion of John Fothergill,
and the writer of two letters in this collection,
appears only to have been twenty-five years of age
when he went to America on a religious visit:
he was a minister residing within Settle Monthly Meeting,
and had previously visited some parts of Great Britain in this capacity.
There is little recorded respecting him after his return from America;
but he settled in London in 1712,
and became one of the Correspondents of York Quarterly Meeting:
he died of consumption on the 19th of 3rd month, 1731, aged 56 years.

William Ellis to Richard Johns.

Airton, 1704.

To Richard Johns.

By this know, that it has been often in my mind to write to you,
but I have been prevented; so having this opportunity, I was not willing to pass it by,
but to let you know that you with many other Friends have been and are often in my mind;
and in the remembrance of you I can say,
my heart is often very much enlarged in love to you;
and great pleasure I have in thinking of you, and in the secret of my heart,
I desire the growth of Truth and righteousness among you,
and that many may be added to you,
and that the life of our profession may be perfectly enjoyed,
so that the desert may be as pools of water,
and the inhabitants of the wilderness may sing for joy,
because the Lord is risen to redeem his people by his holy arm,
which has put on strength, and is certainly made bare in this our day.

Dear Friend, I cannot easily express my love to you;
and when I think of the times we have been together by sea and land,
and enjoyed that which is from everlasting and to everlasting,
it much more abounds with desires for your safety till the end come;
for I see the adversary is at work to hinder the completing of the great work of salvation.
If this come to hand you may give as much of my kind
and affectionate love to Friends as you see fit,
and to whom you will.
I have been about a year and a half sorely afflicted,
and thought I should have gone before now,
yet am able to stir a little about among Friends, by which I have great help;
but I cannot yet see that I shall be well again while I am here.
Herewith come two Friends to visit you, John Fothergill and William Armistead.
Though but young they are well approved of, and zealous, both in doctrine and discipline;
men that I look for a great deal of good service out of, if they live; and if they come,
you may receive them as such.
So with true and unfeigned love to you and your wife, I rest

Your true friend,

William Ellis.

William Armistead to William Ellis.

London, 27th of 2nd mo.
1704.

Dear Friend, William Ellis;

These lines are to let you know that through the Lord`'s
mercy and great goodness I am well in my health,
as is also my companion, and pretty well in my mind,
considering that many exercises attend me.
Friends here are very kind and respectful to us;
but we have been so much in a hurry and cumber about getting forward,
that we could not enjoy them to our satisfaction;
however I am pretty easy in my mind in the main,
hoping that the great and good God who has concerned us in his great work,
will go along with us, and attend us with his good Spirit,
which is alone the help of his people in all trials and exercises; and I can say,
it is the deep travail of my soul that I may keep so near unto him, and lean so upon him,
as that I may witness the brightness of his countenance shining in upon my soul,
which is that alone in which I can truly rejoice.

And dear William, let I pray you, your cry be unto the Almighty in my behalf,
that he may stay my mind, and anchor and settle my thoughts,
so firmly and steadfastly upon him,
as that by his power I may be carried on to his glory,
and my own soul`'s peace and satisfaction; that if it be his will to bring me back again,
it may be with sheaves in my bosom.
We are, for anything we know, going out of this town this day towards the Downs,
where the ship lies, in expectation if the wind serve,
to set forward on our journey or voyage, the 30th of this month.
The fleet seems to be in great haste to be gone.
We wrote a few lines to you before, but have had no answer yet.
We are likely, we hope, to go with an honest Friend who sails for Maryland.
I am very desirous to hear from my friends, but have not as yet heard from any of them,
which makes me a little wonder.
My dear love is to you and your wife, and your family, and faithful Friends in general,
and to my relations when you have opportunity.

From your truly loving friend,

William Armistead.

The writer of the following letter is incidently mentioned by Samuel Bownas, page 82,
edition 1846, as "`a worthy Friend, John Rodman by name.`"

John Rodman to William Ellis.

New York, 21st of 11th mo.
1704.

Dear And Esteemed Friend, William Ellis;

In that love that is unchangeable, do I dearly salute you,
hoping and steadfastly believing,
that the great God of mercy and love will be with you in your travail,
for his Name`'s sake, and for the prosperity of his Church, in a glorious manner,
to the great joy and comfort of those that truly love the Lord;
for I know from a living sense, that the Lord of the great harvest, even Jesus Christ,
is with you, and does sweetly comfort and strengthen you by his Spirit, to go forward;
and through his pure love, makes hard things easy.
O, magnified be his pure Name forever, for he is worthy! even Christ our Lord,
"`who is over all God blessed forever.`"
He has, even in his holy body, showed us the example, enduring hardship for us,
that he that has perfected salvation for us, might fit us to be made partakers of it.

Dear William, I may signify my dear unity with you; for the Lord of all our mercies,
I can with great assurance of spirit say,
has given me a living sense of his divine power that lives in you,
which has knit my spirit to you;
in which I have felt a rejoicing in humility before the Lord,
in that which comes from above, in which joy and life from God,
though absent in body yet present in spirit, I felt encouragement in the sense of life,
to say unto you, Go forward in the Name of the Lord.
My dear friend, Farewell!
The grace, mercy and power of God go with you,
and be your strength and comfort and unspeakable joy;
always remembering that without Him, we cannot do anything for his glory or our own good.
William, pray unto the Lord for me, that I may walk worthy of the Lord`'s mercies,
and be found a faithful steward, doing the will of the great God.
My dear love to Friends, and more particularly to those that have travelled among us,
as you have opportunity.

So rests your well-wishing friend,

John Rodman.

Thomas Aldam to William Ellis.

Warmsworth, 20th of 10th mo.
1705.

Esteemed Friend, William Ellis;

My love in the unchangeable Truth does hereby salute you,
with your dear wife and the rest of faithful Friends; and by this you may know,
that both your letters came to hand;
by which I understand that then your exercises were great; these,
I desire the Lord in mercy, if it be his will, may abate, or however,
sweeten with the enjoyment of his life-giving presence.
O this is that, my dear friend, that makes hard things easy, and bitter things sweet.
He is the Physician of value who can cure all manner of diseases, both of body and mind;
those that know him can trust in him, hoping and patiently waiting for his salvation,
believing him to be a God keeping covenant,
and showing mercy to a thousand generations of those that love and fear him,
being near to help us when our outward man decays, by the renewing of our inward man.

My dear friend, I do not write unto you as to one that knows not these things;
but my heart being opened with the remembrance of his goodness,
and a present sense thereof, I cannot but say, O that my soul,
with the souls of his little ones,
may forever trust in the Lord! that we may know Him that has been with us in six troubles,
to be with us also in the seventh; for I see when we have done all,
we have need of patience; for as to the outward man,
I have seen one event to the just and to the unjust; but blessed be the Lord,
he is settling a remnant upon that Rock, against which the gates of hell cannot prevail.

Again I dearly salute you, my ancient friend,
having always taken very kindly your remembrance of, and travail for me,
either by writing or otherwise;
and I think we have still as much need to seek the Lord one for another,
and for his whole Church, as ever we had; for we have an unwearied adversary,
who goes about to deceive and devour.
I had written sooner to you, but had hopes to have seen you at the Quarterly Meeting,
if your weakness did not hinder.
There still continuing a difference between R. Clayton and Friends of Derby,
and being desired to be at their Quarterly Meeting,
I am in a strait touching my visit to York,
where I would have willingly been with the rest of my beloved friends,
considering Truth`'s service in our county,
and the great need there is of the peaceable wisdom,
in which our true unity is preserved.
If I be not there, I should be glad to hear of your being there if the Lord enable you.
I have not room to enlarge, but committing you with myself to the Lord our preserver.

I remain your friend and brother in the Truth,

Thomas Aldam.

Sir John Rhodes, Bart, the writer of the following letter, resided at Balber Hall,
in Derbyshire, but belonged to the meeting at Handsworth Woodhouse, near Sheffield.
Martha Rhodes, his mother, with whom he resided,
and whom Thomas Story styles "`The old lady,`" of this family,
appears to have adopted the principles of Friends at an early period,
and to have suffered distraints in consequence, between 1683 and 1690.
Her son, John, and one of her daughters also became Friends;
the former is said to have become convinced of the Truth when very young,
and to have embraced the same under the cross,
forsaking all the honour of this world and the friendship of it,
for that honour which is of God only,
and the friendship and fellowship of the faithful and sanctified in Christ.
Sir John Rhodes remained single to the end of his days and lived a retired life,
which rendered the brightness of his talents less
conspicuous than might otherwise have been the case.
He died about 1746.--See Life of Thomas Story, fol.
pages 90, 465, 684, 787.

John Rhodes to William Ellis.

Balber, in the Year 1705.

Much Esteemed Friend, William Ellis;

My dear love salutes you, for the Truth`'s sake,
which has made you not only truly lovely,
but greatly serviceable to the Church in our day:
the Lord having honoured you with an eminent station therein,
and endowed you with the rich jewels of his treasury,
that he has been pleased to open and dispense to the children of men,
in this age of the world.
And it is not the least of your ornaments,
that you are not lifted up with those distinguishing favours,
because they are given you and not merited by you, for which my soul loves you,
and esteems you above the great men of the earth;
and I could wish our outward habitations were nearer together,
that I might have the privilege of your desired and valued company,
being sensible it would be much to my advantage in the better sort of things,
in which I covet that my profiting may be,
however things may succeed with me as to transitory enjoyments;
finding by a long experience that a habitation in the Truth is the greatest riches,
and I hope I shall ever be of that mind;
for through mercy I see more of the emptiness and
unsatisfactoriness of the great things of this world,
and of what her children, love, than I have sometimes done,
which often puts me in a travail, that I may be counted worthy through Christ,
to obtain a mansion with the redeemed and beloved of God in eternal habitations,
when the glories and honours here below will be at an end.

Dear William, my heart abounds in love, but I must stop, and let you know,
that your generous present came safe to hand,
and was gratefully accepted in the love you sent it in,
but I was concerned that you should be at that charge, in bestowing a kindness upon me,
that never did anything to deserve it at your hands.
I know not when I shall get to make my acknowledgments to you at your own house,
and to see your good wife, of whose excellency I have heard much;
for I am often not well, which prevents me from going far from home.
I perceive it is your lot also to meet with bodily exercises.
I should be glad to hear it was otherwise with you.
As for me, I have found it good that I have these afflictions;
for they have taught me to number my days, and to apply my heart unto wisdom;
so that I may say, The Lord, in very faithfulness, has afflicted me,
and made me to sit in the dust and mourn over Him whom I have pierced,
and be in bitterness for it, that I might witness his great salvation and remission.
I must conclude with dear love to you and your kind wife.
I hope to remain

Your loving and obliged friend for the Truth`'s sake,

John Rhodes.
