== Chapter XVI.

[.chapter-synopsis]
* Remarks on Wrong Spirits
* Notice of Susanna Freeborn
* Letters from Leah Newbery and Richard Johns
* Notices of Thomas Wilson and Joseph Glaister
* Letter from Samuel Jennings
* Notice of John Gratton and letter from him
* Letter to Francis Tomes
* Letter from George Rook
* Notice of George Knipe and letter from him
* Letters from William Edmundson and Thomas Rodman

Some of the letters in this chapter, as well as some in those preceding, show,
that notwithstanding the Society of Friends was at this period,
in a state in which the accessions to its numbers by convincement
were much greater than has been the case in modern times,
it nevertheless had, in some places,
trials to endure in consequence of the obtrusion of a wrong spirit.
Trials from wrong spirits have occurred in the Church
of Christ in most periods of its history;
and the apostle Paul when speaking of "`divisions`" among the brethren in his day,
attributes them to a permitted condition,
in order "`that they which are approved may be made manifest.`"
Trials arising from wrong spirits are not therefore to be
taken as necessarily proving a lapsed condition of the Church,
but rather as evidences of the necessity of watchfulness and prayer,
lest those who think they stand should not be found in a christian spirit,
or in any other way should fail of the grace of God.

In the [.book-title]#Life of John Richardson# mention is made of Susanna Freeborn,
who is noticed in the following letter: she went in company with him,
on a religious visit to Nantucket;
and he speaks of her as a woman in good unity with Friends.--See [.book-title]#Life of John Richardson#.
Edition 1743, page 85.

[.embedded-content-document.letter]
--

[.letter-heading]
Leah Newbery to William Ellis.

[.signed-section-context-open]
Rhode Island, 29th of 6th mo. 1706.

[.salutation]
Dear Friend, William Ellis;

Our friend, Alice Anthony, desired me to write a few lines for her to you,
to let you know that your labour of love among us has not been in vain;
we are livingly sensible of the good effect of it;
blessed be the name of the Lord! although there has and is a spirit
among us that would crush and keep down the young ones,
and is ready to envy and snub them; and not only so,
but when strangers and travelling Friends come among us,
is ready to bias them as it were to dash and beat some back.
All this proceeds from self-love; self would be had in reputation;
self would be esteemed and honoured, and have the preeminence;
but where the Truth prevails, in old or young, such cannot but honour, love,
and esteem all the faithful, and more especially those that are ancient in the Truth.
I was reluctant in myself to write after this manner;
yet was willing to give you a little account of the truth of things among us.

Our dear friend, Thomas Thompson, has been a valiant warrior among us,
and has quit himself like a man.
Indeed, although I believe there are some among us,
and that not of the meanest sort neither, that will say of him as they said of you,
That such doctrine as yours will do little good here.
What shall we say, when such as are accounted leaders cannot endure sound doctrine?
However,
blessed be the Lord! there is a remnant upon Rhode Island that love sound doctrine,
and desire to be searched thoroughly; and this I have to tell you,
that Truth has prospered and grown more upon Rhode Island
and the parts adjacent since the time you were here,
than it has done for fifteen or twenty years before.
There are several that are come forth and have a concern for the prosperity of Truth.
Our dear and ancient friend, Daniel Gould, is well, also Susanna Freeborn,
the young woman that came forth in a testimony when you were among us;
to whom you were a nursing father.
We cannot forget you, but you are very fresh and living in our remembrance,
and we have cause to bless the Lord on your behalf.

Dear friend, I am a child, and have written like a child, stammeringly and brokenly;
but I hope, as you are strong, you will bear with the weak.
My dear love salutes you, and

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
Leah Newbery.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Richard Johns to William Ellis.

[.signed-section-context-open]
Maryland, 12th of 6th mo. 1706.

[.salutation]
Dear Friend, William Ellis;

Whom I truly love, I have yours per our friends, John Fothergill and William Armistead;
and I was glad to hear from you, though truly sorry for your affliction.
I may say as you do, It has been often in my mind to write to you,
but something or other has prevented.
And now having this opportunity, by our friend, Samuel Bownas,
know that through the continued mercy of the Lord
I with my wife and all my children enjoy health;
and Friends in these parts are generally in health, as when you left us,
and the Truth prospers in America.
The Lord has a people here to whom his love is;
and he delights to water them with the distillation of the dew of his mercy,
which engages them to be zealous for the honour and glory of his great Name;
and the constraining power of the Lord has opened
the mouths of several of his people hereaway,
to speak a word in season.

Several new Meetinghouses have been built, as at the Cliffs, Herring Creek,
and Petapsio,
also large additions have been made to our Yearly Meetinghouse at West River.
The last Yearly Meeting there, has settled a meeting of ministering Friends.
In this Province, the great benefit they are of has been already witnessed among us.
Our Week-day meetings are duly kept and pretty well attended,
and Friends are zealously concerned for keeping up
the established discipline in the Church.
And I may further tell you, that Friends hereaway are of one heart; we have no opposers,
peace, love and unity dwell with us.
Thus I have given you a brief account of the present
state of Truth`'s affairs among us here;
and in a fresh remembrance of our sweet companionship, both by sea and land,
and in a living sense of the many heavenly visitations we enjoyed together,
I conclude at this time,
who am your truly loving friend and brother in the fellowship
of the Gospel of our Lord and Saviour Jesus Christ,

[.signed-section-signature]
Richard Johns.

--

Thomas Wilson, who is mentioned in the following letter, was a native of Cumberland:
he was brought up in profession with the Episcopal Church,
but joined the Society of Friends while a young man.
After experiencing a true change of heart by the power of the grace of God,
he came forth as a minister of the Gospel of Christ;
and under the constraining influence of the Holy Spirit
travelled in the exercise of his gift in Great Britain,
Ireland, and America: he settled at Edenderry in Ireland, in 1695:
he often travelled in the work of the ministry in company with James Dickinson.
Thomas Wilson died in 1725, aged 70,
having been a minister about 45 years.--See [.book-title]#Piety Promoted#,
Part IX. [.book-title]#Leadbeater`'s Biographical Notices#,
page 158. [.book-title]#Journals of Thomas Wilson and James Dickinson#, edition 1847.

Joseph Glaister, who is also noticed in this letter, was born in Cumberland,
from which county he visited Ireland in 1695,
in company with another Friend of the same name:
he removed with his family into North Carolina,
and is described in a testimony respecting him as a valuable minister,
and very serviceable in the discipline,
and one who travelled much for the spreading of the Truth: he died in 1718,
aged about 45 years, having been a minister about 24 years.

[.embedded-content-document.letter]
--

[.letter-heading]
Samuel Jennings to William Ellis.

[.signed-section-context-open]
Philadelphia, 13th of 6th mo. 1706.

[.salutation]
Dear William Ellis;

With true and hearty love do I salute you,
in a renewed and living remembrance of your labour of love while among us,
which I pray God plentifully to reward for it has
left a living impression upon many hearts,
such as neither time nor distance can wear out.
I was pleased to hear of you by Samuel Carpenter, to whom you wrote,
but grieved to hear of your affliction.
The Lord relieve and ease you, my dear friend!
I thought to have written to several Friends that have travelled
here (for others in your parts I know not) only to renew love,
for business I have none with any.
I entreat you to help me to supply that defect: I have not time to do as I would;
therefore pray give my dear love to John Richardson, whom I believe to be a faithful man;
he was kindly received here for his work`'s sake; also to your companion, Aaron Atkinson;
and if it fall in your way, to dear Thomas Wilson and James Dickinson,
Thomas Thompson and Josiah Langdale, and Joseph Glaister;
they will be all glad to hear of the Truth`'s prosperity and Friends`' welfare.
Things in the main, I think, are pretty well among us,
though we are not without our exercises on various accounts, both religious and civil;
but there are some that trouble us, who seem to be of us, who are high and stubborn,
asserting rule, but not having learned to rule themselves; and for lack of skill,
they are apt to justify the wicked and condemn the righteous,
which practices are both an abomination to the Lord; but the Truth is over them,
and they shall not proceed much farther; and the living are out of their reach,
under the waterings of heaven,
and they grow to the honour and praise of Him that has planted them,
and is daily bountiful to them.

Many Friends here suffer loss of goods, for not training for soldiers,
which loss in the general they cheerfully and honestly suffer;
but a few raise contrivances to avert suffering, to the staining of their testimony,
and yet would be thought clear.
Low priests and apostates are wicked and envious and very busy;
but the Truth goes over them all and must prevail.
Dear John Fothergill and William Armistead are now with us;
we are very glad of the assistance the Lord has given us,
by seasonably sending his servants among us.
I believe they all have their reward in it,
and honour is brought to God and comfort to his people by it.
The Lord keep us sensible of the multitude of his mercies,
in the unity of his Holy Spirit, without which we can neither grow nor live;
so that therein we may praise Him who is worthy of all praise and renown,
now and forever.
This with dear love to yourself and your dear wife, though unknown, and all Friends,
is from your sincere friend and brother in the fellowship of the Gospel,

[.signed-section-signature]
Samuel Jennings.

--

John Gratton, the writer of the following letter, appears to have been born about 1641.
He was first brought under religious conviction,
when he was a shepherd-boy of eleven years of age,
but he remained in a halting state till he attained to manhood;
he then became more devoted in heart to the Lord.
He was brought into great grief on observing the
instability of some professed preachers of the Gospel,
in times of persecution.
In 1670 he began to preach among the Baptists,
but soon left this people because they also flinched in the day of trial,
and becoming convinced of the soundness of the principles held by Friends,
and seeing their constancy under suffering, he joined them in 1671.
The third time he attended a Friends`' meeting,
he spoke as a minister under the constraining influence of the Divine Spirit;
and he soon became an able minister of Christ.
His business was that of a butcher,
but he often left his temporal concerns to make apostolic
visits to various parts of Great Britain and Ireland;
he also suffered imprisonment for about five years and a half for the Gospel`'s sake.
His residence was for many years at Monyash, in Derbyshire,
but in 1708 he removed to Needham, and resided with a daughter, at whose house he died,
in 1711, aged 68, having been a minister about 40 years.

[.embedded-content-document.letter]
--

[.letter-heading]
John Gratton to William Ellis.

[.signed-section-context-open]
6th of 10th mo. 1706.

[.salutation]
My Dearly Beloved and Truly Esteemed Friend, William Ellis;

These come dearly to salute you and your comfortable wife, desiring, in much love,
that these lines may find you both in good health, and every way, in soul, body,
and mind, well in the Lord, who is the true treasure and portion of his poor children,
who, though they be poor,
have been made by him instrumental to direct and invite the poor,
and tell them where there is plenty of true riches that will never decay,
and that no thief can steal away.
Blessed be the Lord! he has taken a remnant out of the sorrows
of hell into heavenly places in Christ Jesus,
where true joy and comfort are.
Praise be to him forever!
I pray God preserve us in his holy Truth, alive to God all our days, to his own glory.
Oh, there never was more need of the secret preserving hand of God than now!

Dear friend, I am kept very weak in body, unfit to travel,
and my wife is fallen lame and weak also, else I often think of you,
and should be glad to come once more to see you, in the will of God,
and in the enjoyment of him, without whom I am worse than nothing, so can do nothing.
I desire your remembrance of us; I was glad of Lawrence King and his companion`'s visit.
So in true love, that is beyond words, in which you and your dear wife are near me,
I thank God,

[.signed-section-closing]
I am your sincere friend and brother,

[.signed-section-signature]
John Gratton.

--

[.embedded-content-document.letter]
--

[.letter-heading]
William Ellis to Francis Tomes.

[.signed-section-context-open]
Airton, 1706.

[.salutation]
Kind Friend, Francis Tomes,

This comes with remembrance of true and unfeigned love to you and Friends,
as you see fit, and to let you know of my safe arrival in my own country.
Though I went through much difficulty and exercise in my travels after I left you,
yet the Lord stood by me in all trials; so that at my return,
I could not express his goodness to me;
and because of that and all other of his mercies to me,
my heart and soul are engaged to praise his holy name.
And now, my friend, seeing it fell to my lot to visit you,
and I had times of comfort among both old and young,
therefore my heart is deeply concerned for your welfare,
and I desire that all Friends may walk up to the Truth.
Let the time past be sufficient wherein we walked
according to the course of our vain mind,
so that our diligence may be doubled to redeem our misspent time,
so that we may increase our love to God, and one to another.

And let all Friends be careful to meet together often, and in due time,
and let the power of Truth fill all your hearts; and in that,
both old and young will grow in sincerity;
and if it please the Lord to open the hearts of any among you,
be tender to them and wait to help them on in their service for the Lord;
and if any that be of a tender age should give a word of exhortation,
let no man despise their youth; for it was said of old,
that out of the mouths of babes praises should arise: and again,
the stammerer should speak plainly,
and "`the tongue of the dumb shall sing,`" and the simple shall learn doctrine;
and says the prophets, they shall grow as calves in the stall,
and as willows by the water-courses.
They were to wait to see the Truth at work in the hearts of a young generation,
and to rejoice thereat.
And I desire that Friends`' care may increase over the negroes,
and labour to bring them to the feeling of the life of Truth;
and that when out of meeting they may learn to be grave and sober;
and thus my soul travails that the Lord`'s name may grow famous among the heathen.
Here are three of our country Friends, that I hope may bring this to you,
they are true men, and will be of good service,
if it please God to bring them safe to you.
I desire you to remember my true love to Ann Wilson if alive, and James Hill`'s widow,
and to Friends in general.
This comes with true love to you and your wife, and so concludes your truly loving friend,

[.signed-section-signature]
William Ellis.

--

[.embedded-content-document.letter]
--

[.letter-heading]
George Rook to William Ellis.

[.signed-section-context-open]
Dublin, 25th of 10th mo. 1707.

[.salutation]
Dear Friend, William Ellis,

With endeared love, I very dearly salute you and your dear wife,
with whom my spirit has sweet unity in the life of Truth; and now, my friend,
I send you a paper enclosed, written by our friend William Edmundson,
who has had a weighty concern upon him for a right
regulation in men`'s and women`'s meetings,
that all that meet about the Lord`'s business may
be rightly qualified and gifted for that service,
and that none may be admitted nor continued members of such meetings,
but faithful men and women, according to the first settlement;
and especially of the Meeting for Sufferings, in London.
It might be of great service to all the Churches if it were made up of such weighty,
sensible members, as the matters of that meeting require such; but as the case stands,
many concerned Friends are uneasy about that meeting, not knowing the boundaries thereof,
nor indeed who are the proper members thereof,
therefore it ought to come under your serious consideration,
to have things put in order in that meeting, and especially in your county,
where there is both a large and weighty people that
might give good help in this good work.

William Edmundson`'s dear love is to you and your wife, and faithful friends;
and he bids me send you one of the papers, to communicate as you thought fit,
and he desires me to tell you that he would be glad of a few lines from you;
but he desires that you will excuse his writing to you, for he says his hands shake so,
that he cannot do it.
I was willing to give this account of him, because you may think long of hearing from him.
I was with him in the north of this nation just before our Half-year`'s meeting;
we were five or six weeks out and had good service;
for the Lord`'s goodness went along with us and gave strength
to old age beyond the ordinary course of nature.
Give my dear love to Aaron Atkinson when you see him,
and tell him I should be glad to see him and you here.
Our Friend John Bradley landed here yesterday, being come to give us a visit.
This is all at present from your steadfast friend, honest but poor,

[.signed-section-signature]
George Rook.

--

George Knipe, of Hawkshead, in Lancashire, the writer of the following letter,
was brought up in profession with the Episcopal Church,
but joined the Society of Friends about 1675, being then in the 22nd year of his age.
Previous to this period he was vain in his conduct,
and given to the singing of idle songs.
The change produced in him by attention to the light of
God`'s spirit shining in his heart was very conspicuous.
After experiencing the work of repentance and sanctification
of the Spirit unto a good measure of obedience,
he became a preacher of Christ, and from about his 32nd year,
spent most of his time in publishing the glad tidings of the Gospel.
In this service he made many apostolic journeys in Great Britain and Ireland.
He died in 1709, in the 56th year of his age.--See [.book-title]#Piety Promoted#, Part V.

[.embedded-content-document.letter]
--

[.letter-heading]
George Knipe to William Ellis.

[.signed-section-context-open]
London, 16th of 8th mo. 1708.

[.salutation]
Dear Friend, William Ellis,

I make use of this opportunity to write to you,
having heard of your affliction and weakness, I was sorry and sympathised with you;
and my cry and prayer to God was, that he might give you patience,
and assist you with his merciful hand,
and sweeten your racking pain with his divine presence, whose grace is sufficient,
and his power is made manifest in weakness.
My cry and secret breathings were, that the Lord, who can and does give time,
might spare you a little longer, and that it might be to his glory and praise,
and to your comfort; and when I heard of your recovery I was glad, I can honestly say;
and I hope it will be for more service to him and his Truth, and people,
whom he has inclined your heart to serve.
O! what need have we all to be devoted to do all the good
we can in the little time the Lord gives us,
that we may give up our accounts with joy, and have the sweet sentence of "`Well done,
good and faithful servant, enter into the joy of your Lord;`" and,
"`Come you blessed of my Father,
inherit the kingdom prepared for you from the foundation
of the world;`" then will it be said to us,
When I was hungry you gave me food; and thirsty you gave me drink;
and naked you clothed me; and sick and in prison,
you came to visit and administer unto me.
Oh this is precious, sweet, and profitable!
This looks very glorious and beautiful; it has the image of the holy Jesus,
our holy mediator, and heavenly pattern and example, whose steps we are called to follow,
who was not of this world, who came not to do his own will,
but the will of him that sent him; therefore the world hated him without a cause.
His kingdom was not of this world, and his servants have not their treasure here.
I observe that one said he would follow the Lord whithersoever he went;
Jesus answered him thus; "`The foxes have holes, and the birds of the air have nests;
but the Son of Man has not where to lay his head;`" from which we may infer the meaning,
If you follow me you must not expect great palaces and preferments in this world;
but must leave them,
and walk and live by faith in him who clothes the lilies and feeds the ravens.
This is a hard task for a carnal man to be reconciled to,
and it was so for the young man that went away sorrowful,
because he had great possessions, when our Saviour said,
"`How hardly shall they that have riches enter into the kingdom of God!
For it is easier for a camel to go through a needle`'s eye,
than for a rich man to enter the kingdom of God.`"
God Almighty helps us, that our hearts and minds may be heavenly,
that our treasure may be in heaven, then our hearts will be there also.
I am a poor pilgrim, and have been exposed to many trials, exercises and afflictions,
yet I am alive to breathe a little, so long as God pleases.
I have had a deep trial of late, yet the Lord has helped me,
and given me my life for a prey.
I have had many shakes, if I had not trusted in God I had not stood.
His hand has upholded me, he has hid me in his pavilion from the strife of tongues.

I have been once more at the Land`'s End, in Cornwall;
I know not but it may be the last time: I have had no companion;
I had like to have dropped, but the Lord`'s power upheld me;
yet I was weakly and have got on but slowly of late.
I am spent,
but not without hope of a rich reward from the bountiful hand of a merciful God,
whose compassion fails not them who love and fear him.
In his sweet love I tenderly greet and salute you with your good wife,
and I desire your welfare every way as my own.
I hope I shall be preserved where I may labour for
Zion`'s prosperity and the peace of Jerusalem;
for they prosper that love her and favour her dust,
and that cry and cannot hold their peace until her
righteousness be as the sun at noon day.
I would not load you with lines.
William Penn is at liberty.
Pride grows to a great height in this nation.
The Lord, I am satisfied, will bring it down.
I commit you to the protection of God, who will not fail us as we keep true to him.
I conclude your true and constant friend in my measure of grace,

[.signed-section-signature]
George Knipe.

--

[.offset]
The following letter from William Edmundson appears to have
been written when he was about 81 years of age.

[.embedded-content-document.letter]
--

[.letter-heading]
William Edmundson to William Ellis.

[.signed-section-context-open]
Dublin, 11th of 9th mo. 1708.

[.salutation]
Dear William Ellis;

I received your loving and brotherly letter per our friend and brother, Lawrence King,
and likewise another which you wrote in Lancashire,
and which I received in the same entire kindness
and brotherly love in which they were written;
and to make my return, am glad still to hear from you, and of your integrity,
which you hold fast for the Lord, and his blessed Truth,
and which integrity never wanted a reward.
I am sorry for your affliction by reason of that painful infirmity that attends you,
but may not advise you to submit to an operation for it,
for that might shorten your days, as it has done those of many others within my time.

And now my friend, I am in this city on account of Truth`'s service;
it being the time of our National Half-year`'s Meeting,
where we have an account of Truth`'s affairs, and of Friends in every quarter,
and of the care of Elders and concerned brethren,
that all may be well in the Church of Christ,
and that the plantation of the Lord of Life may be kept clean.
But this is a hard labour and requires great diligence and skill;
weeds of several kinds shoot up so fast, and make such a specious show,
and are of such fine colours, as though they were the very choice and wholesome herbs,
and the sweet and pleasant flowers in the garden;
this is particularly the case with that presumptuous weed,
the love of the greatness and riches of this world, and the earnest pursuit after them;
it is a surfeiting weed,
and surfeits those noble parts in man which otherwise are capable of serving the Lord.
We have waded through the service belonging to this meeting,
through the continued assistance of God`'s goodness and heavenly wisdom.
For the particulars I shall refer you to the bearer, being straitened for time.
My unchangeable love to you in the unchangeable, blessed Truth,

[.signed-section-signature]
William Edmundson.

--

[.embedded-content-document.letter]
--

[.letter-heading]
Thomas Rodman to William Ellis.

[.signed-section-context-open]
Rhode Island, 22nd of 10th mo 1708.

[.salutation]
Dear Friend, William Ellis;

I received your kind and loving letter some time past,
but I must acknowledge my negligence in not writing to you;
often I remember your charge to write every year:
however I am glad of this opportunity by our friend John Hulley,
a young man that has been lately convinced of the Truth here;
he has been to Barbados and Jamaica to visit Friends there,
and now has laid before Friends his intention of visiting Friends in Old England,
his native country.
He is of a blameless conduct, and I hope Friends will be tender towards him.
My name is not at his certificate, I not being at the meeting when it was granted.

Dear William, although I have not so frequently written to you,
yet you are sealed in my heart; and your service here on this Island,
God has blessed with good effects,
and particularly the Lord has opened our hearts to build a fair, large meetinghouse;
also at Dartmouth, Sandwich, Naragansett Province,
meetinghouses are built since you were here.
The testimony that God gave you to bear with power and virtue, has awakened many.
Friends are generally well, and the Truth prospers,
and our meetings of business are carried on in the unity of the Gospel.
I heard by John Fothergill`'s letter, of your being at the Yearly Meeting in London,
sound in faith, though weakly of body.
The Lord knows what is best; his left hand shall uphold, and his right hand will defend.
I am weakly and crazy myself, but rather better than I have been for some years past,
for which with manifold other mercies, I desire I may bless the Lord;
and in and through all, I can truly say, It was good that I was afflicted.
I cannot get near enough to manifest my love to you, but in our love to the Truth,
we are sweet and pleasant together.
John Fothergill and William Armistead have left a sweet savour behind them.
I hope the Lord will reward them,
and all his servants that he is pleased to concern in his work.
My love salutes you and bids you, Farewell!

[.signed-section-closing]
I am your friend,

[.signed-section-signature]
Thomas Rodman.

--
