== Chapter XVII.

[.chapter-synopsis]
* Notice of a Yearly Meeting at Lancaster by John Kelsall
* Decease of William Ellis
* Notice of Abigail Stott
* Remarks respecting the recording of Ministers
* Ministers in Settle Monthly Meeting coteraporary with William Ellis
* Abigail Stott`'s Testimony respecting William Ellis.

The Correspondence of William and Alice Ellis being now brought to a close,
the following notice of a Yearly Meeting at Lancaster,
in which the former took a prominent part, claims a place here.
This Meeting was held in the Second Month, 1709,
and at an interval when William Ellis was a little recruited from
the effect of the malady which wore down his bodily powers,
and at length caused his death.
The account is from the pen of John Kelsall, who was a schoolmaster at Dolobran in Wales.

[.embedded-content-document.letter]
--

I went to the Yearly Meeting at Lancaster.
The public meetings were attended by a very great number of Friends,
and many heavenly testimonies were borne,
and much counsel and sound advice were given in the openings of Truth,
for Friends to keep in faithfulness.
Then came on the Quarterly Meeting, where things were managed in great calmness,
love and unity;
and a good account was given from various places of the increase and prosperity of Truth.
At the close of this, a very solemn weighty parting meeting was held.
Great indeed was the power and presence of the Lord in that assembly;
his divine overshadowing arm,
and wing of love were abundantly known and manifested at that time; and a sweet,
pure current of life largely flowed through the meeting,
to the great joy and rejoicing of the faithful,
whose souls were sweetly refreshed together,
and who were constrained to speak well of the name of the Lord.

Among other brethren, our dear friend, William Ellis, had a blessed opportunity,
and was carried on in the power and life of Truth, even beyond a usual manner.
Oh!
I think it affects my heart to remember the glorious
presence of the Lord that appeared with him,
he being full of love, full of zeal, full of courage,
and as one triumphant over the devil and the powers of darkness,
and in the divine region of light and life.
This was indeed a glorious season;
and the rays and majesty of Truth were largely extended
and stretched over that large assembly,
so that many were made to say afterwards, that they had not known the like.
And in this exaltation of life and power, the meeting concluded.

--

Tradition says that Alice Ellis was absent from home
at the time of the decease of her husband;
that after he returned from Lancaster he reluctantly consented
to her leaving him in order to attend a meeting at a distance;
and that on her setting out on the journey,
he walked to an adjacent rising ground and followed
her with his eyes as far as he was able,
under the impression that he should see her no more in this world.

Soon after her departure he became worse and declined rapidly,
but manifested a sweet state of mind and a readiness to depart,
which were very comforting to his friends.
In conversation with one of them, a short time before his decease,
he alluded to the day of his convincement of the Truth as it is in Jesus, saying,
"`It was a glorious day for me,`" and he added,
"`that he had large tokens that the day of his death would be so likewise.`"
He died at his own house at Airton, on the 4th of the 4th month, 1709,
aged nearly 51 years, having been a minister 30 years; and on the 11th,
his remains were interred in the burial-ground attached
to the meetinghouse adjacent to his dwelling,
and which he had given to the Society of Friends.
A large concourse of his fellow-professors and neighbours attended on the occasion,
which it is stated,
"`was eminently owned and overshadowed with the Lord`'s power and presence.`"

After the decease of William Ellis several testimonies
to his character and services were drawn up.
The following was from the pen of his old mistress, Abigail Stott,
to whom allusion is made at pages 2, 18, 45 and 46 of this volume.
She appears to have been of a class of persons,
who seem to have been numerous in the early days of the Society of Friends,
and who were at times engaged in vocal labour as ministers in their own meetings,
but did not travel in this work.
As the practice of recording ministers did not take
place in the Society of Friends till about 1773,
and testimonies respecting them were seldom if ever issued
on their decease in the earlier periods of the Society,
unless the parties had travelled much in the service of the Gospel,
we have little official evidence as to who were considered
accredited ministers in that day,
unless they had certificates granted them for service out of their own meetings.
The granting of these certificates might indeed be considered as
the official acknowledgement of ministers by their monthly meetings;
nevertheless many, who probably never applied for such certificates,
were in the practice of attending the meetings of ministers,
having been invited to do so by some of the members of these meetings;
such invitation at that period being considered a sufficient introduction.
John Stott, the husband of Abigail Stott, mentioned at pages 2 and 45,
and Ann Kingshall or Killinghall, mentioned at page 46,
were also probably ministers in Skipton Meeting,
of the same description as Abigail Stott.

Those who by having had certificates from Settle Monthly Meeting,
for the performance of religious services in other parts of Great Britain,
in Ireland or in America, between 1636 and 1709,
and who were consequently contemporary with William Ellis,
and constituted the chief part of the Meeting of Ministers at Settle,
mentioned at pages 71, 72, etc. were--Richard Wildman, James Wildman, Julian Frankland,
Thomas Carr, Samuel Watson, Mary Watson, Jennet Stow, Jane Sedgwick, Thomas Rudd,
Joseph Nicholson, William Birkbeck, William Armistead, Thomas Wilde, John Potter,
Stephen Sedgwick, William Slater, Lawrence King, Phoebe Tillotson, and Ann Hird;
and there is evidence that James Walton,
Alice Ellis and John King were also ministers at this period.

[.embedded-content-document.testimony]
--

[.letter-heading]
A Testimony concerning the Convincement of that faithful Servant of Jesus Christ,
William Ellis, of Airton, in the County of York, deceased, by Abigail Stott, 1709.

[.centered]
_"`The memory of the just is blessed.`"--Prov. 10:7_

[.small-break]
'''

It was his lot before his convincement, to become a hired servant to my husband,
John Stott, of Skipton, in Craven, in the county aforesaid, linen-weaver, also deceased;
and when he had been about two years with us,
there was a meeting appointed and held at Lower Bradley, about two miles from Skipton,
aforesaid, in the Third Month, on the fifth day of the week, called Hallow Thursday,
1676; to which meeting he asked of me if he might go;
and with much freedom I allowed him that liberty.
In this meeting the Gospel was so effectually preached by Roger Haydock,
a minister of Jesus Christ, that when William Ellis came from that meeting,
it did plainly appear to me and others,
that he was not only convinced of the way of Truth and righteousness,
but also in a good measure brought into obedience to the same.
He was soon tried, and he resisted many delights,
pleasures and vanities which before he had served, and been in bondage to;
and he was now in an extraordinary manner, awakened to righteousness.
It is with me to say, and surely believed by me,
that he witnessed the day which the prophet foretold,
Mal. 3:1,3,--"`The Lord whom you seek shall suddenly come to his temple,
even the Messenger of the Covenant,`"--"`and He shall sit as a refiner,
and purifier of silver, and He shall purify the sons of Levi,
and purge them as gold and silver,
that they may offer unto the Lord an offering in righteousness.`"
I had the opportunity daily for about three years, to observe his life and conduct,
he living about so long a time with my said husband,
from and after the day of his convincement; in all which time he was of a humble,
peaceable, and self-denying life, and was circumspect both in his words and ways,
lest he should offend the Lord.
His conduct did declare his love and pure zeal to God and his commandments.
Matt. 22:37-39, "`You shall love the Lord your God with all your heart,
and with all your soul, and with all your mind.
This is the first and great commandment; and the second is like unto it,
You shall love your neighbour as yourself.`"

Certain I am that he was faithful and laborious in his service to us,
and a good example to our servants;
a reprover of vice and of the appearance of evil in our children,
and often he did restrain them from vanity and that which corrupts youth.
Also he was one that often, when he might have slept, laboured with his hands,
that he might get to meetings,
and he did use often to retire after he had done our service,
into places more free from noise and hurry.
He loved Friends that were honestly minded, whether poor or rich,
but was more especially a visiter of the needy;
he loved all our neighbours that in any measure were well-minded;
he often suffered and was reviled for confessing Christ before men by a holy, innocent,
harmless life; and once as he was passing on a First-day through Skipton,
on the account of religious worship, he was by violent hands,
taken and imprisoned in the toll-booth; and in these and many more trials he met with,
his mind was borne up with much patience and a Christian-like spirit,
rejoicing that he was a sufferer for Truth`'s sake.
Thus, he having through faith in Christ Jesus, denied himself of what the glory,
friendship, and wisdom of this world could promise unto him,
it pleased the Lord to give him an earnest of a glorious
and heavenly kingdom that endures forever.

Not long after he went from us to live at Airton again,
he bore a public and faithful testimony, attended with power and authority from heaven.
The grace given him was not bestowed on him in vain; for in it he faithfully laboured,
and was concerned abundantly, that many might be made partakers of the heavenly calling.
And as he preached the Kingdom of Heaven faithfully,
so he held forth the true means and way to it;
he did not make use of other men`'s lines till he was made a witness thereof himself;
neither laid burdens on other men`'s shoulders that
he did not lay hold on with all his might;
for the marrow of pure religion was displayed by him.
He visited the fatherless and widows in their afflictions, and others under necessities;
and as God Almighty had blessed him with a generous mind and temper of doing good,
it often prospered in his hands,
so that he saw many relieved by the unspeakable ways
and means which God made him instrumental in;
whereof, in an extraordinary manner,
I was a partaker many times during the space of twenty-six years,
I being a widow so long.
And he sympathised with those in any spiritual need.

Being travelling on the account of his service in the ministry in the year 1688,
though several miles from my family (as himself told me),
there was a concern came upon him touching my eldest son, called Jacob,
so that when he returned he came to visit us, and finding him sick and weak,
he was concerned in prayer and supplication to the Lord for him, which was acceptable;
so that my son, who many times before had spoken to me his dissatisfaction,
touching his future well-being, declared unto me his satisfaction, with much assurance,
concerning a lively and eternal hope given him, while William was yet praying;
in which hope, having also received a heavenly earnest,
he continued to the time he was taken out of this life, which was about two weeks after,
and on the 20th day of the 11th mo. 1688.
As touching more of William Ellis`'s works,
and the labour he was concerned in for the good of the church, in particular and general,
in this nation and other nations, I hope a further account may be given,
to the end that our heavenly Father may be glorified,
and that we may bring forth much good fruit.

[.signed-section-signature]
Abigail Stott.

--
