== Chapter XVIII.

The Testimony of Alice Ellis concerning her Husband--Thomas Thompson`'s Testimony concerning
William Ellis--A Brief Account of the Life and Death of William Ellis from Settle Monthly
Meeting--The Testimony of York Quarterly Meeting concerning William Ellis.

The following Testimonies respecting William Ellis were printed in a pamphlet entitled,
"`A Brief Account of the Life and Death,
and some of the Gospel Labours of that faithful Servant and Minister of Jesus Christ,
William Ellis; London: Printed and sold by J. Sowle, in White Hart Court,
in Gracious Street, 1710.`"
Few copies of this tract, are now to be found;
it presents a summary of the life and labours of William Ellis,
and consequently claims a place in this volume.

The Testimony of Alice Ellis concerning her dear husband.

He was a man that feared God and eschewed evil: his delight was in Truth`'s prosperity;
for which he travailed both in body and mind;
not satisfying himself with a bare speaking of things,
or exhorting of others to practice pure religion,
but he himself was careful to practice the same.
He was zealous for the honour of God; in his ministry powerful; and fervent in prayer;
it being as food and drink unto him to serve the Lord and his people.
He was a loving husband; and in great unity and fellowship, we lived together,
and had the blessing of being help-mates one to another, both spiritually and temporally,
being married above twenty-two years;
in all which time I do not remember of any angry words that passed between us.
I had great unity with his travels in Truth`'s service;
having many times a sense thereof upon my own spirit,
before he has acquainted me therewith.

The loss of him deeply affects my heart,
and causes sorrow many times to take hold upon me;
but not like those that sorrow without hope,
I being fully persuaded that my loss is his gain, and desiring that I may so walk,
and finish my course in the Truth, that when it shall be my lot to follow him,
I may partake of that joy and glory into which, it is my belief, he is already entered,
and lives to praise the great and mighty God forever and evermore.
He was also a kind friend and a good neighbour, delighting to do good unto all,
but especially to the household of faith.

I shall not much further enlarge, knowing that several of his dear friends and brethren,
with whom he was much conversant, and engaged in Truth`'s service,
have given a more full account of his convincement,
labours and travels in the work of the ministry, and service of the church of Christ,
both in this nation, and other countries beyond the seas.
But with hearty desires that our most gracious God
may raise up many faithful men and women,
to bear witness unto his unchangeable Truth, such as are lovers of God,
and will feed the flock of Christ, of a willing mind, I shall conclude,
and am a well-wisher to Zion`'s prosperity,
and to all such as love the Truth of our Lord Jesus Christ.

Alice Ellis.

The 10th of 2nd mo.
1710.

Thomas Thompson`'s Testimony concerning William Ellis.

It is in my heart to give forth this testimony concerning
my dear friend and brother in Christ,
William Ellis, whom I dearly loved, esteemed, and honoured, for the works`' sake,
whereunto he was called, and wherein he approved himself a faithful labourer, until He,
who called him, gathered him into that rest which is glorious,
there to enjoy the effects of his faith and fruits of his labours everlastingly.

This I can, and do testify, from a certain knowledge,
that he was a man that loved and feared God; and as he loved the Lord with all his heart,
so he sought to exalt the Lord`'s name, and he stood against wickedness,
being filled with zeal for the glory of God,
who had anointed him to preach the everlasting Gospel to them that dwell on the earth,
and had given him a good understanding in things appertaining to his kingdom.
In the year 1686,
it was his lot to visit Friends`' Meetings in the east part of Yorkshire, and I,
with many others, may say,
that he came among us in the blessing of the Gospel of Christ,
in whose dread he sounded forth the day of the Lord,
and proclaimed liberty to the captives.
Dreadful was he to the workers of iniquity,
who often felt the weight and force of his weapon, i. e., the word of God,
which was as a fire in his heart,
and as a sword dividing between that which served God and that which served him not;
but to the mourner in Zion his words were sweeter than honey and smoother than oil.

From that time I became acquainted with him,
and found him to be more in the root than in appearance; his company was pleasant,
his conversation easy and delightful.
A great lover of unity and concord was he,
and he laboured greatly to promote the same among his brethren;
his concern was great for the increase of the government of Christ,
and for the promotion of good order and discipline in the Church; he struck at vice,
encouraged virtue, and laboured with all his might,
that Zion might have on her beautiful attire,
that so she might shine in the light and glory of her Head and Husband.
And as he abhorred pride, so he commended humility both in practice and doctrine,
being himself plain and exemplary, free from affecting popularity,
and his testimony being lively and instructive, full of marrow and substance,
though not decked with florid expressions or rhetorical strains.
It was not wisdom of words that he minded, nor how to please itching ears;
but to please God was his care, and to preach the Gospel so to men,
as that what he spoke might answer God`'s witness in all;
and therefore he preached the Truth in the power, plainness, and simplicity of it;
and yet at times there did, a sort of a heavenly eloquence, as well as a heavenly melody,
attend him, because his heart was filled with the Spirit of life,
and he spoke in the power and demonstration thereof,--he spoke as one that had authority,
and not as the Scribes,--and as the Lord had led him through many states,
and been with him in many conditions, so He gave him, many times, a word in season,
not only to the weary traveller for his encouragement,
but that which suited various states and conditions; yes, to my knowledge,
he has often hit the mark, and spoken to people`'s states in a meeting,
as if he had known them, though he was at that time altogether a stranger.
Truth opened things to him, and through him,
to the comfort and satisfaction of such as loved and lived in the fear of God.
He was beloved in his own country, respected in his travels, both in England, Ireland,
and America, for the Truth`'s sake, in which he was serviceable to many.
He was a generous man, and a good Christian, given to hospitality, apt to teach.
Example in him went along with precept,
not being more forward to advise others to do good, and to be liberal to the poor,
than he was to do so and be so himself.
In a word, as his life, since he received the blessed Truth,
was a continued series of evidences of the goodness of God,
the Almighty helped him so to walk and finish his course,
as that he has left a good savour behind him, and his memorial is precious.

Thomas Thompson.

Hitchen, Hertfordshire,

31st of the 5th mo.
1710.

A Brief Account of the Life and Death of William Ellis, from Settle Monthly Meeting.

William Ellis, son of Stephen Ellis, of Calton,
a town not far distant from Skipton in Craven, in the County of York,
was born in the 8th month, 1658.
His father was by trade a linen-weaver, and instructed his son William in the same trade,
when capable thereof, until he attained to the age of sixteen years,
about which time he went to live as a servant with John Stott, of Skipton aforesaid,
linen-weaver, with whom, after having lived the space of two years, it so fell out,
that there was a meeting held at Lower Bradley,
two miles distant from the place where he then lived.
That faithful servant of Jesus Christ, Roger Haydock,
providentially happened to be at this meeting; and William having knowledge thereof,
and his master and dame being of that Society of people in scorn called Quakers,
he asked leave of them to go thereto, who readily replied, he might go.
At this meeting his heart and understanding were so effectually reached,
that he was thoroughly convinced of the ever blessed Truth, which he, quickly after,
was concerned to promote the honour of,
being of a circumspect carriage and behaviour among the family in which he then lived,
thereby showing a good example to his master`'s children, like Joseph, of old,
in whose heart the fear of God was,
evidently manifesting his growth and prosperity therein.

After the space of three years from the time of his convincement, he removed to Airton,
a town near adjoining to the place where he was born.
Soon after his removal he was livingly opened in a public
testimony to and for the Truth he was made partaker of;
and in due time he became an able minister thereof;
approving himself yet more and more a good example therein to others.
And it is worth our observation, that although he had little or nothing from his father,
he being but of low circumstances in the world,
yet he soon began to be helpful in the Church,
by distributing towards the relief of the poor,
out of what he got by hard labour and great diligence and industry in his calling,
and part of which also he freely spent upon Truth`'s account in other ways.
He freely gave up a great deal of his time to attend meetings,
not only such as were for public worship, but also meetings,
for business and the affairs of the church:
he was a diligent attender of these while but young;
and though he was not forward to speak in such meetings, having a reverent esteem for,
and regard to, them that were in Christ before him, and kept their places,
yet he was in those times serviceable,
being in a deep and weighty travail for the honour and prosperity of Truth,
and that the wisdom of God might open in Friends, that therein,
all things relating to the church`'s affairs, might be managed.
But it was not long before that divine and living spring of life,
that often opened plentifully in him to the filling of his heart,
gave him boldness to speak forth what was upon his mind, in meetings for business,
in which he was well received, being always careful to speak in fear,
and in a sense and savour of life, demonstrating thereby a Christian spirit,
in which he was a good pattern and lively example to others,
always demeaning himself in great humility, so that he became very serviceable,
both in the Monthly and Quarterly Meetings to which he belonged,
and in other meetings for the same service, in other places where his lot was cast,
he being zealously concerned to promote and establish good
order and sound discipline in the Church of Christ.

And although, as before observed, his beginning was but small,
having little or nothing save what he laboured for,
yet it pleased God to bless his endeavours with success,
so that his outward substance increased; and as that was enlarged, so his heart opened,
and he gladly made use of opportunities in which he might
lay out a great part thereof in the service of Truth.
He often exhorted Friends to keep out of worldly-mindedness,
and to labour to keep themselves from being leavened into a strait,
niggardly and narrow spirit, that would not allow them to serve Truth freely,
as they ought to do; this in all likelihood he had good authority to do,
being himself a good example in this respect; for although he was industriously careful,
and not negligent, nor slothful about his outward concerns,
whereby his substance in the world did considerably increase,
yet would he not impute the same to his own doings,
neither was his mind much taken up therewith;
he looked upon it only as the favour of the Almighty to him,
and therefore thought himself under the greater obligation
to lay out the same to the utmost of his strength and ability,
in order to promote the interest of Truth,
and the honour of that worthy and precious Name, in which he had believed,
and which had also been his strong tower and rock of defence,
in the depth of many exercises.

It may be truly said,
he was abundantly more industriously concerned on account of the Truth,
than on the account of his outward and temporal affairs; and as,
after the time of his convincement,
he was all along careful to behave himself so as that he might not be a burden,
or cause of exercise to his faithful brethren,
nor bring trouble in any case upon the church, but on the contrary,
be serviceable and helpful to the same according to his measure,
so was he also careful to walk among his neighbours and those he conversed with,
as that he might demonstrate unto all,
that the whole aim and drift of his mind was chiefly to
promote Truth and righteousness in his day and age.
And this undoubtedly he did, with all his might and strength,
for which we believe his reward is sure with the Lord forevermore;
an earnest of which we are fully satisfied he had many times plentifully given him,
while in this earthly tabernacle.
This was so sweet unto him, as he often used to say, that for the sake thereof,
he did not spare devoutly to offer up his whole strength, and the prime of his years,
even for the promotion of the blessed Truth, by which he had been so eminently visited,
and whereby he was made instrumental for the good of many.
Under these qualifications he was made serviceable various ways,
so that many have cause to lament the loss of him, and more particularly we,
his friends and brethren, among whom, for the most part, he resided,
who also had the most immediate and particular benefit of his service and company.
The loss of him would undoubtedly sadden many hearts,
were they not fully satisfied that his departure was in peace;
and though his body be gone to the dust,
yet the remembrance of him is sweet and precious,
in which the faithful enjoy him in spirit, under a lively hope,
that the mighty Lord of the harvest, who raised him from a low degree,
and by his almighty power, made him a blessed and serviceable instrument in his hand,
is also able to raise up others in his room, for the carrying on of his own work,
to his own praise, who over all is worthy of praise, adoration and worship, might,
majesty and dominion, now and forever.

Thus having given some account of his convincement, and conduct of his life,
relating to his interaction in the world;
what remains is to give some further account of his ministry,
and labours and travels therein.
It was not long, as has been before observed, after he was convinced,
before his mouth was opened in a public testimony for the Truth,
in which he sensibly witnessed a growth,
being careful diligently to wait for the springings of life,
which is the root and supply of all sound and right ministry;
for he laboured more to grow in that, than in words without it,
although also very careful to keep to that soundness of speech that cannot be condemned.

Not very long after he was concerned in a public testimony,
he was drawn forth to visit Friends`' meetings not
far distant from the place of his abode,
as also in various places more remote, in which he had good service,
and was well received among Friends, to his and their mutual joy and comfort in the Lord.
And in the year 1694,
he had a concern upon his mind to visit the meetings of Friends in Ireland,
where he was likewise kindly received;
his visit being acceptable to faithful Friends in that country.
Under this concern he was enabled through the goodness of God unto him,
to perform what was required of him in that respect,
returning home again in much satisfaction and peace, as a reward for such, Ins labour.
After this he continued in his customary service, both at home and abroad,
many times visiting Friends in various parts of this nation, till at length,
it pleased the Lord to concern him to visit the people of God, in foreign countries,
to which he gave up; and way being made for him, for such a service,
and having the concurrence of his Friends and brethren along with him therein,
at length he set forward on his journey and voyage for America,
leaving his wife and family, in the Ninth Month, 1697.
He took shipping at Deal, in Kent, in the Tenth Month after.
He had a prosperous voyage, arriving on the fourteenth day of the First Month following,
in Maryland, where he visited Friends and had much service,
as well as in other provinces, as Virginia, Carolina, Pennsylvania, East and West Jersey,
New England, Long Island and Rhode Island, etc.
In these countries he had many large and precious meetings, esteeming it,
as he would often say after his return, as a merciful favour to him from the hand of God,
that he was enabled to go through what was required of him in that respect, adding,
"`Oh! it was well for me, that I gave up to that service in those days,
while health and strength of body were afforded me, for now,
I feel my natural strength is abated,
whereby I am the more incapable of performing such service.`"
Notwithstanding this, he would often be looking back with joy,
and rejoicing at those times,
praising God for the many mercies vouchsafed to him inwardly,
and whose divine arm of power was likewise near to protect him on his return;
he arriving again in England, the twenty-third of the Fourth Month, 1699.
He was absent from his native land in the aforesaid service,
upwards of one year and six months.

After this he travelled not very much, excepting in the county where he lived,
and some adjacent counties, as Bishopric, Westmoreland, and Lancashire,
etc. and several times to the Yearly Meeting at London.
He was for several years before he died, attended with various infirmities,
and particularly that of the stone, which much impaired his health;
nevertheless he mostly frequented the Quarterly and Monthly Meetings to which he belonged,
though many times with much difficulty, because of the infirmities of his body;
but at many times when the life and power of Truth was upon him,
he was borne up over his infirmity as though he were in no kind so afflicted.
Thus this faithful and upright-hearted man, being now unfit for long journeys,
and service in remote places,
such as he spared not to undertake when he found it his concern in his younger years,
laboured much in the service of Truth, on one account or other in his own country,
till toward the latter end of the summer, in the year 1708,
at which time his old distemper seized violently upon him,
insomuch that he was thereby brought very weak,
which weakness he continued under for several months,
not being able to stir much from his own house.

In this time his inward man was strong and his understanding clear;
so that Friends who went to visit him in the time of his sickness,
were often comfortably refreshed in beholding and feeling his spirit
in the power and dominion of the life of Jesus Christ,
which may truly be said, was his support over all his exercises.
But notwithstanding his former weakness,
about the latter end of the Twelfth Month or beginning of the Erst Month following,
he begun to recover somewhat,
and gathered strength so far as to get to the Monthly
and Quarterly Meetings to which he belonged.
In these he had as formerly, good service,
after which he was likewise enabled to go to the Yearly Meeting for worship,
held in Lancaster, in the Second Month, 1709.
In this meeting, powerful was that Hand and Arm, which guided and supported him,
under the conduct whereof, eminent were the Gospel truths,
which in that meeting were through him delivered, to the gladdening of many hearts;
the service whereof, we believe, will not easily be forgotten by a remnant,
and in which his faith was strong,
that Truth and the glory of it should yet more and more prevail and spread over nations,
even from sea to sea, unto the uttermost parts of the earth.

Thus having been supported by the Lord in his service, after that meeting ended,
he returned homewards,
after which lie weakened by degrees till the time of his departure, which was not long.
Many sweet and edifying expressions dropped from him in his illness,
by which it appeared he was ready to embrace death with cheerfulness of mind,
whenever it should please the Lord so to order it.
A few days before his departure, being visited by a Friend,
he began to speak to him of the day of his convincement, saying,
"`It was a glorious day for me;`" and further added,
that he had large tokens that the day of his death would be so likewise,
which we have good cause to believe was so to him.
He continued sensible, under his weakness of body,
until the time he drew his last breath, which was on the 4th day of the 4th month,
in the year 1709, and in the fifty-first year of his age.
He was buried on the 11th day of the same month, in Friends`' burying ground at Airton;
many Friends being present at the burial made up a large meeting,
which was eminently owned and overshadowed with the Lord`'s power and presence,
several living testimonies being there borne to the comfort and satisfaction of many.
+++[+++The said burying ground and meetinghouse were, some years before his death,
given and secured by the said William Ellis for the use of Friends.]

William Ellis was born the 5th of the 8th month, 1658,
convinced of Truth in the 3rd month, 1676, came forth in a public testimony, 1679,
died the 4th of the 4th month, 1709.

Signed in behalf of our Monthly Meeting, held at Settle, the second of the First Month,
1709, by

John Armistead, Sr., William Holt, Thomas Head, John King, John Tomlinson, Lawrence King,
Richard Wilkinson, Adam Squire, Thomas Wilde, Thomas Carr, John Moore, Sr.,
William Windle, John Atkinson, Robert Tunstall, John Weatherall, William Birkbeck,
Isaac Armistead, John Armistead, Jr., Simeon Wilkinson, John Bawson, Joseph Hall,
Richard Clough, William Stockdale, John Battersbie, William Slater, John Moore, Jr.

The Testimony of the Quarterly Meeting held at York, concerning William Ellis.

Our dear friend and deceased brother, William Ellis, of Airton,
within Settle Monthly Meeting, in the County of York,
departed this life the 4th of the 4th month, 1709.
He was a faithful labourer in the harvest of the Lord; he gave himself to spend,
and be spent in Truth`'s service, both in feeding the flock of God,
as also in the overseeing the same.
Being an able minister of the New Testament, not of the letter but of the Spirit,
his doctrine dropping down like dew, and like small rain upon the tender grass,
the Spirit of God accompanying him in the delivery of the same,
he was of great comfort and benefit unto the Churches, both at home and abroad,
where the Lord did order him.

The care of the Churches was also upon him,
for the peace and prosperity of which he travailed both in body and mind.
His labours and service for the work of the Gospel were much,
both in our nation and in several foreign countries, in which he approved himself,
as an able and faithful minister of our Lord Jesus Christ,
encouraging and strengthening the honest and tender-hearted, to hold on their way,
to the perfecting of the work of their salvation;
as also in warning and stirring up the careless and unfaithful,
to more diligence and watchfulness.
He preached with authority, in the spirit of the Gospel and the remembrance of him,
and of the heavenly sweetness that attended his ministry (who though dead,
yet speaks) is precious unto us,
and the unity and harmony which we had together with him,
cannot easily be forgotten by us.
His doctrine was deep, and his company very pleasant to his brethren;
he was given to charity, and used hospitality much,
his heart and house being very open to entertain such as travelled,
or were concerned in Truth`'s service.
Much might be said in the praise of such a faithful minister, who not only preached,
but in practice was exemplary to the flock; but Friends of the Monthly Meeting of Settle,
to which he did belong, having drawn up an account of the same,
we refer to it for further satisfaction, touching his labours and travels,
both in the work of the ministry and other services
of the Church of Christ Jesus our Lord;
beseeching Him who is Lord of the Harvest,
to send many such faithful labourers into his harvest.
As he lived in the Truth, so we believe he died in the Lord,
and now is at rest from his labours, and his works follow him.

Signed on behalf of our Quarterly Meeting, held at York, the 6th of the 2nd month, 1710.

Thomas Green, Thomas Aldam, Benjamin Hornor, Jeremiah Grimshaw, Robert Turner,
John Fothergill, James Simpson, John Richardson, Michael Robinson, Aaron Atkinson,
John Hillary, William Armistead, John Fielden, Francis Smith, Thomas Hammond,
Henry Jackson, Jr.
