== Appendix

[.blurb]
=== History of the First Gathering of Friends in Settle Monthly Meeting.

The following document contains a history of the first gathering of the
Society of Friends in the district comprised within Settle Monthly Meeting;
it leads to the period in which their further history for
nearly twenty years may be traced in the preceding pages.
It also exhibits an interesting view of the spirit of inquiry excited in that age,
and which seems to have been increased by the aspersions ignorantly or maliciously
cast upon the simple and truly Christian principles professed by Friends.
The zeal of the early Friends,
and the simplicity of the proceedings and the sufferings
of these early promulgators of the plain truth of the Gospel,
as well as the power and convincing efficacy attending their ministry,
deserve especial notice.

[.embedded-content-document.minute]
--

[.letter-heading]
Minute of Settle Monthly Meeting, 11th mo.
3rd, 1704.

[.small-break]
'''

John Moore, Joseph Nicholson, Thomas Camm, and William Armistead, give account,
that according as they were desired by Friends at our last Monthly Meeting,
they did collect the several accounts they now brought
in from the several particular meetings,
touching the labours, sufferings, and services of ancient Friends, not yet in print,
which being so collected and transcribed in one,
was delivered to Friends at the Quarterly Meeting,
and a copy thereof reserved in this meeting, which is as follows:

[.offset]
From our Monthly Meeting, held at Settle, the 22nd of the 10th month, 1704,
to the Quarterly Meeting at York.

[.salutation]
Dear Friends;

According to the request of the Second-day`'s Morning Meeting in London,
we have had under our consideration the most remarkable passages which we can remember,
touching the faithful labours in the gospel of Christ,
and effectual service of those who were first instrumental,
both in gathering and settling meetings, now belonging to Settle Monthly Meeting,
which do here follow.

Before the testimony of Truth, or the way of worshipping of God in spirit,
was published or declared in this latter age, by the messengers and servants of the Lord,
in these parts of the country, there was much talk and discussion,
of a people who were scattered up and down the country,
and more especially in the west and northern parts thereof,
who differed from other people in their belief concerning the principles of religion,
and worshipping of God; and in most parts they were slandered,
vilified and evil spoken of, +++[+++people]
saying that the false prophets were now coming which were spoken of in the Scripture.
But there were some who pondered these sayings,
and were desirous to know the certainty thereof.
And in process of time, in or about the year 1652 or 1653, it was so ordered,
that one of the servants and messengers of Jesus Christ, namely, William Dewsbury,
came to a town called Settle, in the west part of Yorkshire, on a market-day,
and stood upon the cross, and proclaimed the terrible day of the Lord,
which was hastening and coming upon the ungodly and workers of iniquity;
but he was soon pulled down, and a great tumult was made,
and he was much beaten and abused.
But after some time, being taken notice of by a young man whose name was John Armistead,
(who is yet living) was invited to go with him to his mother`'s house,
whose name was Alice Armistead, being a widow; where he went and lodged there.
And in the evening many people were gathered to the house, it being in the said town,
unto whom he declared fervently against the fruitless profession
of religion which was among people at that time,
and directed people to the measure of grace,
and gift of God`'s Holy Spirit in their own hearts,
whereby they might be taught how to worship God acceptably in his own Spirit.

And not long after this, it was so ordered,
that another servant and minister of the Lord, called John Camm, came into the said town,
on a market-day, and in the market-place began to preach the doctrine of repentance,
and the way of life and salvation, unto the people.
But they soon fell upon him with violence, and did beat and buffet him very much,
so that he received many strokes;
yet there were some who endeavoured to bear off some blows,
and to rid him out of their hands;
and after some time he was conducted to the house of John Kidd, in Upper Settle,
where there was a meeting in the evening,
and then things relating to the kingdom of God were plainly laid down by him.

Now, these servants of the Lord did not go away without leaving some impressions
on the souls and spirits of some of the inhabitants of the said town,
so that they were convinced, and came to witness the day of the Lord`'s power,
which broke forth more and more among them,
notwithstanding the cruelty which was used against the servants of the Lord;
so that there was a people gathered from the world`'s ways and worships,
to worship God in spirit; who for that end and purpose met often together for many years,
from house to house:
and many were convinced of the blessed Truth and added to those who at first believed,
so that their number increased considerably.
And in process of time,
a public meetinghouse was built by the said people in the said town of Settle,
where a meeting is settled and kept, known by the name of Settle Meeting at this day.
And moreover, from a part of the said meeting, there is now another meeting settled,
some few miles from Settle, known by the name of Selside Meeting;
so that the Truth had wonderfully prevailed, and does prevail;
blessed be the name of the Lord!

Also about the year 1652-3, came several of the servants and ministers of Jesus Christ,
namely: William Dewsbury, Richard Farnsworth, Thomas Stubbs, Miles Halhead,
and James Nayler, and preached the everlasting Gospel,
by which many were turned from darkness to light,
and from the power of Satan to the power of God.
And by their ministry, a meeting was gathered and settled at Scalehouse, near Skipton,
in Craven, in Yorkshire; and Truth gained ground greatly,
so that several were raised to preach the day of the Lord,
and salvation to mankind through the revelation of his Son, Jesus Christ,
in their hearts, of whom Richard Scostrop was one; who was born the 15th of the 4th mo.
1628, and was a persecutor of Friends; but the hand of the Lord was heavy upon him,
so that he sought to those whom he had sorely abused, and made confession to repentance,
and afterward received mercy from the hand of God;
and the Lord`'s power grew strong in him,
so that he was made to declare the power of God to mankind,
and became an able minister of the Gospel,
and travelled into Scotland and many other places in this nation,
to turn men from darkness to light.
And though he was born to some estate, yet for his love to the Lord Jesus Christ,
he left it all, and spent his days in his service,
and died in his travel beyond the seas;
and his memory is sweet this day among the brethren.
Also John Hill was brought into the work of the ministry,
who travelled through the most of this nation and Ireland, and some parts of Germany,
exhorting Friends to faithfulness, and to wait for the openings of life in them;
and great zeal was upon him to stir Friends up to meet together on the week-day,
declaring how God could sanctify mean things to Friends
who gave themselves up to serve him in their meetings.
He lived to a good old age, and died the 15th of the 12th month, 1684,
in unity with his brethren.

And the said meeting which was gathered and settled by those faithful labourers aforementioned,
now known by the name of Bilston Meeting, does remain;
and the power by which it has been settled is the
strength and uphold thereof unto this day.

Likewise near about the same time, the said William Dewsbury and James Nayler,
had some meetings some miles distant from Scalehouse aforesaid; but Truth getting ground,
and the number of Friends increasing about where they lived,
they settled a meeting near a village called Salterforth,
which is now become a meeting of a considerable number of Friends,
and is called by the name of Salterforth Meeting.

Also about the year 1652 or 3, it was so ordered, that some of the servants, messengers,
and ministers of Jesus Christ, were drawn to visit a people at,
or near unto a town called Bentham, in the west part of Yorkshire, namely,
William Dewsbury, Richard Farnsworth, Robert Hall, and John Snayden,
by whose ministry many of the said people were convinced of the Truth,
turned unto Christ their teacher, on whom they often met together to wait,
who gave them to witness the making good of his ancient promises,
that where two or three were gathered in his name,
his presence should be in the midst of them; by which they were strengthened,
and encouraged to continue their christian practice of meeting together.
And their number, since that time, has much increased,
so that they are now become a meeting of a considerable number of Friends,
which is called Bentham Meeting.

Now the aforesaid Robert Hall, having a concern upon him to visit the steeple-house,
at Bentham aforesaid, was sorely beaten and bruised,
in such sort that he died a short time after.
Moreover,
from the aforesaid meeting at Bentham (there being
some convinced) there is a part gone off,
and a meeting settled, known by the name of Wray Meeting, in Lancashire.
+++[+++Wray Meeting was commenced in 1689.]

Furthermore, George Fox, at his first coming into the north, which was in the year 1652,
was directed to the house of James Tennant, called Scarhouse, in Longstrethdale,
where he preached the Truth in the family; and by the powerful virtue of it,
the said James Tennant and his wife were reached,
so as to receive the Truth in the love of it; where a meeting was soon after settled,
and is continued to this day, known by the name of Scarhouse Meeting.
Now the said James Tennant became a serviceable man to Friends and Truth in his day;
which was not long after the time of his convincement,
being taken prisoner for his testimony against tithes, from which he did not decline,
but patiently endured close imprisonment until death.

In the year 1653, about the 6th month, came two Friends out of the North,
whose names were Thomas Vears and Christopher Atkinson, to a little town called Newton,
not far from Slaidburn, in Bolland, on a Seventh-day, at night,
and were received by James Bond, a poor man, and had a meeting the day following,
where several people were convinced; and the Second-day of the week,
another meeting at Cuthbert Hayhurst`'s, at Essington, where they were well received.
And a little after, came "`William Dewsbury to the house of John Crossdale,
and had some meetings thereabouts; and so came down to the house of Richard Leigh,
and stayed there three days and writ some books; and afterwards came to Essington,
to Cuthbert Hayhurst`'s, and had a meeting at Slaidburn, and was pulled down,
and the town was all in an uproar; but there were some that were convinced by him.
Not long after, John Audland came and had a meeting at Richard Leigh`'s,
and Alexander Parker, being come to his father`'s house,
from Lancaster where he was convinced, and Cuthbert Hayhurst also being convinced,
and both of them being called to the ministry,
with those others who were convinced by the Friends aforesaid,
began to keep a meeting near unto Newton, where there has been one continued ever since,
and is called Bolland Meeting.

[.small-break]
'''

Note.--The said Cuthbert Hayhurst afterwards became an able minister of the Gospel,
and travelled in the service thereof in various parts of the nation,
and some parts beyond the seas, as Jamaica; and afterwards,
with the unity and consent of his brethren, removed himself and family to Pennsylvania,
where he died in full unity with Friends.

--
